#   [Job Adv] (5th job)   5th Job : Arcane stone of Tynerium

sm.setSpeakerID(1540944)
sm.sendNext("Maple World is a world of order and rules whereas Tynerium is a world of chaos and uncertainty. FOr a long time we've been acting as the shadows of this world.")
sm.sendNext("Truth be told, I don't want to help Maple World, but our world is not complete without it. The Black Mage must be gone for our sake and for everyone else's")
sm.setPlayerAsSpeaker()
sm.sendNext("So are you going to help me?")
sm.setSpeakerID(1540944)
sm.sendNext("Huh? I didn't say that.")
sm.setPlayerAsSpeaker()
sm.sendNext("...")
sm.setSpeakerID(1540944)
sm.sendNext("...")
sm.setPlayerAsSpeaker()
sm.sendNext("...")
sm.setSpeakerID(1540944)
sm.sendNext("All right, all right, don't look at me like that. I'll help you. But I want to test you first. \r\n\r\n #L0#What test? #l")
sm.sendNext("It's a simple test to see how lucky you are. I'm going to send you out of this place. You'll have to come back, but the entrance to this place will have been moved someplace else. \r\n\r\n #L1# Wait, that's unfair?#l")
sm.sendNext("I'm not going to wait for you long. Prove to me how lucky you are. \r\n\r\n #b(Find a Horizon Portal near the upper side of the World Tree within 5 minutes.)")
sm.sendNext("This is what you want, right? I was going to give it to you from the start. Hurry, take it. \r\n\r\n #v2435736# #bArcane Stone of Tynerum x1")
sm.startQuest(parentID)
sm.completeQuest(parentID)#todo
sm.dispose()