# id 17007 ([Commerci] Bon Voyage 3), field 865000001
sm.completeQuestNoCheck(parentID)
sm.setSpeakerID(9390220) # Maestra Fiametta
sm.setParam(1)
sm.sendNext("You've been given 1 Commerci Denaro for the previous voyage. ")
sm.sendSay("You now know everything you need to know to grow rich. Keep at it, and before you know it, you'll be a billionaire. Ha.")
sm.sendPrev("I look forward to the day you join the ranks of Commerci's most wealthy. ")
sm.setParam(0)
res = sm.sendNext("Hello, #e#b#h0##k#n. Welcome to the Commerci Trade Center. \r\n#b\r\n#L0#Enter trade#l#b\r\n#L1#Stimulus System#l#b\r\n#L2#Move to the Merchant Union trade location#l#b\r\n#L3#The vessel's energy will be recharged manually.#l#b\r\n#L4#The goods will be manually restocked.#l")
sm.sendNext("You've earned #r#e30458#k#n EXP through your trades. You also have #b#e11#k#n Commerci Denaros and #d#e8544#k#n Mesos waiting for you.")
res = sm.sendAskYesNo("Do you want your voyage earnings right now?")
sm.createQuestWithQRValue(17011, "")
sm.createQuestWithQRValue(17012, "")
sm.createQuestWithQRValue(17013, "")
sm.createQuestWithQRValue(17014, "")
sm.createQuestWithQRValue(17015, "")
sm.createQuestWithQRValue(17023, "end=0")
sm.sendNext("There you go, allotment complete. ")
sm.openUI(189)
sm.createQuestWithQRValue(17011, "")
sm.createQuestWithQRValue(17011, "C=10")
sm.createQuestWithQRValue(17011, "C=10;S=0")
sm.warp(865000101)
