# id 17518 ([Tynerum] A Brush with Hilla), field 863100104
sm.setSpeakerID(9390100) # Hilla
sm.sendNext("So, you came.")
sm.setParam(17)
sm.sendSay("...Hilla?")
sm.setParam(0)
sm.sendSay("I told you to go away, but you wouldn't listen. ")
sm.setParam(17)
sm.sendSay("YOU're the one behind all this nonsense!")
sm.setParam(0)
sm.sendSay("What of it?")
sm.setParam(17)
sm.sendSay("What are you scheming?!")
sm.setParam(0)
sm.sendSay("Scheming? I'm not scheming. I'm working on getting what I want.")
sm.setParam(17)
sm.sendSay("I'll stop whatever horrible ritual you've got cooked up!")
sm.setParam(0)
res = sm.sendAskYesNo("You really don't have to beg me to destroy you. I'll happily oblige.")
sm.sendNext("Are you ready to join my undead army? It'll only take a minute.")
sm.startQuest(parentID)
sm.warp(863100105)
