# id 17661 ([Commerci Republic] Unstable Future), field 865030000
sm.setSpeakerID(9390236) # Leon Daniella
sm.setParam(2)
sm.sendNext("Calm down. We can catch up to them.")
sm.setParam(0)
sm.sendSay("I just get so excited in my brain. I'm all fired up! I've got the vigor in my heart.")
res = sm.sendAskYesNo("But we need to think about what we're going to do and use some strategies.")
sm.startQuest(parentID)
sm.setParam(32)
sm.setColor(1)
sm.sendNext("We have two missions, sidekick. First up, clear our names, because people think we're bad, and we are NOT bad. Second, rescue Claire and make her my girlfriend.")
sm.sendSay("I'm sorry to say it, #h0#, but Claire comes first. She's way prettier than you. Besides, chicks dig outlaws.")
sm.sendSay("You can work on that other thing, but I'm going after her right now. Don't try to follow me!")
sm.setParam(56)
sm.sendSay("Um, I actually think we could just do both things at the same time.")
sm.setParam(32)
sm.sendSay("What?! That's crazy. Claire doesn't know anything about assassinating guys. She's too nice to know assassins.")
sm.setParam(56)
sm.sendSay("The guys we saw after Claire disappeared were the same guys I saw when the envoy was attacked. If we can catch them, we can clear our names.")
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(16689)
sm.startQuest(16689)
