# id 17656 ([Commerci Republic] Dances with Wolves 1), field 865030000
sm.setSpeakerID(9390249) # Robed Lady
sm.sendNext("My identity will not help you two get out of your current situation.")
sm.setParam(2)
sm.sendSay("I like to know who my allies and my enemies are.")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("Hey, what if I pay you double? I mean, seriously, my dad is LOADED.")
sm.setParam(0)
sm.sendSay("Oh... Really? How much can you pay me right now?")
sm.setParam(4)
sm.sendSay("Uh, maybe just like half now, half later? I've gotta save SOME cash... what if I find a house I need to buy? ")
sm.setParam(0)
sm.sendSay("A fair deal, my name is...")
sm.setParam(2)
res = sm.sendAskYesNo("Wait. We're in danger! Lupos!")
sm.startQuest(parentID)
sm.setParam(4)
sm.sendNext("Aww, man, I HATE Lupos! Don't let them bite this beautiful lady!")
sm.startQuest(parentID)
sm.progressMessageFont(3, 20, 20, 0, "EXP and mesos greatly reduced if hunting monsters beyond your level range.")
sm.startQuest(16689)
sm.startQuest(parentID)
sm.startQuest(16689)
