# id 17674 ([Commerci Republic] Mutually Beneficial), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.setParam(32)
sm.setColor(1)
sm.sendNext("You've been embroiled in our politics against your will, but I have one more favor to ask you.")
sm.setParam(56)
sm.sendSay("Is it about Leon? I don't think I can fix him.")
sm.setParam(32)
sm.sendSay("No, no. Leon is... he will grow into himself. I have a more subtle task for you. Will you hear me out?")
sm.setParam(56)
sm.sendSay("Sure, what can I do?")
sm.setParam(32)
res = sm.sendAskYesNo("You're quite kind, haha. Could you deliver this letter to Empress Cygnus.")
sm.startQuest(parentID)
sm.setParam(56)
sm.sendNext("Empress Cygnus? What... is it?")
sm.setParam(32)
sm.sendSay("It's a peace treaty, though I assure the terms are fair and equitable, haha. I would like to propose an alliance between our peoples.")
sm.setParam(56)
sm.sendSay("Whoa... Of course! I'll read it to her a thousand times if I need to!")
sm.setParam(32)
sm.sendSay("You have been a strange and welcome visitor, #h0#. I hope to see you again soon. Leon will be waiting for you at the harbor.")
sm.setParam(56)
sm.sendSay("Thank you, sir. I'll come back and visit soon!")
sm.setParam(32)
sm.sendSay("See that you do.")
