# id 17645 ([Commerci Republic] Close Up with Captain Blood), field 865010001
sm.setSpeakerID(9390209) # Captain Blood
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
sm.sendNext("These pirates are way tougher than those ones before! Maybe they'll come work for my dad...")
sm.setParam(0)
sm.sendSay("Not a chance, scallywag!")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("Captain Blood! I hate that guy!")
sm.setParam(0)
sm.sendSay("Ye did well to make it this far, but the pleasure cruise ends here! Yar har har!")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
res = sm.sendAskYesNo("We'll show you what we've got! #h0#, ready?")
sm.startQuest(parentID)
sm.setParam(5)
sm.sendNext("Let's wipe their butts! I mean...GO!")
sm.sendSay("Let's do some fightinnnnnnnng!")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
