# id 17675 ([Commerci Republic] His Circumstances), field 865000000
sm.setSpeakerID(9390256) # Leon Daniella
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9390240) # Claire Tremier
sm.sendNext("...I'll be going.")
sm.hideNpcByTemplateIdhi(9390237, True, True)
sm.setParam(56)
sm.sendSay("Hey, Leon.")
sm.setParam(32)
sm.sendSay("Hm? Oh, hey, sidekick. I heard from dad. When you're ready...")
sm.setParam(56)
sm.sendSay("Wait... What did I just see? What's going on between you two?")
sm.setParam(32)
sm.sendSay("Hm? Oh, you mean Miss Tremier?")
sm.setParam(56)
sm.sendSay("Wait, wait, wait. What happened to all the girlfriend talk?! What's going on?!")
sm.setParam(32)
sm.sendSay("We, uh, we just decided to, like, get to know each other. She says I have to be more gentlemanly.")
sm.setParam(56)
sm.sendSay("Wait, does she actually LIKE you? Like, like-like?! Go get her, man!")
sm.setParam(32)
sm.sendSay("She and I both have a lot of stuff we want to do in life before we bring a new person into our families. We're gonna take it slow...")
sm.setParam(56)
sm.sendSay("I... wasn't talking about marriage... But whatever works.")
sm.setParam(32)
res = sm.sendAskYesNo("Hey, I've still got to round up my crew before we set sail. Can you do one last thing for me?")
sm.startQuest(parentID)
sm.setParam(56)
sm.sendNext("A favor? What is it?")
sm.setParam(32)
sm.sendSay("W-well. I wrote a letter for Miss Tremier, but we got so caught up saying goodbye that I forgot to give it to her. Could you take it to her before she leaves for the Heaven Empire?")
sm.setParam(56)
sm.sendSay("Are you sure you don't want to give it to her yourself? You don't know when you'll see her again.")
sm.setParam(32)
sm.sendSay("Oh, man, you think she'd give me a kiss? No, Leon, no! That's not what a gentleman would do. I think. Ohh, I miss her eyes...")
sm.setParam(56)
sm.sendSay("(I think I'm going to vomit...)")
sm.setParam(32)
sm.sendSay("It's better if you do it. I'll become a better man and win her the right way. It's more romance novely that way, right? Haha!")
sm.setParam(56)
sm.sendSay("Uggghhhh fine. Just leave me out of the next round.")
