# id 17679 ([Commerci Republic] Red Tide), field 865010011
sm.setSpeakerID(9390246) # Captain Blood
sm.setParam(56)
sm.setColor(1)
sm.sendNext("Your pirating days are over!")
sm.setParam(32)
sm.sendSay("Hahaha! Ye've walked into th' belly a' th' beast and ye don't even know it! ")
sm.setParam(56)
sm.sendSay("That's what you think, scurvy-face! Thanks for bringing your guys along so I can mop the floor with them all at once. ")
sm.setParam(32)
sm.sendSay("Puff up ye chest, wee seagull. I'll gift ye a right whippin' ye'll never forget!")
sm.setParam(56)
res = sm.sendAskYesNo("(This guy... I'm going to swab his decks!)")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.progressMessageFont(3, 20, 20, 0, "EXP and mesos greatly reduced if hunting monsters beyond your level range.")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.closeUI(1128)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.createQuestWithQRValue(18418, "B=33273")
