# id 17673 ([Commerci Republic] Undeniable Proof), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.sendNext("I knew you were innocent. I'm glad that we could prove it.")
sm.setParam(2)
sm.sendSay("I'm glad we could work everything out too. I felt bad that Leon got swept up in this.")
sm.setParam(0)
sm.sendSay("The course of a man's life is decided by their behavior in moments of peril. This will be good for my son. I only hope he can forgive my betrayal as a father...")
sm.setParam(2)
sm.sendSay("You're the leader of the Republic. I think he'll understand that you had to do what was best for the nation.")
sm.setParam(0)
res = sm.sendAskYesNo("I hope. Can you tell me more about what happened with the Heaven Empire envoy?")
sm.startQuest(parentID)
sm.setParam(2)
sm.sendNext("Sure. It was actually Claire who rescued us before we were arrested.")
sm.setParam(0)
sm.sendSay("She used magic to save you?")
sm.setParam(2)
sm.sendSay("Yes, she's pretty good at it, actually. We were hiding out in the forest on the outskirts of San Commerci, but Claire was abducted.")
sm.setParam(0)
sm.sendSay("And the abductors were assassins from the Heaven Empire?")
sm.setParam(2)
sm.sendSay("I'm not 100% sure, but Zion was ordering them around. He said they were the ones who came up with the plot.")
sm.setParam(0)
sm.sendSay("Hmmm... But for all we know, they could be an independent group, or mercenaries. And with Zion gone, there is no way to find out.")
