# id 17657 ([Commerci Republic] Who's That Lady?), field 865030000
sm.setSpeakerID(9390205) # Claire Tremier
sm.setParam(32)
sm.setColor(1)
sm.sendNext("There, are you happy now?")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("Heeeeey! ")
sm.setParam(56)
sm.sendSay("Leon? Did you just black out? Lady, I have no idea who you are.")
sm.setParam(32)
sm.sendSay("You STILL can't just trust me? After everything I've done?")
sm.sendSay("My name is #bClaire Tremier#k. I am the heiress to the Tremier Merchant Union.")
sm.setParam(56)
sm.sendSay("Tremier? That little weasel that called me a murderer?!")
sm.setParam(32)
sm.sendSay("That little WEASEL is my father.")
sm.setParam(56)
sm.sendSay("What is your game here?")
sm.setParam(32)
sm.sendSay("My game? I don't like your tone...")
sm.setParam(56)
sm.sendSay("Well, what are you going to do about it?")
sm.setParam(36)
sm.sendSay("Whoa, #h0#, relax! Miss Tremier obviously has some good reasons for what she's doing. Let's hear her out, and listen to her pretty voice.")
sm.setParam(56)
sm.sendSay("Fine, but this had better be good.")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33288")
