# id 17642 ([Commerci Republic] A Fickle Man), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.setParam(56)
sm.setColor(1)
sm.sendNext("Ah... I'm sorry. I was careless. I should've told you first.")
sm.setParam(32)
sm.sendSay("Yes, that's right! We're friends but I AM the captain of this ship. All cute girls have to go through me!")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390204) # Robed Lady
sm.sendSay("Oh my, what kind of ship is this? It's quite tasteless. Are we running low on cash?")
sm.setParam(32)
sm.sendSay("!!!!!!!!!!!!!!!!!!")
sm.setParam(56)
sm.sendSay("Leon, you're absolutely right. I should have given it a second thought. I'll tell her nicely and get her off the ship right away.")
sm.sendSay("Excuse me...")
sm.setParam(36)
sm.sendSay("Hm? What is it? I hope you don't expect me to do any swabbing.")
sm.setParam(56)
sm.sendSay("No, it's not that. I'm, um, well... ")
sm.setParam(32)
sm.sendSay("After the big fight today, would you like to go out with me?")
sm.setParam(36)
sm.sendSay("...Wha... Ha. Ha ha. Hahahahaha! Oh...oh my goodness... That's rich. Ahem. I tell you what...we'll talk again after the fight. IF you survive. Now, if you're done talking, I'm going to have a look around.")
sm.setParam(56)
sm.sendSay("Leon, what are you doing?")
sm.setParam(32)
sm.sendSay("Ahh, jealous? Yeah, she totally digs me. Can't just let a lady go by herself, y'know. It's a big, bad world out there.")
sm.setParam(56)
sm.sendSay("(Weirdo. I just can't figure him out.)")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33268")
