# id 17643 ([Commerci Republic] Yar! Pirates!), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.sendNext("It's quiet...TOO calm. I hope the pirates are saying their prayers and kissing their...something...")
sm.setParam(2)
sm.sendSay("Who knows. It's only been a couple days, so let's wait it out.")
sm.setParam(0)
res = sm.sendAskYesNo("Hm... Sure. But are you ready to take on the pirates at any minute?")
sm.startQuest(parentID)
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390217) # Tepes
sm.sendNext("Pirates! Pirates! Don't let them near!")
sm.setParam(1)
sm.sendSay("They're here! Oh BOY!")
sm.setParam(5)
sm.sendSay("The pirates are boarding the ship! Tell them to wipe their feet first!")
sm.setParam(1)
sm.sendSay("Let's go, #h0#! FOR THE AWESOME!")
sm.startQuest(parentID)
sm.progressMessageFont(3, 20, 20, 0, "EXP and mesos greatly reduced if hunting monsters beyond your level range.")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
