# id 17667 ([Commerci Republic] Plans from Heaven), field 865030111
sm.setSpeakerID(9390238) # Zion
sm.setParam(32)
sm.setColor(1)
sm.sendNext("W-we knew that Gilberto would reject our peace treaty.")
sm.setParam(56)
sm.sendSay("Why did you even propose them if you knew they'd be rejected?")
sm.setParam(32)
sm.sendSay("M-my assassins believed that... that linking the Prime Minister of Commerci to the assassination of a peace envoy would be disastrous with the other nations...")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("And then they'd all turn their backs on us! You were trying to break us down and isolate us! ")
sm.setParam(32)
sm.sendSay("T-that was His Grace's plan, yes.")
sm.setParam(56)
sm.sendSay("We're going to march back to town, and you're going to tell everyone what you just told me.")
sm.setParam(32)
sm.sendSay("Y-yes... but you must offer me asylum.")
sm.setParam(36)
sm.sendSay("AND, we get to have your stuff.")
sm.setParam(32)
sm.sendSay("T-that's...!")
sm.setParam(36)
sm.sendSay("What? Mine? You're right. It IS mine now. Unless you want mr. mustache to meet the tweezers... ")
sm.setParam(32)
sm.sendSay("N-no. I was going to say... that's m-my gift... to you!")
sm.setParam(36)
sm.sendSay("Oh, really? Thanks man, that's super nice. I kinda feel bad now.")
sm.sendSay("Hey #h0#, you should use this.")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33299")
