# id 17681 ([Commerci Republic] Final Report), field 130000000
sm.setSpeakerID(1101000) # Cygnus
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1540450) # Cygnus
sm.sendNext("#h0#, I'm glad to see you are well.")
sm.setParam(56)
sm.sendSay("Heya, Empress? I just got back.")
sm.setParam(36)
sm.sendSay("I was beginning to get worried. You were out of touch for a while.")
sm.setParam(56)
sm.sendSay("Yeah, I guess I got stuck in a sticky situation.")
sm.setParam(36)
sm.sendSay("Oh my! I trust that everything went well in Commerci?")
sm.setParam(56)
sm.sendSay("Eventually, yes. It was a lot like the rest of Maple World, fresh air, beautiful sights, and good people... Punctuated by occasional bouts of insanity and evil. ")
sm.setParam(36)
sm.sendSay("It sounds like a very splendid place. I look forward to visiting someday.")
sm.setParam(56)
sm.sendSay("Yeah, let's put a hold on that. I DO have a letter for you though. It's from the Prime Minister of the San Commerci, their big capital.")
sm.setParam(36)
sm.sendSay("#face0#For me?")
sm.setParam(56)
sm.sendSay("I didn't read it, but I think it's a peace treaty.")
sm.setParam(36)
sm.sendSay("If it is, you have done a great thing for Maple World. Thank you.")
sm.setParam(56)
sm.sendSay("Sure thing!")
sm.setParam(36)
sm.sendSay("I thank you for proving I was right to have faith in you, #h0#. Your friendship means a great deal to me.")
sm.sendSay("#face2#You look weary. You should go get some rest. I could use a nap myself.")
sm.sendSay("Oh, I had something prepared for you, a small token of my thanks. I left it with Neinheart.")
sm.startQuest(parentID)
