# id 17658 ([Commerci Republic] Claire's Story), field 865030000
sm.setSpeakerID(9390205) # Claire Tremier
sm.setParam(32)
sm.setColor(1)
sm.sendNext("My father will do anything anything to protect me... ANYTHING.  And that is the problem. He's attempting to marry me to the ruling family of the Heaven Empire. ")
sm.setParam(36)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("NOT COOL!")
sm.setParam(32)
sm.sendSay("I have been studying with the Heaven Empire's royal family for some time now, but I hate it there. They are a cruel, and backwards society, and I want to marry for love. And...")
sm.setParam(56)
sm.sendSay("And?")
sm.setParam(32)
sm.sendSay("And... And... I want to be a magician!")
sm.setParam(56)
sm.sendSay("A magician? Seriously?")
sm.setParam(32)
sm.sendSay("Oh, I know it's a foolish reason to give up an empire, but it is the only thing that makes me happy. I've been studying magic in secret since I was six!")
sm.setParam(56)
sm.sendSay("Hence the awesome magic show on the ship...")
sm.setParam(32)
sm.sendSay("Yes, but there's a limit to how much I can learn on my own. I've decided to study abroad, but I can't tell father. But... I don't know how to pay for it... So... ")
sm.setParam(56)
sm.sendSay("You're playing bodyguard for us to make the money... I get it.")
sm.setParam(32)
sm.sendSay("Yes, I suppose I am. ")
sm.setParam(56)
sm.sendSay("So, any idea why your dad wants to make me out as a murderer?")
sm.setParam(32)
sm.sendSay("No. That was... unexpected. I would have to assume it has something to do with his communications with the Heaven Empire though.")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33289")
