# id 17676 ([Commerci Republic] Her Circumstances), field 865000000
sm.setSpeakerID(9390256) # Leon Daniella
sm.setParam(32)
sm.setColor(1)
sm.sendNext("Hey, you're back! Was she swooning over me? No, Leon, that's not gentlemanly. But was she?")
sm.setParam(56)
sm.sendSay("I gave her your letter.")
sm.setParam(32)
sm.sendSay("Did she read it? Did she look happy? Was she touching her hair? You can tell a girl likes you if they touch their hair! ")
sm.setParam(56)
sm.sendSay("(Leon, you are so clueless!) Oh... yeah... totally... all kinds of hair touching. And she asked me to give this to you.")
sm.setParam(32)
sm.sendSay("YES! What is it?")
sm.setParam(56)
sm.sendSay("Man, I don't know! You open it.")
sm.setParam(32)
sm.sendSay("Let... me... see... What is this?")
sm.setParam(56)
sm.sendSay("Looks like some kind of charm. ")
sm.setParam(32)
sm.sendSay("It must be a good luck, no harm charm! I will never let this leave my person. Ever.")
sm.setParam(56)
sm.sendSay("Maybe just wear it like half of the time... (I really hope that thing is not cursed.)")
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(18418, "B=33309")
