# id 17676 ([Commerci Republic] Her Circumstances), field 865000000
sm.setSpeakerID(9390240) # Claire Tremier
sm.setParam(56)
sm.setColor(1)
sm.sendNext("Hey, uh, when are you leaving?")
sm.setParam(32)
sm.sendSay("As soon as my father is ready.")
sm.setParam(56)
sm.sendSay("He's going too?")
sm.setParam(32)
sm.sendSay("Yes, I believe this whole business with the kidnappers has put him on edge. He's barely let me go to the bathroom by myself, haha.")
sm.setParam(56)
sm.sendSay("But you're not going to give up, right? On being a magician?")
sm.setParam(32)
sm.sendSay("Of course not! That's ridiculous. I will continue to collect money... and knowledge, so long as I can.")
sm.setParam(56)
sm.sendSay("(She is totally going to run away again.)")
sm.sendSay("Is there anything you want me to tell Leon? Just in case you don't see him again?")
sm.setParam(32)
sm.sendSay("Leon? No. I said my goodbyes. ")
sm.setParam(56)
sm.sendSay("You're not going to miss him?! I thought you two were like...")
sm.setParam(32)
sm.sendSay("Why would I miss him?")
sm.setParam(56)
sm.sendSay("Right, right... Why indeed? (Leon, you poor thing!)")
sm.setParam(32)
res = sm.sendAskYesNo("Actually, could you give him this?")
sm.startQuest(parentID)
sm.setParam(56)
sm.sendNext("Sure, no problem. I'll make sure he gets it. ")
sm.setParam(32)
sm.sendSay("It's... it's a new spell I'm testing out. I hope it works for him.")
