# id 17677 ([Commerci Republic] Back to Lith Harbor), field 104000000
sm.setSpeakerID(9390200) # Parbell
sm.setParam(2)
sm.sendNext("Whew! It's feels like ages since I've been somewhere familiar.")
sm.setParam(0)
sm.sendSay("Where yuh been?! I thought y'uns was fish food.")
sm.setParam(2)
sm.sendSay("Oh... SERIOUSLY?! Parbell? You're alive?! What are you doing here?")
sm.setParam(0)
sm.sendSay("Hah! Do I looks like a feller what would get done in by such a bitty little storm? Ol' Parbell's seen plenty worse than that on the high seas!")
sm.sendSay("About before... I know it weren't the safe n' cozy voyage I promised, so consider yerself off the hook fer that reward yuh promised me. ")
sm.setParam(2)
sm.sendSay("Were you waiting here for me? How did you know I'd be back?")
sm.setParam(0)
sm.sendSay("Ain't no way a lil' bitty storm like that would leave yuh swimmin' with the fishes. Not if yuh got half the gumption of Ol' Parbell! I's afraid I didn't have much time to look for y'un what with my boat in pieces. But I heard yuh were safe from Mayor Berry, so I went ahead n' booked passage back here.")
sm.setParam(2)
sm.sendSay("(Ugh... You're going to have to complain about this to Neinheart when you return to Ereve.)")
sm.setParam(0)
res = sm.sendAskAccept("I figures yer gonna want a lift back to see that Empress Syggus o' yers. It's only fair I take y'un there fer free in mah new boats. \r\n#b(You will be moved to Ereve if you accept.)#k")
sm.completeQuestNoCheck(parentID)
sm.setParam(1)
sm.sendNext("The weather's pretty fair today, I reckon we won't run afoul o' no trouble.")
sm.createQuestWithQRValue(18418, "B=33310")
sm.warp(130000000)
