# id 17644 ([Commerci Republic] Arg! Chase!), field 865010001
sm.setSpeakerID(9390244) # Leon Daniella
sm.setParam(2)
sm.sendNext("Those pirates really know their way around the ocean...")
sm.setParam(0)
sm.sendSay("Of course, they move around a lot more than merchant ships.")
sm.setParam(2)
sm.sendSay("Captain Blood's ship is in sight!")
sm.setParam(0)
res = sm.sendAskYesNo("Captain Blood is here. Ready?")
sm.startQuest(parentID)
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390217) # Tepes
sm.sendNext("Oh, no! Pirates from Captain Blood's ship are boarding! And they didn't ask permission first!")
sm.setParam(1)
sm.sendSay("All right, let's do this!")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
