# id 17653 ([Commerci Republic] Don't Even Ask), field 865000002
sm.setSpeakerID(9390203) # Gilberto Daniella
sm.sendNext("Did you deliver the letter?")
sm.setParam(2)
sm.sendSay("Yes, but... ")
sm.setParam(0)
sm.sendSay("He didn't take it well?")
sm.setParam(2)
sm.sendSay("I don't know if that letter was supposed to be funny, but he was laughing a lot. He... he said that you made the mess, you have to clean it...")
sm.setParam(0)
sm.sendSay("What? That fool! This isn't some petty grudge. This threatens our entire nation! ")
sm.setParam(2)
sm.sendSay("He said he was too busy managing his union to help.")
sm.setParam(0)
sm.sendSay("That... that vindictive child! Thinking of his coin purse when our very freedom hangs under a knife! I knew he wanted my job, but I never though he would sink to this.")
sm.sendSay("I'm sorry, I must be alone. Go get some rest.")
sm.completeQuestNoCheck(17740)
sm.createQuestWithQRValue(18418, "B=33283")
sm.createQuestWithQRValue(18418, "B=33284")
