# id 17641 ([Commerci Republic] Robed Adventures), field 865000000
sm.setSpeakerID(9390204) # Robed Lady
sm.setParam(32)
sm.setColor(1)
sm.sendNext("What are you doing here?")
sm.setParam(56)
sm.sendSay("..............")
sm.setParam(32)
sm.sendSay("Ah, you said something about eliminating pirates, right?")
sm.setParam(56)
sm.sendSay("..............")
sm.setParam(32)
sm.sendSay("Are you sure you can do it? You're crew doesn't exactly look the fittest.")
sm.setParam(56)
sm.sendSay("...Fine, you can come.")
sm.setParam(32)
sm.sendSay("What? W-whatever do you mean?")
sm.setParam(56)
sm.sendSay("Just say it, you want to go on the voyage with us.")
sm.setParam(32)
sm.sendSay("...Well, I'm a VERY busy woman, but if you REALLY need my help, I'll go.")
sm.setParam(56)
sm.sendSay("...Strange lady. I hope she doesn't cause trouble. I'll just talk to Leon later.")
sm.completeQuestNoCheck(parentID)
sm.warp(865010001)
