# id 17665 ([Commerci Republic] Zero Patience), field 865030111
sm.setSpeakerID(9390236) # Leon Daniella
sm.setParam(33)
sm.setColor(1)
sm.sendNext("(Pssst, #h0#, can you hear them?)")
sm.setParam(57)
sm.sendSay("(Nope.)")
sm.setParam(33)
sm.sendSay("(Let's just go in there and save Claire.)")
sm.setParam(57)
sm.sendSay("(Wait.)")
sm.setParam(33)
sm.sendSay("(She's in danger! That guy is super bullying her!)")
sm.setParam(57)
sm.sendSay("(Don't move! I think they know each other...)")
sm.setParam(33)
sm.sendSay("(I have to save her... This is what I was born to do, sidekick!)")
sm.setParam(57)
sm.sendSay("(H-hey!!)")
sm.startQuest(parentID)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9390207) # Zion
sm.sendSay("Who's there?")
sm.setParam(33)
sm.sendSay("Remember me, Zion?!")
sm.setParam(37)
sm.sendSay("Ah, the Prime Minister's deckhand. What brings you here?")
sm.setParam(33)
sm.sendSay("Shut up and get away from my Claire!")
sm.setParam(37)
sm.sendSay("Oh, do you know my darling Claire-bear? I am... an acquaintance like yourself, Mr. Daniella. Though I hardly think you meet her standards.")
sm.setParam(57)
sm.sendSay("Don't listen to his lies, Leon. Why did you fake your own death, goldilocks? What are you plotting?!")
sm.setParam(37)
sm.sendPrev("Ah, you're the... traveler. I apologize for getting you involved, but I'm afraid you can't be allowed to know what you know.")
