# id 17637 ([Commerci Republic] Deus Ex You), field 865000002
sm.setSpeakerID(9390262) # Leon Daniella
sm.sendNext("C'mon, Dad! Just give the word and I'll tear Captain Blood up. No sweat!")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390203) # Gilberto Daniella
sm.sendSay("Hm? You? But you JUST came back from battling the Delfinos.")
sm.setParam(2)
sm.sendSay("(Yeah, that's right.)")
sm.setParam(0)
sm.sendSay("But...but...I really wanna fight pirates!")
sm.setParam(4)
sm.sendSay("Hm. A noble cause, to be sure. However, I fear that Captain Blood may be just a touch out of your league.")
sm.setParam(2)
sm.sendSay("(That's right. Leon needs more training...)")
sm.setParam(0)
sm.sendSay("B-but... What if I go with #h0#? I can watch #h0#'s back, and jump in to do some world-class swashbuckling! ...Supervised, of course.")
sm.setParam(2)
sm.sendSay("(Wait, what? Why me...)")
sm.setParam(4)
sm.sendSay("You disappoint me. I thought you were beyond begging others for help. Do I need to suspend your allowance again?")
sm.setParam(2)
sm.sendSay("(Ugh, not this again... I'd better get this over with.)")
sm.sendSay("Prime Minister, I'll go with Leon.")
sm.setParam(4)
sm.sendSay("Don't be ridiculous. You've already done more than enough for us.")
sm.setParam(2)
sm.sendSay("I've done enough as allies. This time I want to help as a...friend...of Leon's.")
sm.setParam(4)
sm.sendSay("Hm... When you say it like that, I'm inclined to...")
sm.startQuest(parentID)
