# id 17681 ([Commerci Republic] Final Report), field 130000000
sm.setSpeakerID(1101002) # Neinheart
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1540451) # Neinheart
sm.sendNext("Ah, I see you're back. You look like you've had a rough time of it.")
sm.setParam(56)
sm.sendSay("Yeah, thanks to a certain somebody.")
sm.setParam(36)
sm.sendSay("Oh? Well, I hope you dealt with that person appropriately.")
sm.setParam(56)
sm.sendSay("Uh... Anyway, remember how you said you'd arranged my passage to Commerci? Turns out nobody ever paid Parbell. Also, the boat sinking halfway there wasn't exactly what I signed up for.")
sm.setParam(36)
sm.sendSay("Huh? I didn't give you Parbell's ruby? Strange... I rarely forget things like that. As for your having to get a little wet, I deeply apologize. The next time your Empress wants to call for your help, I'll be sure to remind her you only perform duties that are convenient.")
sm.setParam(56)
sm.sendSay("#b(...I'm detecting serious notes of sarcasm in this apology.)#k")
sm.setParam(36)
sm.sendSay("In any case, you've performed your mission admirably, as always. This is precisely why I push you around.")
sm.sendSay("Oh my, that was a slip of the tongue. What I meant was 'this is why I push you to greatness.' Don't misunderstand.")
sm.setParam(56)
sm.sendSay("#b(...I forgot to ask the Empress to give Neinheart a scolding...)#k")
sm.setParam(36)
sm.sendSay("It may not be enough but be reward enough for your service, but this is a gift from the Empress for all your hard work. \r\n\r\n#b#i2049702:##t2049702##k\r\n#b#i2431935:##t2431935##k\r\n#b#i2431936:##t2431936##k")
sm.sendSay("Oh! And one more thing. This was attached to the letter you brought from Commerci. You should take good care of it.\r\n\r\n#b#i1142981:##t1142981##k")
sm.sendPrev("You don't have enough space in your inventory. Please empty at least 2 slots in Equip tab, and 3 slots in Use tab.")
