# id 17647 ([Commerci Republic] The Fall of Captain Blood), field 865010001
sm.setSpeakerID(9390243) # Robed Lady
sm.sendNext("Where are the pirates?")
sm.setParam(2)
sm.sendSay("Pirate? Captain Blood!")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9390235) # Leon Daniella
sm.sendSay("Oh yeah! I was staring at the boat on the horizon like, 'who's flying that pirate flag?' I totally forgot about Captain Blood. Haha!")
sm.setParam(0)
sm.sendSay("He's getting away!")
sm.setParam(4)
sm.sendSay("He must have a really fast ship. My dad's sailboat is that fast. Should we go get my dad's sailboat?")
sm.setParam(2)
sm.sendSay("There's no time. He's gone for now.")
sm.setParam(4)
sm.sendSay("Awww, we almost had him! I want him! I want to get him!")
sm.setParam(0)
res = sm.sendAskYesNo("I suppose I will have to do this.")
sm.startQuest(parentID)
sm.setParam(56)
sm.setColor(1)
sm.sendNext("What are you gonna do? Swim out there and catch him? Are you hiding a jet ski under those robes?")
sm.setParam(32)
sm.sendSay("Don't be so naive... and what is a jet ski?")
sm.setParam(56)
sm.sendSay("Stop calling me naive!")
sm.setParam(32)
sm.sendSay("Shall I handle this for you? There will be a fee.")
sm.setParam(36)
sm.sendSay("You can catch the pirate?! That's awesome! My dad's got lots of money.")
