# 1800 - [Evolution System] Suspicious Movement on the path
sm.setSpeakerID(9400115)
sm.sendNext("Thank you for coming. I'll explain more about the underground mine situation, but first... You know who this is?")
sm.setPlayerAsSpeaker()
sm.sendNext("I know that face!")
sm.setSpeakerID(9400115)
sm.sendNext("You should. She is the founder of the Black Wings and the commander of the Black Mage's Army...")
sm.setPlayerAsSpeaker()
sm.sendNext("Orchid.")
sm.setSpeakerID(9400115)
sm.sendNext("She is the reason our city was taken. She is the one who masterminded the theft of the Seal Stones, attacked Mercedes... That such a small girl could have caused so much havoc...")
sm.sendNext("She's been quiet for a while now, so I knew there must be trouble brewing. The Black Wings appear to have had a coup.")
sm.sendNext("We've pieced together some information suggesting that Orchid was ousted from her position. We're not sure why, but there has been a huge shake-up in the command structure of the Black Wings.")
sm.sendNext("It all seems to have begun when Orchid was betrayed by the scientist...")
sm.startQuest(parentID)
sm.warpInstanceIn(957020001, 0)