sm.setSpeakerID(1102101)
sm.removeEscapeButton()
sm.sendNext("A knight's gotta be strong, right? I mean, you guys have some really tough missions. So, you ready for your next training session?")
sm.completeQuest(parentID)
sm.warpInstanceIn(130030103, 0)