sm.levelUntil(10)
sm.setJob(2200)
sm.addSP(5, True)
sm.chatScript("You learned the Back to Nature skill.")
sm.sendSayImage("UI/tutorial/evan/14/0")
sm.systemMessage("A baby dragon has hatched from the egg in the incubator.")
sm.systemMessage("Obtained 5 Skill Points to use for leveling up.")
sm.systemMessage("It looks like the baby dragon has something to say. Click to talk to it!")
sm.completeQuestNoCheck(22130)
sm.giveSkill(20011293)