# 25511 - [Job Adv] (Lv.60)   The Power of Crystals
sm.removeEscapeButton()
sm.setSpeakerID(1032209)
sm.sendNext("Luminous, I've gathered the power of all the Auguries")
sm.sendNext("I'll use this power to melt the Dark right out of you.")
sm.sendNext("Remember, it's up to you to conquer your darkness. The Auguries will only help so much.")
sm.setPlayerAsSpeaker()
sm.sendNext("Have faith. I won't let the Dark take me again!")
sm.setSpeakerID(1032209)
sm.sendNext("Focus on this saying: #b<The light shines brightest in the deepest dark.> #kOkay, here we go!")
sm.setPlayerAsSpeaker()
sm.sendNext("AAAUGH!")
sm.setSpeakerID(1032209)
sm.sendNext("You did it! That wasn't so bad, was it?")
sm.setPlayerAsSpeaker()
sm.sendNext("(What is this new energy that courses through my body? It's as though the Light and Dark merged into one...)")
sm.setSpeakerID(1032209)
sm.sendNext("You should rest up for now. We can talk later.")
sm.setJob(2711)
sm.startQuest(parentID)
sm.completeQuest(parentID)
sm.addSP(4)

