# id 25837 (Challenge: Recharge!), field 400000000
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3000018) # Eskalade
sm.sendNext("It's time to Recharge in an actual fight!")
sm.setParam(16)
sm.sendSay("Whoa, I don't wanna fight yet!")
sm.setParam(4)
sm.sendNext("It's time to Recharge in an actual fight!")
sm.setParam(16)
sm.sendSay("Whoa, I don't wanna fight yet!")
sm.setParam(4)
sm.sendSay("You'll never get anywhere if you just talk about stuff! Take me out and beat up some stuff!")
sm.setParam(16)
sm.sendSay("How am I supposed to learn anything if you're just gonna be a jerk?")
sm.setParam(4)
sm.sendSay("Just walk out there, find a monster, and use your skills! #bRecharge successfully 5 times#k. It won't take you long!")
sm.setParam(17)
sm.sendSay("Ugh, I don't wanna get all sweaty, but I guess I have to.")
sm.startQuest(parentID)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/07/16/06/15")
