# id 25829 (Skill Starter), field 400000000
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3000018) # Eskalade
sm.sendNext("You're probably scared and confused by your awesome new powers, right? Well, I'll teach you a little something.")
sm.setParam(16)
sm.sendSay("Could you make it less condescending?")
sm.setParam(4)
sm.sendSay("This is the only way I know how to teach! Now take a look at your Beginner Skills, little brainless one!")
sm.sendSay("The first one is called #i3800342# Day Dreamer. You can use this skill to escape to a lovely little hideout that I #especially prepared for the two of us#n.")
sm.setParam(16)
sm.sendSay("I... don't know if I like the sound of that. Should I be worried?")
sm.setParam(4)
sm.sendSay("The next skill is #i3800344# Dress-Up! Boy, do I like Dress-Up. It lets you change between boring old #h0# and the magical, firey Angelic Buster! Dress-Up will happen automatically if you try to use other skills before you transform, so don't be surprised!")
sm.setParam(16)
sm.sendSay("...")
sm.setParam(4)
sm.sendSay("That's kind of all I feel like explaining. I can see it's not really sinking in anyway. Just... try that other stuff out on your own.")
sm.completeQuestNoCheck(parentID)
