# id 25836 (Eskalade Power), field 400000000
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3000018) # Eskalade
sm.sendNext("Wait, actually, there's one more thing that you must know. One last... obligation.")
sm.setParam(16)
sm.sendSay("...What is it?")
sm.setParam(4)
sm.sendSay("My power is nearly unlimited, or so it will seem to you. It requires some recharging, but I'll never require petty things like mana or fury from you.")
sm.setParam(16)
sm.sendSay("Are you boasting about yourself?")
sm.setParam(4)
sm.sendSay("What?! No! No, I... Of course not. I need to tell you what I will require...")
sm.setParam(16)
sm.sendSay("Spit it out!")
sm.setParam(4)
sm.sendSay("I, geez, look, you have a skill called  #e#bSoul Battery#n#k. That thing is like a conduit for my full power. Once it's out, it'll take a while for me to use it again.")
sm.setParam(16)
sm.sendSay("What?! You're just gonna burn out on me?")
sm.setParam(4)
sm.sendSay("Do you realize how often you interrupt others? You should work on that. I'm trying to tell you that you can reuse skills if you perform a successful #e#bRecharge#n#k.")
sm.setParam(16)
sm.sendSay("How do I do that?")
sm.setParam(4)
sm.sendSay("Every attack you use has a chance to Recharge. You need to keep an eye on your attacks to see if it works, then you'll be able to perform another Soul Battery. Got it?")
sm.setParam(16)
sm.sendSay("I'm sorry, I was looking at a butterfly and that was boring.")
sm.setParam(4)
sm.sendSay("Listen to me! Not all of your Attack skills are Soul Battery skills. If you use Recharge skills like #e#bSoul Buster, Pink Pummel, and Heavenly Crash#n#k., you'll be in good shape.")
sm.setParam(16)
sm.sendSay("Yeah, yeah, yeah, just mix it up and I'll be fine. I got it! Gah, you lecture too much. ")
sm.setParam(4)
sm.sendSay("You are dumber than I was hoping you would be...")
sm.setParam(16)
sm.sendSay("What?! What did you just say?")
sm.setParam(4)
sm.sendSay("You are dumber than I was hoping you would be...")
sm.setParam(16)
sm.sendSay("What?! What did you just say?")
sm.setParam(4)
sm.sendSay("Quiet, minion! I just remembered another thing I still need to lecture you about. You have some skills that boost your #e#bAffinity#n#k with me. The stronger our bond is, the faster your Recharge. So you have even more reason to ingratiate yourself to me.")
sm.setParam(5)
sm.sendSay("Okay, NOW I think we're done here. When you inevitably get confused, open the Soul Battery window and use the little button there to get a rundown of the important stuff.")
sm.completeQuestNoCheck(parentID)
