# id 34200 ([Chu Chu] Arcane Blockage), field 993017200
sm.lockInGameUI(True, False)
sm.blind(True, 255, 0, 0, 0, 0)
sm.forcedMove(False, 2)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("That Flying Fish must've run away because #bthat thing#k was blocking the river...")
sm.sendSay("Anyways... What is this huge creature? I'm not going to be able to move forward as long as #bhe#k is in the way.")
sm.sendSay("Uh, excuse me... I'm #b#h0##k... I'm in kind of a hurry and I need to get through. Could you step aside? You do have feet, right?")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003156) # Muto
sm.sendSay("No... Ta-sty... Tasty...")
sm.setParam(57)
sm.sendSay("Huh? Tasty? I don't think you understand how serious this is... The world will be in #rgrave danger#k if I'm not allowed to pass.")
sm.completeQuestNoCheck(34225)
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face1##fs50#TASTIES!")
sm.setParam(57)
sm.sendSay("Ahh! Don't eat me!")
sm.sendSay("Uh... I have these old #bsandwiches#k sitting at the bottom of my bag...")
sm.sendSay("Do you want some?")
sm.setParam(37)
sm.sendSay("Give it... now!")
sm.setParam(57)
sm.sendSay("(I only have two left... I guess I can share.)")
sm.setParam(37)
sm.sendSay("Hawb... Om... Nom...")
sm.completeQuestNoCheck(34223)
sm.sendSay("#face0#YUMMY!")
sm.sendSay("More... More...")
sm.setParam(57)
sm.sendSay("I'm sorry... but that's all I had...")
sm.setParam(37)
sm.sendSay("#face0#Please... More...")
sm.setParam(57)
sm.sendSay("Even if you ask politely... I don't have any more food...")
sm.completeQuestNoCheck(34225)
sm.setParam(37)
sm.sendSay("#face1##fs50#MORE TASTY!")
sm.sendDelay(1000)
sm.setParam(57)
sm.sendNext("Fine! I guess I'll just have to #rforce my way through#k!")
sm.forcedMove(False, 100)
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face2##fs50#Waah! More tasty!")
sm.sendDelay(1000)
sm.spawnNpc(3003167, -370, 20)
sm.showNpcSpecialActionByTemplateId(3003167, "summon", 0)
sm.showNpcSpecialActionByTemplateId(3003167, "appear", 0)
sm.setInnerOverrideSpeakerTemplateID(3003150) # Lyon
sm.sendNext("Have no fear, your hero is here!")
sm.blind(True, 500, 255, 255, 255, 0)
sm.forcedInput(4)
sm.sendDelay(2000)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendNext("Oh my! I #bmessed up again#k and hit this stranger in the head... Gotta work on my landing, heh!")
sm.setInnerOverrideSpeakerTemplateID(3003156) # Muto
sm.sendSay("#face1##fs50#What you give... Give more!")
sm.setInnerOverrideSpeakerTemplateID(3003150) # Lyon
sm.sendSay("Huh? Heya #bMuto#k! You like the #bfood#k this person gave you?")
sm.setInnerOverrideSpeakerTemplateID(3003156) # Muto
sm.sendSay("#face1##fs50#MORE TASTY!")
sm.setInnerOverrideSpeakerTemplateID(3003150) # Lyon
sm.sendSay("#face0#Well isn't that amazing! #bMuto#k enjoying #bfood#k? It's been a while.")
sm.sendSay("Hm... This stranger is exactly what our village needs right now! You're coming with me, buddy.")
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(parentID, "a=2")
sm.warp(450002204)
