# id 34202 ([Chu Chu] Master Lyck, Top Chef), field 450002000
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003152) # Master Lyck
sm.sendNext("You there! Bring me my knife! #bSlurp slurp#k!")
sm.createQuestWithQRValue(18418, "B=34842")
sm.sendSay("No, no, this soup is all wrong! Are you really thinking of serving this \r\nto #bMuto#k?!")
sm.sendSay("#face0#What a disgrace! #bSlurp-slurp#k!")
sm.setParam(57)
sm.sendSay("Um... Excuse me...")
sm.setParam(37)
sm.sendSay("#face0#Hmm? Are you one of my new chefs? Can't you see I'm busy? \r\nWhy are you standing there like a buffoon?")
sm.sendSay("#face0#Go and bring me more ingredients! \r\nI swear, you're just as dense as #bLyon#k!")
sm.setParam(57)
sm.sendSay("Uh... Actually, #bLyon#k is the one that sent me here...")
sm.setParam(37)
sm.sendSay("Did anyone else hear that strange whining sound? It certainly couldn't \r\nbe that assistant I just sent for ingredients, slurp-slurp!")
sm.setParam(57)
sm.sendSay("#bSigh#k... How am I supposed to carry on a conversation with someone like this...")
sm.setParam(37)
sm.sendSay("EXCUSE ME?!")
sm.setParam(57)
sm.sendSay("Oh! Yes, Lyon sent me...")
sm.setParam(37)
sm.sendSay("What did you just say?")
sm.setParam(57)
sm.sendSay("Lyon sent me?")
sm.setParam(37)
sm.sendSay("#face0#No! Not that! Didn't you just say that I #b'couldn't carry on a conversation \r\nwith a tongue like this'#k!?")
sm.setParam(57)
sm.sendSay("What? That's not what I said at all.")
sm.setParam(37)
sm.sendSay("#face0##fs30#How dare you mock my \r\nbeautiful tongue!")
sm.setParam(57)
sm.sendSay("I didn't!")
sm.setParam(37)
sm.sendSay("#face0#You're FIRED! Get out of my #brestaurant#k at once! #bSlurp, slurp-slurp#k!")
sm.setParam(57)
sm.sendSay("You can't fire me, I don't even work here...")
sm.setParam(37)
sm.sendSay("Huh? You don't?")
sm.setParam(57)
sm.sendSay("Of course I don't... I just arrived here.")
sm.setParam(37)
sm.sendSay("What? Then what business do you have with me?")
sm.setParam(57)
sm.sendSay("I'm #b#h0##k. #bChief Lyon#k told me to find you and help you make delicious food...")
sm.setParam(37)
sm.sendSay("#face3#What? You're the #bkitchen hand#k sent by Lyon?!\r\nThen you should have said so!")
sm.setParam(57)
sm.sendSay("You never gave me a chance to speak... and I'm not a kitchen hand...")
sm.setParam(37)
sm.sendSay("Silence! #rGulla#k will strike in a few days time!\r\nI must perfect my new #b'signature dish'#k! ")
sm.setParam(57)
sm.sendSay("Signature... dish?")
