# id 34211 ([Chu Chu] Eree Valley's Catch of the Day 1), field 450002023
sm.setSpeakerID(3003154) # Pimi
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003154) # Pimi
sm.sendNext("Sniff, sniff... Mmm, it's starting to smell good!")
sm.setParam(2)
sm.sendSay("Yeah! It'll be ready for Muto to eat as soon as we add the top bun.")
sm.setParam(4)
sm.sendSay("You're forgetting the #bmost important#k thing.")
sm.setParam(2)
sm.sendSay("Huh? What do you mean?")
sm.setParam(4)
sm.sendSay("The #bfish#k! No meal is ever complete without seafood.")
sm.setParam(2)
sm.sendSay("We already have two kinds of meat... And you want to add seafood to the mix? I'm not sure that'll taste very good...")
sm.setParam(4)
sm.sendSay("Maybe you misheard me. I said #bI want you to get fish for the sandwich#k #fs20#right now.")
sm.setParam(2)
sm.sendSay("...Fine. It's not like I'm the one who has to eat it.")
sm.setParam(4)
sm.sendSay("Hehe. What a good listener!")
sm.sendSay("All you need to do is gather #i4034950:# #b#t4034950##k and #i4034951:# #b#t4034951##k items from #bGreen Catfish#k and #bBlue Catfish#k in #bEree Valley#k.")
sm.sendSay("Um, can you get around #b20#k to start?\r\nThose that #bcan't fly#k like yourself will have to #bswim#k in Eree Valley. Beware the swift current. If you can't #bswim#k then... You're gonna have a bad time.")
sm.setParam(2)
sm.sendSay("Wait, can YOU fly?")
sm.setParam(4)
sm.sendSay("Isn't that obvious? How could we fly with these little wings? Are you making fun of me? Hehehe.")
sm.setParam(2)
sm.sendSay("Err... Sorry. I'll be back soon.")
sm.startQuest(parentID)
sm.warp(450002012)
