# id 34215 ([Chu Chu] The Secret Ingredient), field 993017200
sm.setSpeakerID(3003151) # Simia
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003151) # Simia
sm.sendNext("We couldn't have made it without your help, #h0#!.")
sm.sendSay("Why don't you take the first bite?")
sm.setParam(2)
sm.sendSay("You... want me to put that in my mouth? After helping you put all that weird stuff in it?")
sm.sendSay("That wasn't part of the agreement...")
sm.sendSay("(Sighs) Well, down the hatch!")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003153) # Pibik
sm.sendSay("Well, don't just eat it! Tell us how it tastes!")
sm.setInnerOverrideSpeakerTemplateID(3003154) # Pimi
sm.sendSay("How is it? Will Muto like it?")
sm.setParam(2)
sm.sendSay("Huh. This is actually pretty okay, considering the horrible things we put inside it. But...")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003151) # Simia
sm.sendSay("But?")
sm.setParam(2)
sm.sendSay("It's... A little on the #bbland#k side.")
sm.sendSay("The sandwich I gave Muto was a lot more flavorful. It wasn't exactly health food.")
sm.setParam(4)
sm.sendSay("Let me try a bite... \r\nHmm... I think I see what you mean.")
sm.sendSay("I've never made a dish this large... so there probably #risn't enough seasoning#k...")
sm.setParam(2)
sm.sendSay("It's almost time to meet with Master Lyck. This'll just have to do for now.")
sm.setParam(4)
sm.sendSay("But... Muto is basically a child... There's no way we'll convince him to eat something this bland...")
sm.setParam(2)
sm.sendSay("Then what would you suggest...? We don't have a lot of time here.")
sm.setParam(4)
sm.sendSay("I know something that would add a lot of flavor... But it's not easy to come by.")
sm.setInnerOverrideSpeakerTemplateID(3003154) # Pimi
sm.sendSay("Simia, you can't be thinking about #r...that#k!")
sm.setParam(2)
sm.sendSay("What is it?")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003151) # Simia
sm.sendSay("Well, we have to grind up the #rfruit of the Slurpy Tree#k.")
sm.setParam(2)
sm.sendSay("That's it? Pick fruit from a tree? No flying gorillas? I can do that! Where's this #rSlurpy Tree#k?")
sm.setParam(4)
sm.sendSay("The #rSlurpy Tree#k grows deep inside the Chu Chu Forest... But... it's no ordinary tree.")
sm.sendSay("The #rSlurpy Tree#k is a big, scary #rman-eating tree#k... That's part of why it's hard to get harvest the #rSlurpy Fruit#k...")
sm.sendSay("I know you're strong, but... Would you be willing to risk your life to get the fruit? I wouldn't ask if the village wasn't at stake...")
sm.setInnerOverrideSpeakerTemplateID(3003154) # Pimi
sm.sendSay("WELL?!")
sm.sendSay("Whee!")
sm.setInnerOverrideSpeakerTemplateID(3003155) # Pidol
sm.sendSay("Whee!")
sm.setParam(2)
sm.sendSay("(Sighs)... I guess I have no choice... I'll be back...")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003151) # Simia
sm.sendSay("Wait! #h0# I'm sorry for making such a difficult request, but...")
sm.setParam(2)
sm.sendSay("You don't need to worry. I'm strong!")
sm.setParam(4)
sm.sendSay("It's not that... It's just that, the Slurpy Fruit #bmust be picked with the stem intact#k... You see, that's the tastiest part...")
sm.setParam(2)
sm.sendSay("I see...")
sm.startQuest(parentID)
sm.createQuestWithQRValue(49000, "count=1;Quest=0;day=152855;QET=20190704201215;state=2")
sm.createQuestWithQRValue(49000, "count=1;Quest=0;day=152855;QET=20190704201215;state=1")
sm.createQuestWithQRValue(49000, "count=1;Quest=0;day=152855;QET=20190704211218;state=1")
sm.warp(450002010)
