# id 34207 ([Chu Chu] The Five-Color Hill Special 1), field 450002023
sm.setSpeakerID(3003151) # Simia
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003151) # Simia
sm.sendNext("#b#h0##k!\r\nHow would one make one of those... #bsand... wiches#k?")
sm.setParam(2)
sm.sendSay("Uh... I need #bbread for a bun, something green and leafy like lettuce, and then some kind of meat patty#k...")
sm.setParam(4)
sm.sendSay("Okay! Then let's recreate the #bbread and 'lettuce'#k first!")
sm.setParam(2)
sm.sendSay("Okay. Can you think of anything here that tastes like the #blettuce, and the bread#k that were on the top and bottom of the sandwich?")
sm.setParam(4)
sm.sendSay("Ooh... I have an idea!")
sm.sendSay("First, head over to Five-Color Hill and gather #b40#k #i4034943:# #b#t4034943##k items from the #bBighorn Pinedeer#k. Those should perfectly replicate the flavor of the bread!")
sm.sendSay("Oh! But first, we need a #bname for our culinary experiment#k. How about we start with a word that #bdescribes the dish#k!")
sm.setParam(2)
sm.sendSay("I think the word 'sandwich' is already perfectly fine...")
sm.setParam(4)
sm.sendSay("No! Our food can't truly be great without a #bgreat name#k!\r\nPi siblings! Help the traveler brainstorm.")
sm.setSpeakerType(3)
sm.setInnerOverrideSpeakerTemplateID(3003153) # Pibik
res = sm.sendNext("Me first! Okay! Pick One:\r\n#b#L0# Delicious#l\r\n#b#L1# Homecooked#l#l\r\n#b#L2# This is dumb.#l")
sm.setSpeakerType(4)
sm.sendNext("#bDelicious #kis it? That's sounds cool!")
sm.setParam(2)
sm.sendSay("What... That's a terrible start for a sandwich name.")
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003154) # Pimi
res = sm.sendNext("Next, how about one of these!\r\n#b#L0# Beefy#l\r\n#b#L1# Smelly#l#l\r\n#b#L2# Your ideas are all terrible...#l")
sm.setSpeakerType(4)
sm.sendNext("Hmm. Sure, #bBeefy #kcould work!")
sm.setParam(2)
sm.sendSay("(Sighs) ...Whatever.")
sm.setSpeakerType(3)
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003155) # Pidol
res = sm.sendNext("Hehe, hehehe. I pick too!\r\n#b#L0# Bite of Heaven#l\r\n#b#L1# Surprise#l\r\n#b#L2# Delight#l")
sm.setSpeakerType(4)
sm.sendNext("...No like! I say... '#bTastesplosion#k' instead! Heheheh. Kaboom!")
sm.setParam(2)
sm.sendSay("Umm...")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003151) # Simia
sm.sendSay("Okay, that settles it! The name of our sandwich is the #bDelicious Beefy Tastesplosion#k!")
sm.sendSay("Okay! Let's prepare our dish!")
sm.createQuestWithQRValue(34219, "foodname=Delicious Beefy Tastesplosion Sandwich")
sm.startQuest(parentID)
sm.warp(450002002)
