# id 34213 ([Chu Chu] A Taste of Skywhale Mountain 1), field 450002023
sm.setSpeakerID(3003155) # Pidol
sm.setParam(2)
sm.sendNext("So... #bPidol#k... What kind of patty do you want to make?")
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(3003155) # Pidol
sm.sendSay("E... Egg... Eggy-eggy-egg.")
sm.setParam(2)
sm.sendSay("Come again?")
sm.setParam(4)
sm.sendSay("I said, I wish you to procure some #beggs#k, you addlebrained buffoon.\r\nPerhaps if you merely tried listening for a change...")
sm.setParam(2)
sm.sendSay("W-wait, so you can speak normally?")
sm.setParam(4)
sm.sendSay("Hehehe, speak... I speak good... Hehe...\r\nEgg patty is yummy... Heeheehee.")
sm.setParam(2)
sm.sendSay("What's with him?")
sm.setParam(4)
sm.sendSay("Hehe. You get #i4034954:# #b#t4034954##k and #i4034955:# #b#t4034955##k from #bCrilia#k and #bPatriarch Crilia#k at #bSkywhale Mountain#k... We use... for seasoning...")
sm.setParam(2)
sm.sendSay("Wait, you were just talking about eggs... You want me to get feathers now?")
sm.setParam(4)
sm.sendSay("Yes! Feathers... Like I say...")
sm.startQuest(parentID)
sm.warp(450002017)
