# id 34331 ([Lachelein] Decisive Battle), field 450004000
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("Is it over? Is that it? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003251) # Protective Mask
sm.sendSay("#face0#I... think it's over. But the barrier around the city hasn't disappeared yet.")
sm.setParam(57)
sm.sendSay("What are you going to do now? ")
sm.setParam(37)
sm.sendSay("#face0#Dreams and reality are separate once more. And now, just like any other, this dream will slowly fade away... ")
sm.setParam(57)
sm.sendSay("But if the dream end, then you'll...  ")
sm.setParam(37)
sm.sendSay("#face0#The nightmare must vanish when the day breaks.")
sm.sendSay("#face0#If the people, or the Erdas are safe, then that means I've fulfilled my purpose. It doesn't matter if I disappear.")
sm.setParam(57)
sm.sendSay("...")
sm.setParam(37)
sm.sendSay("#face0#I guess you'll resume your quest when the fog is lifted. ")
sm.sendSay("#face0#It will be a difficult journey, but I hope you'll return safely.")
sm.completeQuestNoCheck(parentID)
sm.lockInGameUI(False, True)
sm.progressMessageFont(3, 20, 10, 0, "You can shorten previous Arcane River area Daily Quests.")
