# id 34475 ([Arcana] Between a Rock Spirit and a Hard Place), field 450005400
sm.completeQuestNoCheck(parentID)
sm.startQuest(34488)
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.spawnNpc(3003351, -1250, 120)
sm.showNpcSpecialActionByTemplateId(3003351, "summon", 0)
sm.showNpcSpecialActionByTemplateId(3003351, "stand2", -1)
sm.forcedFlip(True)
sm.sendDelay(300)
sm.blind(False, 0, 0, 0, 0, 300)
sm.sendDelay(300)
sm.sendDelay(900)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003301) # Small Spirit
sm.sendNext("#face0#Am I imagining things, or is the ground shaking?")
sm.forcedFlip(True)
sm.sendDelay(600)
sm.forcedFlip(True)
sm.sendDelay(600)
sm.setParam(57)
sm.sendNext("#b(The ground is definitely shaking... What's going on?)#k")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003302) # Wind Spirit
sm.sendSay("#face0#The plump one cries, and we must fly. We should depart, immediately.")
sm.resetNpcSpecialActionByTemplateId(3003351)
sm.showNpcSpecialActionByTemplateId(3003351, "wind2", 0)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/wind", 100)
sm.sendDelay(1000)
sm.forcedMove(True, 100)
sm.sendDelay(2000)
sm.sendNext("#face0#The Spirit Tree sings a pained and mournful tune~")
sm.setInnerOverrideSpeakerTemplateID(3003301) # Small Spirit
sm.sendSay("#face7#No... What's happened to the Spirit Tree?!")
sm.resetNpcSpecialActionByTemplateId(3003351)
sm.showNpcSpecialActionByTemplateId(3003351, "wind3", 0)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/wind", 100)
sm.sendDelay(2400)
sm.sendNext("#face7#We have to hurry!")
sm.setInnerOverrideSpeakerTemplateID(3003314) # Rock Spirit
sm.sendSay("#face0#The Spiwit Twee's in twouble!?")
sm.forcedFlip(True)
sm.sendDelay(600)
sm.sendNext("#face0#I have an idea!")
sm.lockInGameUI(False, True)
