# id 34470 ([Arcana] What the Trees Saw), field 940200216
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b(You asked about the stranger with the terrible aura.)#k")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003310) # Lost Tree Spirit
sm.sendSay("#face0#Curious, are you? Then I'll tell you. But... it is a painful memory.")
sm.sendSay("#face0#It was on a day so quiet, even the winds were still.")
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendNext("#face0#We Tree Spirits were tending to the trees, like any other day.")
sm.onLayer(1000, "00", 0, -80, 12, "Effect/Direction19.img/effect/arcana/3", 4, True, -1, False)
sm.sendSay("#face0#But then we felt an aura of immense evil enter the forest. It was calm, but so very powerful...")
sm.sendSay("#face0#Our first instinct was to hide, and we watched in silence.")
sm.offLayer(1000, "00", False)
sm.onLayer(1000, "01", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/0", 4, True, -1, False)
sm.onLayer(1000, "02", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/1", 4, True, -1, False)
sm.onLayer(1000, "03", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/2", 4, True, -1, False)
sm.onLayer(1000, "04", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/3", 4, True, -1, False)
sm.onLayer(1000, "05", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/4", 4, True, -1, False)
sm.onLayer(1000, "06", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/5", 4, True, -1, False)
sm.onLayer(1000, "07", 0, -80, 12, "Effect/Direction19.img/effect/arcana_disappear/6", 4, True, -1, False)
sm.sendSay("#face0#The trees, flowers, grass, and rocks of the forest... Everything in the strangers wake vanished, transformed into something else.")
sm.sendSay("#face0#...All from coming into contact with that stranger's aura.")
sm.sendSay("#face0#She was only walking by, but in an instant it was all gone...")
sm.sendSay("#face0#Others followed behind her... I don't remember how many. I was too consumed by fear.")
sm.sendSay("#face0#That's all we saw. Just thinking about that day brings back so many terrible feelings. Fear, anger, helplessness...")
sm.offLayer(300, "01", False)
sm.offLayer(300, "02", False)
sm.offLayer(300, "03", False)
sm.offLayer(300, "04", False)
sm.offLayer(300, "05", False)
sm.offLayer(300, "06", False)
sm.offLayer(300, "07", False)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
