# id 34860 (Wielding the Elder Crystal), field 940202032
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3001353) # Illium
sm.sendNext("#face0#Now that I can use the #bElder Crystal#k, I can feel how powerful it is.\r\nI must learn how to use this for combat.")
sm.sendSay("#face0#First, I can use #b#fUI/UIWindow6/illiumSkillTutorial/0#Deploy Crystal#k to summon a Crystal.\r\nOnce I've done that, I can freely move it in front of me. If I use it with\r\nthe #rDown Arrow Key#k, the Crystal will teleport to where I am!")
sm.sendSay("#face0#This crystal is going to #rsignificantly increase my magic ability#k.")
sm.sendSay("#face0#If I hit the Crystal with a #b#fUI/UIWindow6/illiumSkillTutorial/5##b#fUI/UIWindow6/illiumSkillTutorial/4# Radiant Skill#k, a\r\n#r#fUI/UIWindow6/illiumSkillTutorial/1##r,#fUI/UIWindow6/illiumSkillTutorial/2##r Reaction Skill#k will activate.")
sm.sendSay("#face0#Knowing that, if I place the Crystal in a good location and activate\r\na #rReaction Skill#k, I could be really powerful in combat!")
sm.sendSay("#face0#If I hit the Crystal with #b#fUI/UIWindow6/illiumSkillTutorial/4# Radiant Javelin#k and #b#fUI/UIWindow6/illiumSkillTutorial/5# Radiant Orb#k, the magic in the Crystal seems to stack. ")
sm.sendSay("#face0#But the #bamount the Crystal charges#k differs each time. To quickly charge Magic ATT, I'll have to use the two skills in conjunction#r for effective combat#k.")
sm.sendSay("#face0#Oh! If #benough Magic ATT stacks in the Crystal#k, the #rCrystal's appearance#k changes.\r\nOnce it does, I'll be able to use #b#fUI/UIWindow6/illiumSkillTutorial/3#Crystal Skills#k.")
sm.sendSay("#face0##rThere's so much to learn#k about using the Elder Crystal! If I keep researching it, I'm sure I'll get #beven stronger#k!")
