# id 35921 (The Wait for Daybreak), field 100051030
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.zoomCamera(0, 1500, 0, 1504, -77)
sm.forcedFlip(True)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(1000)
sm.setSpeakerType(3)
sm.setParam(549)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0##b(Noon is still several hours away, and it occurs to you that it's been some time since you last rested. Ever since you were afflicted with the relic's curse, you've found it difficult to have restful sleep.)#k")
sm.blind(True, 200, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sendNext("#face6##b(Even now, you can feel your life slowly ebbing away, and a small pain where the curse's sigil marks your body. Though small, you can feel its strength grow with each passing day.)#k")
sm.sendSay("#face0##b(You can't help but wonder what Athena Pierce would think if she saw you in your present state. Would she chastise you as a foolish student whose insatiable curiosity brought disaster upon yourself?)#k")
sm.sendSay("#face0##b(You remember boasting confidently that you'd embark on an amazing adventure; that you'd always follow the path less taken. Right now, though, you feel more lost than you can ever remember feeling. How could you stand tall and look your teacher in the eye in the state you're in?)#k")
sm.sendDelay(500)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face2#Heeeey, what'cha thinkin' about?")
sm.spawnNpc(1013350, 1216, -119)
sm.showNpcSpecialActionByTemplateId(1013350, "summon", 0)
sm.moveNpcByTemplateId(1013350, False, 150, 150)
sm.blind(False, 0, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sendDelay(500)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0#Bwah--!")
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face0#I was playing by myself, but then I saw your face. You looked so sad that I had to come over and see if you're okay...")
sm.sendSay("#face0#Sorry for interrupting you when you were resting. It's just...")
sm.sendDelay(500)
sm.sendNext("#face1#Well... I kinda know how you must feel. I had a depressing day not too long ago, and your face just now made me think of how I felt then. It was like all this weight was pressing down on me.")
sm.sendSay("#face1#B-but I'm not trying to say that you and I are the same. You're so brave and smart, but I'm just a scaredy cat.")
sm.sendSay("#face0#S-so what I'm trying to say is, everyone has times when they feel down. When I feel blue, I like looking at pretty little flowers. I think to myself, if they can make it through times like these, then so can I. Heehee.")
sm.sendSay("#face2#I don't know why that cheers me up, but it usually does the trick. Heehee... I figured maybe you could use a little pick-me-up too, so I brought one for you.")
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/Fever", 100)
sm.onLayer(0, "01", -20, 65, -1200000, "Effect/Direction22.img/effect/PF_flower/0", 4, False, -1, False)
sm.sendDelay(1500)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0#...")
sm.offLayer(300, "01", False)
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendNext("#face0#Well, that took way too much effort.")
sm.sendSay("#face0#Up and at 'em, you two. I've finally fixed the ancient compass!")
sm.sendDelay(500)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face2#Gorgonz is already done with the repairs? I didn't even realize we'd been resting that long! Come on, let's go see what it can do!")
sm.sendDelay(500)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(parentID)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/07/08/13/45")
sm.createQuestWithQRValue(35948, "00=h0;10=h0;11=h1;02=h1;21=h0;12=h0;22=h1;13=h0;23=h1;14=h0;24=h0;15=h0;06=h0;25=h0;07=h0;16=h0;26=h1;08=h0;17=h0;09=h1;19=h0")
