# id 35929 (Assuaged Fears), field 100051040
sm.setSpeakerType(3)
sm.setParam(36)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face0#Well... I guess this is it, then. Now that you found the answer you were looking for, I suppose you'll be on your way, right? I know, I know. I promised I wouldn't be clingy.")
sm.sendSay("#face0#But wherever your travels take you, I hope you'll be safe. I may not be the bravest, but thanks for letting me come on this adventure with you.")
sm.setSpeakerType(4)
sm.setSpeakerID(1013319) # Brie
res = sm.sendAskAccept("#face0#Oh! If you ever feel like coming back to visit our little Karuppa village sometime, you can use this skill to return there whenever you like.")
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.progressMessageFont(3, 20, 4, 0, "You acquired the 'Return to Partem' skill.")
sm.sendDelay(500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.sendNext("#face0#It'd be great to see you again someday. If you ever feel like dropping by, you'll always have a friend in me.")
sm.sendSay("#face2#I'm going back to the village to tell all the Karuppa about everything I heard and saw in the ruins. Will they believe me? Who knows? ...Though I guess Gorgonz might. He's weird like that.")
sm.sendSay("#face0#I've still got a long way to go before I can start feeling confident. What do you think? Do you think I'll be able to be brave like you someday?")
sm.sendSay("#face0#Ack... Just listen to me, rambling on. I shouldn't keep you any longer. Goodbye, for now!")
sm.sendDelay(500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(500)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0#I guess she said everything she wanted to say. I'll see you 'round, kid. And thanks for everything.")
sm.sendDelay(1000)
sm.sendNext("#face0#Anyway...")
sm.sendSay("#face1#(It sounds like there's no way to completely rid myself of this curse. That leaves me just one option: I'm gonna have to rise to the occasion and prove myself worthy of the relic's full power.)")
sm.sendSay("#face0#('Wander, explore, and grow in strength and knowledge,' huh? I guess now that I know I can at least suppress the curse's effects, there's nothing stopping me from chasing after the next adventure.)")
sm.sendDelay(500)
sm.sendNext("#face6#(Still, that story about a guy in a black robe using weird magic on the relic worries me. And the voice was awfully tight-lipped after it told me about the nature of the relic's power.)")
sm.sendSay("#face0#(Maybe if I can master the relic's powers, I can get the voice to talk to me again. But until then, it looks like I'm on my own as far as figuring out how it works.)")
sm.sendDelay(1000)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.warp(910090314)
