# id 35928 (Soulful Discourse), field 100051044
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.setSpeakerID(1013318) # Soul
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013360) # Soul
res = sm.sendNext("#face0#Ahh... I can feel it. A heart drawn by confusion, driven by quiet desperation. The answers you seek are here.\r\n\r\n#b#L0# Ask about the relic and the curse sigil.#l")
sm.blind(True, 200, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/blackHeaven/secretmission3", 100)
sm.onLayer(500, "00", 0, -85, -12, "Effect/Direction22.img/effect/PF_past/0", 4, False, -1, False)
sm.sendDelay(1000)
sm.setSpeakerType(3)
sm.sendNext("#face0#Long ago, the ancient Karuppa that resided in this land fashioned from the wood of a holy tree a sacred icon to venerate in worship.")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face3#Hey, I recognize that design...")
sm.sendDelay(500)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013360) # Soul
sm.sendNext("#face0#As you suspect, that sacred totem is the relic now in your possession. Once, it served as a symbol of enlightened benevolence that healed the sick and gave guidance to those who has lost their way.")
sm.sendSay("#face0#Time passed, and as order was born into this world, the power of the relic gradually began to wane.")
sm.sendSay("#face0#Those who knew of the relic's existence lived their lives and passed on, and as fewer and fewer remembered the ancient ways, the relic came to be regarded as a legend.")
sm.sendSay("#face0#Perhaps it would have been better that way; to eventually be forgotten entirely...")
sm.playSound("Sound/SoundEff.img/blackHeaven/secretmission3", 100)
sm.onLayer(500, "01", 0, -85, -12, "Effect/Direction22.img/effect/PF_past/1", 4, False, -1, False)
sm.sendDelay(1000)
sm.sendNext("#face0#However, hundreds of years ago, a man clad in black robes came to this place and worked his fell spellcraft upon the relic.")
sm.sendSay("#face0#When his hex had been woven, he returned the relic to its resting place and swiftly departed. From that day forward, the relic began to be corrupted by negative energies.")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face3#A mysterious man in black robes?")
sm.sendDelay(500)
sm.offLayer(300, "00", False)
sm.offLayer(300, "01", False)
sm.playSound("Sound/SoundEff.img/blackHeaven/secretmission4", 100)
sm.blind(False, 0, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013360) # Soul
sm.sendNext("#face0#The relic in your possession retains both its original nature and its corrupted state. You have surely felt the stirrings of both within you.")
sm.sendSay("#face0#The corrupted power has already become one with the relic, and cannot simply be made to disappear. It can, however, be suppressed.")
sm.sendSay("#face0#The only way to do so, however, is for you to become the true inheritor of the relic. Only then will its corruption be quelled.")
sm.sendDelay(500)
sm.sendNext("#face0#It is said that a superior tool chooses a worthy owner. The relic, though no mere tool, will respond to your mastery and allow you to draw out its hidden powers.")
sm.sendSay("#face0#Wander, explore, and grow in strength and knowledge. When the time is right, the relic shall guide you.")
sm.sendDelay(500)
sm.sendNext("#face0#I shall pray that you grow in wisdom, to see the path, and in strength, to walk it without fear.")
sm.blind(True, 255, 240, 240, 240, 1300)
sm.sendDelay(1600)
sm.sendDelay(500)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0#The path...")
sm.sendDelay(500)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(parentID)
sm.createQuestWithQRValue(35948, "00=h0;10=h0;02=h1;11=h1;12=h0;21=h0;13=h0;22=h1;14=h0;23=h1;06=h0;15=h0;24=h0;16=h0;07=h0;25=h0;17=h0;08=h0;26=h1;09=h0;19=h1")
sm.warp(100051040)
