# id 37157 ([Elodin] Nature's Roadblocks 2), field 101081000
sm.setSpeakerType(3)
sm.setParam(2)
sm.sendNext("How long have I been here?")
sm.sendSay("I feel like I've been going in circles for ages.")
sm.sendSay("And more of these things keep popping up like, well, weeds!")
res = sm.sendAskYesNo("What if I'm stuck here forever?")
sm.setParam(3)
sm.sendNext("I hope I'm going the right way...")
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
sm.startQuest(parentID)
