# id 37172 ([Elodin] Touching Reunion), field 101084400
sm.setSpeakerID(1501004) # Shimmer Songbird
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(1501015) # Shimmer Songbird
sm.sendNext("My baby!")
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1000)
sm.onLayer(1500, "00", 0, 0, 12, "Effect/Direction21.img/Elodin/meet/0", 4, True, -1, False)
sm.sendDelay(3000)
sm.setInnerOverrideSpeakerTemplateID(1501010) # Baby Bird
sm.sendNext("Mama! I missed you so much!")
sm.setInnerOverrideSpeakerTemplateID(1501015) # Shimmer Songbird
sm.sendSay("Where have you been?! I've been worried sick!")
sm.setInnerOverrideSpeakerTemplateID(1501010) # Baby Bird
sm.sendSay("Ruenna has been taking care of me!")
sm.setInnerOverrideSpeakerTemplateID(1501015) # Shimmer Songbird
sm.sendSay("Ruenna? You mean you're the one she needed help with?")
sm.sendDelay(3000)
sm.offLayer(500, "00", False)
sm.sendDelay(2000)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.sendNext("#h0#! I can't thank you and Ruenna enough for bringing my baby safely home.")
sm.sendSay("I looked everywhere! I worried I'd lost him forever.")
sm.sendSay("And the forest has been so strange lately, what with all those weird noises... I didn't know what to do!")
sm.setParam(3)
sm.sendSay("......")
sm.sendSay("Ruenna was worried too. When you stopped singing, she thought something bad happened.")
sm.sendSay("She wanted to check on you, but she couldn't bring the baby, so here we are.")
sm.setParam(5)
sm.sendSay("I've got to thank her! But before I do...")
sm.sendSay("Why don't we start the singing lessons?")
sm.sendSay("But we need your help to do it, #h0#.")
sm.setParam(3)
sm.sendSay("(She may be overestimating your experience with bird calls a bit.)")
sm.startQuest(parentID)
sm.completeQuestNoCheck(parentID)
