sm.flipDialoguePlayerAsSpeaker()
sm.sendNext("I remember now. I put in a photograph. A photo, the only one, with everyone... They told me to put my most prized possession in, and that was it. Good choice, I guess.")
sm.sendSay("Now I'm sure. The world has #rCOMPLETELY forgotten me.#k\r\nThere are absolutely no traces of me anywhere.")
sm.startQuest(parentID)
sm.completeQuest(parentID)
sm.jobAdvance(2511)
