# id 55235 ([Alishan] Where in the Other World?), field 800000202
sm.setSpeakerID(9330459) # Xiaoming
sm.setParam(37)
sm.setColor(1)
#sm.setInnerOverrideSpeakerTemplateID(9330459) # Xiaoming
sm.sendNext("I was thinking... I know you didn't come to #bLeshan#k as a tourist, but maybe you could, y'know, ease into it? ")
sm.setParam(57)
sm.sendSay("Ummm...")
sm.setParam(37)
sm.sendSay("GREAT! Okay, so... Do you see that beautiful mountain over there? We call that mountain #bAlishan#k! It's the jewel of our village.")
sm.sendSay("As beautiful as the mountain is, we don't get many visitors up here. I made some posters, but I don't know if crayon is professional enough.")
sm.setParam(57)
sm.sendSay("Ummm...")
sm.setParam(37)
sm.sendSay("So, hey... You seem to be okay with being in another world right now. Are you used to this kinda thing?")
sm.setParam(57)
sm.sendSay("Ummm...")
sm.setParam(37)
sm.sendSay("Don't worry, I've seen lots of people like you lately.")
sm.setParam(57)
sm.sendSay("Really? People like me?")
sm.setParam(37)
sm.sendSay("Yeah, but I think #b#p9330460##k sent them back to... wherever you folks come from. And speaking of #b#p9330460##k, you should go find him. After you buy something, of course!")
sm.createQuestWithQRValue(18418, "B=3334")
