# id 58922 ([Hieizan Temple] Jars at Rest 2), field 811000018
sm.setSpeakerID(9130108) # Mysterious Boy
sm.setParam(4)
sm.setInnerOverrideSpeakerTemplateID(9130107) # Mysterious Boy
sm.sendNext("Just place these jars on the stone altar in front of the east tower over there.\r\nSimple, right? I've heard that that area is the best spot... ")
sm.sendSay("Did you know? There are a lot of souls floating around in this temple.")
sm.setParam(16)
sm.sendSay("(You feel something strange. He doesn't seem like the same boy you met earlier.)")
sm.setParam(4)
res = sm.sendAskYesNo("Now, go on. Place the jars on that altar.  ")
sm.startQuest(parentID)
sm.sendSayOkay("Simply click the altar. ")
sm.lockInGameUI(True, True)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.setSpeakerType(3)
sm.setParam(17)
sm.sendNext("(What the-? )")
sm.sendDelay(1000)
sm.sendNext("What are you trying to do?")
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9130108) # Mysterious Boy
sm.sendSay("Heh heh heh... Good work. You've completed 'her' task admirably. ")
sm.sendSay("You know, 'she' told me you'd be easy to trick, with your do-gooder spirit and weak mind. I thought, surely you COULDN'T be that dumb! ")
sm.setParam(17)
sm.sendSay("What? Who is 'she'?")
sm.setParam(5)
sm.sendSay("Well, my part is done, so see ya! You should be more careful lending a hand next time. Ha! ")
sm.setParam(17)
sm.sendSay("Ugh, I've been tricked... ")
sm.sendSay("(Follow the boy to #m811000019:#. You will be teleported automatically. ")
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(parentID)
sm.warp(811000019)
