# id 64065 ([MONAD: The First Omen] Butler's Dilemma), field 867201100
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400581) # Butler
sm.sendNext("#face0#Unbelievable. To ask a civilian for help... ")
sm.setParam(57)
sm.sendSay("#bThey need time to get their strength back. ")
sm.setParam(37)
sm.sendSay("#face0#In wartime, a lack of discipline means certain defeat. ")
sm.sendSay("#face0#When I was younger, I fought for days at a time without sleeping or eating. These layabouts get full meals and sleep by warm fires, and still have the nerve to complain? Unacceptable! ")
sm.sendSay("#face0#I've already had to deal with rumors among the soldiers of a massive shadow during the battle at Kaptafel, and now this. ")
sm.setParam(57)
sm.sendSay("#bWait, a massive shadow? ")
sm.setParam(37)
sm.sendSay("#face0#Yeah. Ridiculous rumors like that can be bad for morale, you know. ")
sm.setParam(57)
sm.sendSay("#bWho started the rumor? ")
sm.setParam(37)
sm.sendSay("#face0#It was Williams, one of the soldiers resting here earlier. That's how undisciplined they've become. You see what happens when you go easy on them? ")
sm.setParam(57)
sm.sendSay("#b(Might be worth asking Williams about what he saw.) ")
sm.setParam(37)
sm.sendSay("#face0##h0#? ")
sm.setParam(57)
sm.sendSay("#bThank you, Vice Captain Butler. Please excuse me... ")
sm.setParam(37)
sm.sendSay("#face0#Where are you going? I'm not finished... ")
sm.startQuest(parentID)
