# id 64025 ([MONAD: The First Omen] Evacuation Prep), field 867200400
sm.completeQuestNoCheck(parentID)
sm.showNpcSpecialActionByTemplateId(9400588, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400587, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400616, "summon", 0)
sm.startQuest(64160)
sm.startQuest(64166)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#Ah, perfect timing! ")
sm.sendSay("#face0#With the snow cleared away, this cart looks better than I remember. Maybe it won't need so much work... ")
sm.sendSay("#face0#While I'm doing this you should grab whatever you've got left in town. Gold, jewels, priceless works of art... ")
sm.setParam(57)
sm.sendSay("#b...? ")
sm.setParam(37)
sm.sendSay("#face0#...That was a joke. If you can, I'd just like you to check and see how preparations are going. ")
sm.setParam(57)
sm.sendSay("#bAh. Not a problem. ")
sm.setParam(37)
sm.sendSay("#face0#Thanks. I'll see you in a bit.")
