# id 64065 ([MONAD: The First Omen] Butler's Dilemma), field 867201100
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bWilliams? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400622) # Williams
sm.sendSay("Oh, hey #h0#! I hope you didn't get in trouble with the Dispatch Commander? Sorry, that was our fault... ")
sm.setParam(57)
sm.sendSay("#bNot at all. Vice Captain Butler mentioned you saw a massive shadow back at... ")
sm.setParam(37)
sm.sendSay("Ah! It's nothing! I was just tired and hallucinating. Really, it was nothing! ")
sm.setParam(57)
sm.sendSay("#bWell, the thing is... I saw something similar. I'd like to know what you saw. ")
sm.setParam(37)
sm.sendSay("No... I really was mistaken. ")
sm.lockInGameUI(True, False)
sm.flipNpcByTemplateId(9400587, False)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400587, False, 50, 50)
sm.sendDelay(1000)
sm.lockInGameUI(False, True)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#...There are quite a few villagers talking about that shadow as well. ")
sm.sendSay("#face0#People are calling it the 'smoke shadow'. Of course, no one knows if it was just a strange cloud... or an actual creature. ")
sm.sendSay("#face0#But I am certain that no one wants to believe it. ")
sm.setInnerOverrideSpeakerTemplateID(9400622) # Williams
sm.sendSay("Err... ")
sm.setParam(57)
sm.sendSay("#bWhat could it be... ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#For now, I choose to believe it was an illusion. It's a... more comforting thought, since no one knows for sure. ")
sm.sendSay("#face0#The truth is that we've all seen it many times, every time there was a snowstorm, or smoke, or thick fog. The people assume it's the shadow of a mountain or an odd cloud. ")
sm.setParam(57)
sm.sendSay("#b(I definitely need to look into this further. ) ")
sm.createQuestWithQRValue(64020, "chk1=1;chk2=1;chk3=1")
sm.completeQuestNoCheck(parentID)
