# id 64071 ([MONAD: The First Omen] Svarti Heirloom), field 867201050
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendNext("H-hero! Are you really leaving? ")
sm.setParam(57)
sm.sendSay("#bYes, there's something I need to take care of. ")
sm.setParam(37)
sm.sendSay("But, the forest... it's so dangerous right now! ")
sm.sendSay("Don't tell the chief about this, but... please, take this! ")
sm.completeQuestNoCheck(parentID)
sm.sendSay("This is a relic that has been passed down in our village for generations. ")
sm.setParam(57)
sm.sendSay("#bBy giving this to me... ")
sm.setParam(37)
sm.sendSay("You'll need it more than we do! I've been waiting for this day, to do some real good for someone! ")
sm.setParam(57)
sm.sendSay("#bThank you, Thorson. I hope I won't have to use it, so I can return it when I come back. ")
sm.setParam(37)
sm.sendSay("Sounds good! So, may the breath of Windsleep Forest be with you! ")
sm.lockInGameUI(True, False)
sm.sendDelay(500)
sm.forcedFlip(True)
sm.forcedMove(True, 309)
sm.sendDelay(501)
sm.sendDelay(1000)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64008, "mapIdx=0")
sm.warp(867201200)
