# id 64062 ([MONAD: The First Omen] Actinops), field 867201100
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendNext("W-wait a second! ")
sm.setParam(57)
sm.sendSay("#bWhat? ")
sm.setParam(37)
sm.sendSay("You know, we're a village of fishermen. Er, harpooners, or whatever you call it. Uh... the monster that showed up in town... ")
sm.setParam(57)
sm.sendSay("#bThe toxic beast? ")
sm.setParam(37)
sm.sendSay("Oh! Is that what you call it? ")
sm.setParam(57)
sm.sendSay("#bAh... not really. One of our knights likes calling it that. ")
sm.setParam(37)
sm.sendSay("I think that monster is... ")
sm.setParam(57)
sm.sendSay("#bIs...? ")
sm.setParam(37)
sm.sendSay("The fish we used to catch! Actinops!")
sm.setParam(57)
sm.sendSay("#bThat monster... was a fish? ")
sm.setParam(37)
sm.sendSay("Yes! Actinops are transparent, down to their blood! It looks a bit gross, but tastes real good. It's Abrup's local specialty! ")
sm.setParam(57)
sm.sendSay("#bI don't know... fish aren't usually pink. Or huge. Or attack people. ")
sm.setParam(37)
sm.sendSay("Yeah, very true. Maybe it ate something pink? Oh, but that's not all! ")
sm.sendSay("Actinops can regenerate really fast. It can also puff itself up real big, so with its regeneration it can do that as long as it wants. ")
sm.sendSay("Didn't you see how it stretched its arm out? ")
sm.setParam(57)
sm.sendSay("#bHmm... ")
sm.setParam(37)
sm.sendSay("Okay, if you still don't believe me, there's another clue! ")
sm.sendSay("Poison! Actinops are poisonous! ")
sm.sendSay("If that monster really is Actinops... ")
sm.setParam(57)
sm.sendSay("#bThen...? ")
sm.setParam(37)
sm.sendSay("If it is Actinops... ")
sm.sendSay("It will focus when it regenerates! And it won't move or attack during that brief time. That's your chance! ")
sm.setParam(57)
sm.sendSay("#b(Thinking back, the monster did pause for a moment after stretching its arm.) ")
sm.setParam(37)
sm.sendSay("But to be honest... it does sound weird saying it out loud. ")
sm.sendSay("It really is Actinops, I'm sure of it... but I have no idea how a small fish turned into such a monster. ")
sm.setParam(57)
sm.sendSay("#bWell, thanks for clearing that up. ")
sm.setParam(37)
sm.sendSay("N-n-not at all! I'm honored to be of help! ")
sm.sendSay("If you have any questions about anything, you can ask me! ")
sm.setParam(57)
sm.sendSay("#bYes, will do. ")
sm.setParam(37)
sm.sendSay("...Whew!")
sm.completeQuestNoCheck(parentID)
