# id 64026 ([MONAD: The First Omen] Ullan's Pets), field 867200480
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bUllan, are you okay? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendSay("Waaah... Dad's so stupid... He doesn't understand me, and gets so mad about it! ")
sm.sendSay("Pete and Elle... I met them when I was 10, the first time I went out with the hunters. They lost their mother to werewolves and were hiding between the rocks... ")
sm.sendSay("Of course, Dad was against it. He said Shrelephants need to live in the wild... But Mom sided with me, so we kept them. Mom taught me how to feed Pete and Elle milk, since they were still babies, and also named them with me... ")
sm.sendSay("I've already lost Mom... If I lose Pete and Elle... I... Sniff... ")
sm.setParam(57)
sm.sendSay("#bIt's okay, Ullan. Don't cry. We'll find them together. ")
sm.setParam(37)
sm.sendSay("Waaah... ")
sm.sendSay("...No. Honestly, I know Dad is right. We gotta make sure everyone gets out of the village, and that means lots of kids and hurt people need us. Pete and Elle are smart... Sniff... I'm sure they'll catch up... ")
sm.setParam(57)
sm.sendSay("#b... ")
sm.setParam(37)
sm.sendSay("(She's trying hard to control herself.) ")
sm.sendSay("...Sigh. I'm okay now. ")
sm.sendSay("Let's hurry back to town and help the others. ")
sm.startQuest(64161)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400588, False, 50, 30)
sm.sendDelay(5000)
sm.flipNpcByTemplateId(9400588, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400588, True, 1000, 50)
sm.completeQuestNoCheck(parentID)
sm.lockInGameUI(False, True)
