# id 64067 ([MONAD: The First Omen] Treatment Necessities), field 867201100
sm.lockInGameUI(True, False)
sm.forcedFlip(True)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(100)
sm.blind(False, 0, 0, 0, 0, 250)
sm.sendDelay(300)
sm.moveNpcByTemplateId(9400580, True, 20, 20)
sm.showNpcSpecialActionByTemplateId(9400584, "skill2", 0)
sm.sendDelay(2000)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, False, 20, 20)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b(Alika and Janyt are busy taking care of the injured.) ")
sm.sendSay("#b(Wonder if there's anything I can help with.) ")
sm.forcedMove(False, 30)
sm.sendDelay(500)
sm.sendNext("#bJanyt, can I help with anything? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400584) # Janyt
sm.sendSay("#face0#Ah... No. The blessings of Afinas suffice. ")
sm.setParam(57)
sm.sendSay("#bBut there should be something. ")
sm.setParam(37)
sm.sendSay("#face1#No. ")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0##h0#? ")
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, True, 60, 30)
sm.sendDelay(500)
sm.setParam(57)
sm.sendNext("#bOh, Alika. I wanted to see if there is anything I could help with. ")
sm.setParam(37)
sm.sendSay("#face1#Of course! There's always plenty to do. ")
sm.sendSay("#face1#Can you find us some supplies for treating injuries? ")
sm.sendSay("#face1#As you can see, there is a limit to Devata Janyt's healing powers. She needs some time to recover, but we don't have enough medicine to treat everyone. ")
sm.setParam(57)
sm.sendSay("#bI'd love to help. What can be used for medicine around here? ")
sm.setParam(37)
sm.sendSay("#face1#The Abrup people have a traditional remedy made from melted Leatty Crystals. I haven't tested it myself, but it's worth a try, right? ")
sm.sendSay("#face1#I was told that the leatty gather on the snowfield near the river. Cayne is already there, so you can look for him. ")
sm.startQuest(parentID)
sm.sendDelay(2000)
sm.lockInGameUI(False, True)
sm.warp(867201180)
