# id 64087 ([MONAD: The First Omen] Alika's Research Materials), field 867202300
sm.completeQuestNoCheck(parentID)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bAlika, take these. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#What are they? ")
sm.sendSay("#face1#Wait... are these...? ")
sm.sendSay("#face2#Wow! Transparent Actinops skin... giant Fembris fangs... hard Frostflail Yeti horns... Did you gather these for my research? ")
sm.setParam(57)
sm.sendSay("#bI hope they lead to a big breakthrough for you! ")
sm.setParam(37)
sm.sendSay("#face1#Oh, thank you so much! To be honest, I was starting to worry that I'd have to return to Afinas without any personal achievements. ")
sm.sendSay("#face1#I couldn't worry about that, since there's so much at stake here, but... you really came through for me. How can I ever repay you? ")
sm.setParam(57)
sm.sendSay("#bDon't worry about that, it was no trouble at all. ")
sm.setParam(37)
sm.sendSay("#face3#Really? Because I remember that Frostflail Yeti giving us some trouble... ")
sm.setParam(57)
sm.sendSay("#bHey, as long as you're happy, I'm happy.")
