# id 64111 ([MONAD: The First Omen] Guilt), field 867202300
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bUllan? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendSay("Hero... W-waaah...")
sm.setParam(57)
sm.sendSay("#bUllan! What happened? ")
sm.setParam(37)
sm.sendSay("Waahh... I was so immature... ")
sm.sendSay("It happened when I was so young... ")
sm.setParam(57)
sm.sendSay("#bWhat are you trying to say, Ullan? Slow down. ")
sm.setParam(37)
sm.sendSay("...It's all our fault that Blanche is gone. ")
sm.setParam(57)
sm.sendSay("#bWhat do you mean? ")
sm.setParam(37)
sm.sendSay("Sniff... Blanche and Granny Sanaan lived in town when I was little... ")
sm.sendSay("I remember playing in the forest with Blanche and the other kids... ")
sm.sendSay("And... ")
sm.sendSay("Blanche... her skin color was different than ours... and she was really strong... ")
sm.sendSay("We started being mean to her. I don't know if we were jealous, or scared... We called her a monster... ")
sm.setParam(57)
sm.sendSay("#b...I see. ")
sm.setParam(37)
sm.sendSay("After that, Granny Sanaan and Blanche left town. They never came back. ")
sm.sendSay("I forgot about them. I even forgot why they left... what I did... ")
sm.sendSay("Sniff... I can't imagine how scared and lonely Sanaan and Blanche must have been in the forest.")
sm.sendSay("If they'd stayed in the village, if they'd never gone into the forest... Blanche would have gone hunting with others that day, and she never would've gone missing! ")
sm.sendSay("I'm so sorry... Waaahhh...")
sm.sendSay("And I hate that my dad didn't tell me Granny Sanaan came looking for Blanche! I hate that he just let her leave like that! ")
sm.setParam(57)
sm.sendSay("#bI'm sure Chief Kan had your best interests at heart, Ullan. ")
sm.setParam(37)
sm.sendSay("Ohhh... He's just gonna say it was for the greater good again! I can't stand it! ")
sm.setParam(57)
sm.sendSay("#bUllan, why not come with me to apologize to Sanaan? It's never too late. ")
sm.setParam(37)
sm.sendSay("Do you think... she'd even listen to me? ")
sm.setParam(57)
sm.sendSay("#bI'm sure she will. ")
sm.sendSay("#bIn fact, I bet she'll respect you for being so brave. ")
sm.setParam(37)
sm.sendSay("You... you really think so? Sniff...")
sm.setParam(57)
sm.sendSay("#bI'm sure of it. Trust me. ")
sm.setParam(37)
sm.sendSay("Well... okay. But what do I say? I mean, I know how to apologize, but... I just...")
sm.setParam(57)
sm.sendSay("#bJust be honest. And if you need my help, I'm always right here. ")
sm.setParam(37)
sm.sendSay("Oh, I can't thank you enough, hero!")
sm.lockInGameUI(True, False)
sm.showNpcSpecialActionByTemplateId(9400589, "attack1", -1)
sm.showNpcSpecialActionByTemplateId(9400592, "attack1", -1)
sm.sendDelay(3000)
sm.setParam(57)
sm.sendNext("#b(Aruhi sounded so sincere... like he was really telling the truth.) ")
sm.sendSay("#bHm... ")
sm.sendDelay(1000)
sm.sendNext("#b(Since Sanaan has been living in the forest all this time, maybe she's seen something.) ")
sm.sendSay("#b(I'll probably see her before Ullan does.) ")
sm.sendSay("#b(I should head to the General Store to find Sanaan.)")
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64112, "chk1=1")
sm.completeQuestNoCheck(parentID)
sm.startQuest(64112)
