# id 64114 ([MONAD: The First Omen] Elva's Role), field 867202300
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendNext("While we're on the subject of paying thanks, #h0#... ")
sm.sendSay("Do you think you might be able to do me a small favor? ")
sm.sendSay("I mean... Oh, I hope I don't come off as just being greedy. I know you're so busy... Ahh, how can I say this... ")
sm.setParam(57)
sm.sendSay("#bPlease, it's no trouble. Tell me what you need. ")
sm.setParam(37)
sm.sendSay("Thank you. You see, I may be a simple merchant but I'm very dedicated to my work. And my work is to make sure I always have what people need. ")
sm.sendSay("Some people might laugh at the idea of a shopkeeper being so dedicated, but... ")
sm.setParam(57)
sm.sendSay("#bNo one thinks that. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("Who would think such a thing? Everyone I know adores you. ")
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("Oh, goodness... ")
sm.sendSay("You see, we haven't been able to trade with other villages or El Nath for a while because of the chaos, and that's left me light on supplies. ")
sm.sendSay("I'm not worried about luxuries or entertainment, mind you, I mean basics like potions. Considering the situation, that could be a problem. ")
sm.sendSay("I hate to trouble you, but this is for everyone's sake. ")
sm.setParam(57)
sm.sendSay("#bDon't sweat it. We could all use more potions. I'll help in anyway way I can. ")
sm.setParam(37)
sm.sendSay("Thank you. That really puts my mind at ease. ")
sm.sendSay("I'm no alchemist but I can brew decent potions. I just need a few ingredients. ")
sm.setParam(57)
sm.sendSay("#bSure. What do you need? ")
sm.setParam(37)
sm.sendSay("Hold on. I had them written down somewhere... Ah! Here they are. ")
sm.sendSay("Twenty Eyeful antennae, ten Optusa leaves, ten Leatty Crystals, ten vials of the clear Actinops blood... ")
sm.sendSay("Oh. It's a bit more than a few, actually...")
sm.setParam(57)
sm.sendSay("#bHa, that's okay, I'm used to it. Twenty Eyeful antennae, ten Optusa leaves... What was the rest?")
sm.setParam(37)
sm.sendSay("Ten Leatty Crystals and ten vials of the clear Actinops blood! ")
sm.sendSay("You know what? Just take the note. It includes how to get each ingredient as well. ")
sm.startQuest(parentID)
sm.sendSay("All right. Here on page ten: How to Make a Super Elixir! ")
sm.setParam(57)
sm.sendSay("#bAlright. I'll be back soon.")
