# id 64133 ([MONAD: The First Omen] Building a Catapult), field 867202300
sm.lockInGameUI(True, False)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bAlika, what's the matter? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Ah... #h0#... ")
sm.sendSay("#face0#It's the catapult.")
sm.setParam(57)
sm.sendSay("#bThe catapult? The one you've been working on? Is something wrong? ")
sm.setParam(37)
sm.sendSay("#face0#Just a minor thing. We've built the frame, and stocked up on rocks to launch. ")
sm.sendSay("#face4#The problem is that we can't find any rope in Skuas that's strong enough to strap the rocks into. ")
sm.setParam(57)
sm.sendSay("#bWell, we just need to go out and get some! ")
sm.setParam(37)
sm.sendSay("#face4#Remember, Fembris were spotted near the village not long ago. That means an attack could be coming at any moment.")
sm.sendSay("#face4#With that threat out there, I can't let anyone leave the town. Not even you. ")
sm.setParam(57)
sm.sendSay("#bHm... ")
sm.sendSay("#b(I could probably slip out and come right back.) ")
sm.sendSay("#b...How strong does the rope need to be? ")
sm.setParam(37)
sm.sendSay("#face5##h0#, don't you even think about leaving. It's too dangerous. ")
sm.setParam(57)
sm.sendSay("#bLook, the catapult could make a huge difference for our defenses. If I go alone, I can find what you need and be back in a flash. ")
sm.setParam(37)
sm.sendSay("#face5#No, I can't let you go alone. It's too risky. ")
sm.sendSay("#face4#Just forget about the rope. We'll find something to substitute for it.")
sm.setParam(57)
sm.sendSay("#b(Yeah, might as well sneak out and get this done.) ")
sm.lockInGameUI(False, True)
sm.startQuest(parentID)
sm.warp(867202200)
