# id 64113 ([MONAD: The First Omen] Source of the Rumor), field 867202300
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendNext("Ah...")
sm.sendSay("Greetings. I'm Elva, and run the general store here in Skuas. ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("As I said, this fine young lady here was the one that brought me back to town. ")
sm.sendSay("While I was living out there in my cabin, I'd come to the general store here in Skuas to pick up supplies. ")
sm.sendSay("But when I stopped coming around, she came looking for me. ")
sm.setParam(57)
sm.sendSay("#bHow considerate! ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400601) # Elva
sm.sendSay("Oh, a store owner should always remember her customers.")
sm.sendSay("Many, many people come by the store, often with news or gossip to share. ")
sm.sendSay("And that's why I think I might be able to answer your earlier question, #h0#. ")
sm.setParam(57)
sm.sendSay("#bDo you mean when I asked about seeing anyone suspicious? ")
sm.setParam(37)
sm.sendSay("Yes, although I didn't see anyone myself. ")
sm.sendSay("Around 6 months ago, one of our herb gatherers told me they saw someone suspicious out in the forest. ")
sm.sendSay("I hadn't thought much of it since it was such an odd tale, but what you said reminded me, #h0#. ")
sm.setParam(57)
sm.sendSay("#bCould you elaborate? ")
sm.setParam(37)
sm.sendSay("Let's see... they said they saw someone in white steel armor, completely closed. Even their face was covered... I remember them saying you would lose them in a blizzard. ")
sm.sendSay("At first they thought the person was blinking around the forest, but they realized there were many of them moving around. ")
sm.setParam(57)
sm.sendSay("#bIt's the same story... ")
sm.setParam(37)
sm.sendSay("Pardon? ")
sm.setParam(57)
sm.sendSay("#bWe have another witness who saw the exact same thing. ")
sm.setParam(37)
sm.sendSay("Is that so? That's... chilling. ")
sm.setParam(57)
sm.sendSay("#bWho did you hear this from? ")
sm.setParam(37)
sm.sendSay("An herb gatherer... he went into the forest to find his missing wife, and never came back. ")
sm.setParam(57)
sm.sendSay("#bI see... ")
sm.sendSay("#bThank you, Elva. ")
sm.sendSay("#b(Turns out Aruhi wasn't just rambling after all.)")
sm.createQuestWithQRValue(64039, "chk1=1;chk2=1")
sm.completeQuestNoCheck(parentID)
