# id 4 (CaravanP2_chk4), field 867200550
sm.createQuestWithQRValue(64006, "WC=1;k1=0;k2=0;k3=0;k5=0;speed=20;man=199;prog=0;Pt=CaravanP2_chk3;Ec=4;max=20;weather=2;food=528")
sm.createQuestWithQRValue(64006, "WC=2;k1=0;k2=0;k3=0;k5=0;speed=20;man=199;prog=0;Pt=CaravanP2_chk3;Ec=4;max=20;weather=2;food=528")
sm.createQuestWithQRValue(64006, "WC=2;k1=0;k2=0;k3=0;k5=0;speed=20;man=199;prog=0;Pt=Caravan_chk4;Ec=4;max=20;weather=2;food=528")
sm.createQuestWithQRValue(64006, "WC=2;k1=0;k2=0;k3=0;k5=0;speed=20;man=199;prog=0;Pt=CaravanP2_chk4;Ec=4;max=20;weather=2;food=528")
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendNext("#face1#Nothing! I've been doing my job, really! ")
sm.sendSay("#face1#You... you think I'm useless, don't you? Just like everyone else... HIC! ")
sm.setParam(57)
sm.sendSay("#bThat's not what I think. I'm just concerned about your ability to keep watch if you're... ")
sm.setParam(37)
sm.sendSay("#face1#...Okay. Okay, I did, a little. HIC! But I can handle it! ")
sm.setParam(57)
sm.sendSay("#b...I see. Please return to your posting. ")
sm.setParam(37)
sm.sendNext("#face1#You... you don't really trust me, do you? HIC! You think I'm just rambling! ")
sm.sendSay("#face0#Right. Well, that's fine... No one listens to what I say anyways... ")
sm.sendSay("#face0#It doesn't matter... But! But, I really saw it with my own two eyes. ")
sm.sendSay("#face1#I mean, it was hard to see through the snow and fog... but I saw it! That giant shadow swept through the forest like it was swimming! ")
sm.sendSay("#face1#Of course, no one would want to believe that! But we must face reality, to be able to... prepare... ")
sm.setParam(57)
sm.sendSay("#bI also saw that shadow while I was coming down the mountain. But none of the villagers seemed to see it. I didn't ask everyone, but... ")
sm.sendSay("#bI was putting off asking people, honestly. I didn't want to stress anyone further by asking about giant monsters... ")
sm.sendSay("#bBut I have to do it, to learn as much as I can about what we're up against. ")
sm.setParam(37)
sm.sendSay("#face1#See? I don't lie.")
sm.createQuestWithQRValue(64020, "chk1=1;chk2=1")
sm.createQuestWithQRValue(64006, "WC=2;k1=0;k2=0;k3=0;k5=0;speed=20;man=199;prog=0;Pt=CaravanP2_chk4;Ec=5;max=20;weather=2;food=528")
