# id 2 (collision), field 867201760
sm.lockInGameUI(True, False)
sm.sendDelay(500)
sm.sendDelay(3000)
sm.forcedMove(True, 200)
sm.sendDelay(2000)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b(This may be too gross for Alika to hold onto.) ")
sm.sendDelay(250)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.forcedFlip(True)
sm.sendDelay(2000)
sm.forcedFlip(True)
sm.sendNext("#b(Maybe just use it for now.) ")
sm.forcedFlip(True)
sm.forcedMove(True, 100)
sm.createQuestWithQRValue(64084, "chk1=1")
sm.sendDelay(1000)
sm.lockInGameUI(False, True)
