# id 13 (q17640), field 865000000
sm.setSpeakerType(8)
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390211) # Kentucky
sm.sendNext("Welcome!")
sm.setParam(17)
sm.sendSay("I'm here for Leon Daniella's items.")
sm.setParam(5)
sm.sendSay("Aha, yes. Let me get everything together. This, and that, and this...")
sm.setParam(17)
sm.sendSay("(Ugh, there's so much junk.) Say, do you think I could have those delivered to the dock?")
sm.setParam(5)
sm.sendSay("Of course. I'll have them delivered right away.")
sm.setParam(17)
sm.sendSay("Great, thank you. (What the heck, they deliver?!)")
sm.setParam(57)
sm.setColor(1)
sm.sendSay("Hm? You..!")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9390204) # Robed Lady
sm.sendSay("Oh, it's you.")
sm.setParam(57)
sm.sendSay("What are you doing here? I hope you didn't forget you're still a wanted criminal?")
sm.setParam(37)
sm.sendSay("Hey, if I didn't save you that day, you wouldn't be standing here.")
sm.setParam(57)
sm.sendSay("Hm... Fine, you win. For now. I'll be going...")
sm.setParam(37)
sm.sendSay("Whoa, not so fast. Where are you headed?")
sm.setParam(57)
sm.sendSay("Time for some pirate-hunting. Why?")
sm.setParam(37)
sm.sendSay("No, it's nothing... Goodbye.")
sm.setParam(57)
sm.sendSay("Uh... Okay. I should head back to Leon.")
sm.createQuestWithQRValue(18418, "B=33264")
