package net.swordie.ms.handlers.header;

import net.swordie.ms.ServerConstants;
import net.swordie.ms.util.Util;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public enum InHeader {
    PONG(150),

    // Login ops
    CONNECT_CHAT(1),
    REDISPLAY_SERVER_LIST(7),
    GUILD_CHAT(19),
    FRIEND_CHAT(20),
    GUEST_LOGIN(22),
    TOS(29),
    VIEW_SERVER_LIST(33),
    VIEW_REGISTER_PIC(50),
    VIEW_SELECT_PIC(53),
    CLIENT_FAILED(57),
    PART_TIME_JOB(59),
    CHARACTER_CARD(60),
    ENABLE_LV50_CHAR(61),
    CREATE_LV50_CHAR(62),
    ENABLE_SPECIAL_CREATION(62),
    CREATE_SPECIAL_CHAR(65),

    DUMMY_CODE(100),
    BEGIN_SOCKET(101),
    SECURITY_PACKET(102),
    PERMISSION_REQUEST(103),
    LOGIN_BASIC_INFO(104), //v208
    CHECK_LOGIN_AUTH_INFO(105),
    VIEW_CHANNEL_REQUEST(106),
    SELECT_WORLD(107), // ~
    CHECK_SPW_REQUEST(108),
    CHAR_SELECT(109),
    CLIENT_LOADING_TIME_LOG(-1), // ?
    CHECK_SPW_EXIST_REQUEST(-1),
    MIGRATE_IN(111),
    SELECT_CHARACTER(113),
    SELECT_GO_TO_STAR_PLANET(114),
    SELECT_ACCOUNT(114),
    WORLD_INFO_REQUEST(115), //v208
    WORLD_INFO_FOR_SHINING_REQUEST(116),
    CHECK_DUPLICATE_ID(117),
    LOGOUT_WORLD(118),
    PERMISSION_REQUEST_FAKE(119),
    CHECK_LOGIN_AUTH_INFO_FAKE(120),
    CREATE_MAPLE_ACCOUNT_FAKE(121),
    SELECT_ACCOUNT_FAKE(122),
    SELECT_WORLD_FAKE(123),
    SELECT_CHARACTER_FAKE(124),
    CREATE_NEW_CHARACTER_FAKE(125),
    CREATE_NEW_CHARACTER(126),

    DELETE_CHARACTER(130), // v208
    RESERVED_DELETE_CHARACTER_CONFIRM(131),
    RESERVED_DELETE_CHARACTER_CANCEL(132),
    RENAME_CHARACTER(133),
    //    ALIVE_ACK_FAKE(133), // one of these is removed 199
    EXCEPTION_LOG(134),
    PRIVATE_SERVER_PACKET(135),
    RESET_LOGIN_STATE_ON_CHECK_OTP(999), //Update later
    CHANGE_SPW_REQUEST(137),
    CHECK_SOW_REQUEST_FAKE(138),
    CHECK_OTP_REQUEST(139),
    CHECK_DELETE_CHARACTER_OTP(140),
    CHECK_OTP_FOR_WEB_LAUNCHING_REQUEST(141),
    CREATE_SECURITY_HANDLE(142),
    ALBA_REQUEST(143),
    UPDATE_CHARACTER_CARD_REQUEST(144),
    ALIVE_ACK(155), // v210
    CLIENT_ERROR(158), // v210
    APPLY_HOTFIX(161), // v210
    SERVER_STATUS_REQUEST(162),
    WVS_SET_UP_STEP(163), // v210
    WVS_CRASH_CALLBACK(164),
    WORLD_LIST_REQUEST(187),
    LOGIN_AFTER_CHAR_CREATION(170),
    CHAR_POSITION_CHANGE(171), // v210
    WORLD_STATUS_REQUEST(176),
    USE_AUTH_SERVER(194),
    AUTH_FAILURE(195), // ?
    CHAR_SELECT_NO_PIC(193), // v210 but may crash
    CHANGE_PIC_REQUEST(-1), // v210


    B_E_G_I_N__U_S_E_R(204), // v210
    USER_TRANSFER_FIELD_REQUEST(205), // *
    USER_TRANSFER_CHANNEL_REQUEST(206),
    USER_TRANSFER_TO_HUB_REQUEST(-1),
    WORLD_TRANSFER_REQUEST(-1), // v210
    WORLD_TRANSFER_SHINNING_STAR_REQUEST(-1), // v210
    WORLD_TRANSFER_UNK(-1),
    USER_MIGRATE_TO_CASH_SHOP_REQUEST(210), // v214
    USER_MIGRATE_AUCTION_REQUEST(211), // v214
    USER_MIGRATE_TO_PVP_REQUEST(212), // v214
    PARTY_MIGRATE_TO_PVP_REQUEST(213), // v214
    USER_MIGRATE_TO_MONSTER_FARM(214), // v214
    USER_MIGRATE_TO_MONSTER_FARM_BY_INVITE_ITEM(215),
    USER_REQUEST_PVP_STATUS(216),
    USER_MIGRATE_TO_PVE_REQUEST(-1),
    USER_MOVE(218), // v214
    USER_SIT_REQUEST(219), // v210
    USER_PORTABLE_CHAIR_SIT_REQUEST(220),
    USER_EMOTICON_ITEM_USE_REQUEST(221),
    USER_DANCE_STOP_REQUEST(222),
    USER_MELEE_ATTACK(223),
    USER_SHOOT_ATTACK(224),
    USER_MAGIC_ATTACK(225),
    USER_BODY_ATTACK(226),
    USER_AREA_DOT_ATTACK(227),
    USER_AFFECTED_AREA_FOR_SCREEN_ATTACK(228),
    USER_HIT(230),
    //
    USER_CHAT(232),
    USER_ITEM_LINKED_CHAT(233),
    USER_A_D_BOARD_CLOSE(234),
    USER_EMOTION(235),
    ANDROID_EMOTION(236),
    USER_ACTIVATE_EFFECT_ITEM(237),
    USER_MONKEY_EFFECT_ITEM(238),
    USER_ACTIVATE_NICK_ITEM(239),
    USER_ACTIVATE_DAMAGE_SKIN(240),
    USER_ACTIVATE_DAMAGE_SKIN__PREMIUM(241),
    USER_DAMAGE_SKIN_SAVE_REQUEST(242),
    USER_DEFAULT_WING_ITEM(243),
    USER_KAISER_TRANSFORM_WING(244),
    USER_KAISER_TRANSFORM_TAIL(245),
    USER_UPGRADE_TOMB_EFFECT(246),
    USER_BAN_MAP_BY_MOB(247),
    USER_MONSTER_BOOK_SET_COVER(248),
    USER_SELECT_NPC(249), // v214
    USER_REMOTE_SHOP_OPEN_REQUEST(250),
    USER_SCRIPT_MESSAGE_ANSWER(251), // v210
    USER_SHOP_REQUEST(252),
    USER_TRUNK_REQUEST(253),
    USER_ENTRUSTED_SHOP_REQUEST(254),
    USER_STORE_BANK_REQUEST(255),
    USER_PARCEL_REQUEST(256),
    USER_EFFECT_LOCAL(257),
    USER_SPECIAL_EFFECT_LOCAL(258),
    USER_FINAL_ATTACK_REQUEST(259),
    USER_CREATE_AREA_DOT_REQUEST(261), // v214
    USER_CREATE_HOLIDOM_REQUEST(262), // v214
    REQ_MAKING_SKILL_EFF(263),
    SHOP_SCANNER_REQUEST(264),
    SHOP_LINK_REQUEST(265),
    AUCTION_REQUEST(266), // v214
    AUCTION_LEAVE_REQUEST(267), // v214
    ADMIN_SHOP_REQUEST(268), // v214
    USER_GATHER_ITEM_REQUEST(268), // v214
    USER_SORT_ITEM_REQUEST(269), // v214
    //
    USER_CHANGE_SLOT_POSITION_REQUEST(271), // v214
    USER_TEXT_EQUIP_INFO(272),
    USER_POP_OR_PUSH_BAG_ITEM_TO_INVEN(273),
    USER_BAG_TO_BAG_ITEM(274),
    USER_POUR_IN_BAG_TO_BAG(275),
    USER_STAT_CHANGE_ITEM_USE_REQUEST(276), // v214
    USER_STAT_CHANGE_ITEM_CANCEL_REQUEST(277), // v214
    USER_STAT_CHANGE_BY_PORTABLE_CHAIR_REQUEST(278),
    USER_MOB_SUMMON_ITEM_USE_REQUEST(279),// v214
    USER_PET_FOOD_ITEM_USE_REQUEST(280),// v214
    USER_TAMING_MOB_FOOD_ITEM_USE_REQUEST(281),// v214
    USER_SCRIPT_ITEM_USE_REQUEST(282),// v214
    USER_RECIPE_OPEN_ITEM_USE_REQUEST(283),// v214
    USER_CONSUME_CASH_ITEM_USE_REQUEST(284),// v214
    USER_ADDITIONAL_SLOT_EXTEND_ITEM_USE_REQUEST(285),// v214
    USER_CASH_PET_PICK_UP_ON_OFF_REQUEST(286),// v214
    USER_CASH_PET_SKILL_SETTING_REQUEST(287),// v214
    USER_OPTION_CHANGE_REQUEST(288),// v214
    USER_DESTROY_PET_ITEM_REQUEST(289),// v214
    USER_BRIDLE_ITEM_USE_REQUEST(290), // v214
    USER_SKILL_LEARN_ITEM_USE_REQUEST(290),
    USER_SKILL_RESET_ITEM_USE_REQUEST(-1),
    USER_ABILITY_RESET_ITEM_USE_REQUEST(-1),
    USER_ABILITY_CHANGE_ITEM_USE_REQUEST(-1),
    USER_EXP_CONSUME_ITEM_USE_REQUEST(-1),
    USER_MONSTER_LIFE_INVITE_ITEM_USE_REQUEST(-1),
    USER_EXP_ITEM_GET_REQUEST(-1),
    USER_CHAR_SLOT_INC_ITEM_USE_REQUEST(-1),
    USER_CHAR_RENAME_ITEM_USE_REQUEST(-1),
    USER_KAISER_COLOR_CHANGE_ITEM_USE_REQUEST(-1),
    USER_SHOP_SCANNER_ITEM_USE_REQUEST(-1),
    USER_MAP_TRANSFER_ITEM_USE_REQUEST(-1),
    USER_PORTAL_SCROLL_USE_REQUEST(303), // v214
    USER_FIELD_TRANSFER_REQUEST(304), // v214
    USER_UPGRADE_ITEM_USE_REQUEST(305),// v214
    USER_UPGRADE_ASSIST_ITEM_USE_REQUEST(306),// v214
    USER_HYPER_UPGRADE_ITEM_USE_REQUEST(307),// v214
    USER_EX_ITEM_UPGRADE_ITEM_USE_REQUEST(308), // v214
    USER_MEMORIAL_EX_UPGRADE_ITEM_USE_REQUEST(-1),
    USER_MEMORIAL_EX_UPGRADE_ITEM_OPTION_REQUEST(-1),
    USER_KARMA_CONSUME_ITEM_USE_REQUEST(-1),
    USER_EVENT_UPGRADE_ITEM_USE_REQUEST(-1),
    USER_ITEM_OPTION_UPGRADE_ITEM_USE_REQUEST(313), // v214
    USER_ADDITIONAL_OPT_UPGRADE_ITEM_USE_REQUEST(314),// v214
    USER_ITEM_SLOT_EXTEND_ITEM_USE_REQUEST(315),// v214
    USER_WEAPON_TEMP_ITEM_OPTION_REQUEST(316),// v214
    USER_ITEM_SKILL_SOCKET_UPGRADE_ITEM_USE_REQUEST(317),// v214
    USER_ITEM_SKILL_OPTION_UPGRADE_ITEM_USE_REQUEST(318),// v214
    USER_FREE_MIRACLE_CUBE_ITEM_USE_REQUEST(319),// v214
    USER_FREE_ADDITIONAL_CUBE_ITEM_USE_REQUEST(320),// v214
    USER_EQUIPMENT_ENCHANT_WITH_SINGLE_UI_REQUEST(321), // v214
    //322 Stats Reset Item?
    //323
    USER_ARCANE_SYMBOL_MERGE_REQUEST(324),// v214
    USER_UI_OPEN_ITEM_USE_REQUEST(325), // v214
    USER_BAG_ITEM_USE_REQUEST(326), // v214
    USER_ITEM_RELEASE_REQUEST(327), // v214
    USER_MEMORIAL_CUBE_OPTION_REQUEST(328),// v214
    USER_USE_NAVI_FLYING_SKILL_REQUEST(329),// v214
    USER_TOADS_HAMMER_REQUEST(-1),// v214
    USER_TOADS_HAMMER_HELP_REQUEST(-1),// v214
    USER_CHANGE_SOUL_COLLECTION_REQUEST(-1),// v214
    USER_SELECT_SOUL_SKILL_UP_REQUEST(-1),// v214
    USER_ABILITY_UP_REQUEST(336),// v214
    USER_ABILITY_MASS_UP_REQUEST(337),// v214
    USER_DOT_HEAL(338),// v214
    USER_CHANGE_STAT_REQUEST(339),// v214
    USER_CHANGE_STAT_REQUEST_BY_ITEM_OPTION(340),// v214
    SET_SON_OF_LINKED_SKILL_REQUEST(341),// v214
    UNLINK_SKILL_REQUEST(342),// v214
    LINK_SKILL_REQUEST(343),// v214
    USER_SKILL_UP_REQUEST(344),// v214
    USER_SKILL_USE_REQUEST(345), // v214
    // ?
    USER_SKILL_CANCEL_REQUEST(347),
    USER_SKILL_PREPARE_STOP(348),
    USER_SKILL_PREPARE_START(349),
    // TODO 345~350
    USER_SKILL_KEYDOWN_CHARGE_REQUEST(351),
    USER_DROP_MONEY_REQUEST(352), // v210
    USER_GIVE_POPULARITY_REQUEST(353),
    USER_PARTY_REQUEST(354),
    USER_CHARACTER_INFO_REQUEST(355),
    USER_ACTIVATE_PET_REQUEST(356),
    USER_REGISTER_PET_AUTO_BUFF_REQUEST(357),
    USER_TEMPORARY_STAT_UPDATE_REQUEST(358),
    USER_PORTAL_SCRIPT_REQUEST(359),
    USER_PORTAL_TELEPORT_REQUEST(360),
    USER_CALLING_TELEPORT_REQUEST(361),
    USER_MAP_TRANSFER_REQUEST(362),
    USER_ANTI_MACRO_ITEM_USE_REQUEST(363),
    USER_ANTI_MACRO_SKILL_USE_REQUEST(364),
    USER_ANTI_MACRO_REFRESH_REQUEST(365),
    //365?
    USER_CLAIM_REQUEST(-1), // ?
    USER_QUEST_REQUEST(368), // v214
    USER_MEDAL_REISSUE_REQUEST(-1),
    USER_CALC_DAMAGE_STAT_SET_REQUEST(-1),
    USER_B2_BODY_REQUEST(371),// v214
    USER_THROW_GRENADE(372),// v214
    USER_DESTROY_GRENADE(373),// v214
    USER_CREATE_AURA_BY_GRENADE(374),// v214
    USER_SET_MOVE_GRENADE(375),// v214
    USER_MACRO_SYS_DATA_MODIFIED(376),// v214
    USER_SELECT_NPC_ITEM_USE_REQUEST(-1),
    USER_LOTTERY_ITEM_USE_REQUEST(-1),
    USER_ROULETTE_START_REQUEST(-1),
    USER_ROULETTE_RESULT_REQUEST(-1),
    USER_ITEM_MAKE_REQUEST(-1),
    USER_REPAIR_DURABILITY_ALL(-1),
    USER_REPAIR_DURABILITY(-1),
    USER_QUEST_RECORD_SET_STATE(-1),
    USER_CLIENT_TIMER_END_REQUEST(-1),
    USER_CLIENT_RESOLUTION_RESULT(-1),
    USER_FOLLOW_CHARACTER_REQUEST(-1),
    USER_FOLLOW_CHARACTER_WITHDRAW(-1),
    USER_SELECT_PQ_REWARD(-1),
    USER_REQUEST_PQ_REWARD(-1),
    SET_PASSENGER_RESULT(-1),
    USER_REQUEST_INSTANCE_TABLE(391), // v214
    USER_REQUEST_CREATE_ITEM_POT(-1),
    USER_REQUEST_REMOVE_ITEM_POT(-1),
    USER_REQUEST_INC_ITEM_POT_LIFE_SATIETY(-1),
    USER_REQUEST_CURE_ITEM_POT_LIFE_SICK(-1),
    USER_REQUEST_COMPLATE_TO_ITEM_POT(-1),
    USER_REQUEST_RESPAWN(-1),
    //397 hair/face/skin for Androids?
    //398 hair/face/skin for Androids?
    //399 hair/face/skin for Androids?
    USER_FORCE_ATOM_COLLISION(401), // v214
    //402
    USER_LUCK_OF_THE_DRAW_FORCE_ATOM(-1),
    USER_UPDATE_PARTY_BUFF_AREA(405), // v214
    USER_DEBUFF_OBJ_COLLISION(-1),
    USER_UPDATE_LAPIDIFICATION(407),
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET(-1),
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_VALUE_SET(-1),
    USER_REQUEST_CHARACTER_POTENTIAL_SKILL_RAND_SET_UI(410),
    USER_REQUEST_OCCUMPATION_DATA(-1), // ?
    USER_REQUEST_ASWAN_TIME_TABLE_CLIENT_INIT(-1), // ?
    USER_PROTECT_BUFF_DIE_ITEM_REQUEST(413),
    USER_PROTECT_BUFF_DIE_MAPLE_POINT_REQUEST(-1),
    USER_PROTECT_EXP_DIE_MAPLE_POINT_REQUEST(-1),
    USER_KEY_DOWN_AREA_MOVING(-1), // v210
    USER_CHECK_WEDDING_EX_REQUEST(-1),
    USER_CATCH_DEBUFF_COLLISION(418), // v214
    USER_AFFECTED_AREA_CREATED(-1),
    USER_AFFECTED_AREA_REMOVED(-1),
    USER_DAZZLE_HIT(-1),
    USER_MESO_EXCHANGE_REQUEST(-1),
    //420 Group Chair Invite?
    //421
    //422 Group Chair Expel?
    //423 LP 441
    ZERO_TAG(426),// v214
    ZERO_SHARE_CASH_EQUIP_PART(427),// v214
    ZERO_LAST_ASSIST_STATE(-1),// v214
    USER_SHOOT_ATTACK_IN_FPS(-1),// v214
    USER_LUCKY_ITEM_USE_REQUEST(-1),// v214
    USER_MOB_MOVE_ABILITY_CHANGE(-1), // v214
    USER_DRAGON_ACTION(-1),// v214
    USER_DRAGON_BREATH_EARTH_EFFECT(-1),// v214
    USER_RENAME_REQUEST(434), // v214
    USER_RENAME_SPW_CHECK(435), // by UI 1110(NameChange)
    NOTICE_COMMAND(-1),// v214
    GROUP_MESSAGE(437),// v214
    ITEM_LINKED_GROUP_MESSAGE(438),// v214
    FIELD_UNIVERSE_MESSAGE(439),// v214
    WHISPER(440),
    MESSENGER(441),

    MINI_ROOM(443), //v214

    PARTY_REQUEST(445), // v214
    PARTY_RESULT(446),//v214
    PARTY_INVITABLE_SET(447), //v214
    EXPEDITION_REQUEST(448),//v214
    PARTY_ADVER_REQUEST(449),//v214
    URSUS_PARTY_REQUEST(450),//v214
    GUILD_REQUEST(451),//v214
    GUILD_RESULT(452),//v214
    GUILD_JOIN_REQUEST(453),//v214
    GUILD_JOIN_CANCEL_REQUEST(454),//v214
    GUILD_JOIN_ACCEPT(455),//v214
    GUILD_JOIN_REJECT(456),//v214
    GUILD_CONTENT_RANK_REQUEST(457),//v214
    TOWER_RANK_REQUEST(458),//v214
    ADMIN(459),//v214
    LOG(460),//v214
    LOG2(461),//v214
    //462 log for tremble? idk
    FRIEND_REQUEST(465),
    LOAD_ACCOUNT_ID_OF_CHARACTER_FRIEND_REQUEST(466),
    MEMO_REQUEST(467),
    MEMO_FLAG_REQUEST(468),
    //468
    ENTER_TOWN_PORTAL_REQUEST(470), // v214
    ENTER_RANDOM_PORTAL_REQUEST(472),
    ENTER_OPEN_GATE_REQUEST(473),
    SLIDE_REQUEST(474),
    //
    //
    FUNC_KEY_MAPPED_MODIFIED(476),
    R_P_S_GAME(-1),
    G_S_R_P_S_GAME(-1),
    STAR_PLANET__G_S_R_P_S_GAME(-1),
    G_S_R_P_S_FORCE_SELECT(-1),
    MARRIAGE_REQUEST(-1),
    WEDDING_WISH_LIST_REQUEST(-1),
    GUEST_BLESS(-1),
    BOOBY_TRAP_ALERT(-1),
    STALK_BEGIN(-1),
    ALLIANCE_REQUEST(486),
    ALLIANCE_RESULT(487),
    TALK_TO_TUTOR(488),
    TALK_TO_PARTNER(489),
    USER_SWITCH_R_P(490),
    REQUEST_INC_COMBO(491),
    REQUEST_DEC_COMBO(492),
    REQUEST_SET_BLESS_OF_DARKNESS(493),
    REQUEST_SET_HP_BASE_DAMAGE(494),
    DEMON_BLOOD_SPILL_REQUEST(495),
    XENON_CORE_OVERLOAD(496),
    SHADOW_SPEAR_REQUEST(497),
    MOB_CRC_KEY_CHANGED_REPLY(498),
    MOB_CRC_DATA_RESULT(499),
    MAKING_SKILL_REQUEST(500),// v214
    BROADCAST_EFFECT_TO_SPLIT(501),
    BROADCAST_ONE_TIME_ACTION_TO_SPLIT(502),
    BROADCAST_AFFECTED_EFFECT_TO_SPLIT(503),
    DEBUG_ONLY_COMMAND(504),
    MICRO_BUFF_END_TIME(505),
    REQUEST_SESSION_VALUE(506), // v210
    USER_TRANSFER_FREE_MARKET_REQUEST(507),
    USER_REQUEST_SET_STEAL_SKILL_SLOT(508),
    USER_REQUEST_STEAL_SKILL_MEMORY(509),
    USER_REQUEST_STEAL_SKILL_LIST(510),
    USER_REQUEST_STEAL_SKILL(511),
    RECALL_SUMMON(512),
    //508
    REWARD_MOB_LIST_REQUEST(514), // v210
    USER_LV_UP_GUIDE_NOTICE(516),
    RESET_CROSS_HUNTER_ALERT(517), // v210
    CROSS_HUNTER_COMPLETE_REQUEST(518), // v210
    CROSS_HUNTER_SHOP_REQUEST(519), // v210
    //514 cross hunter?
    //
    USER_EQUIP_SLOT_LEVEL_MINUS_ITEM_USE_REQUEST(-1), // v210
    BOARD_GAME_REQUEST(-1),
    USER_REQUEST_FLYING_SWORD_START(522), // v210
    BINGO_REQUEST(-1),
    BINGO_CASSANDRA_REQUEST(-1),
    ACTION_BAR_REQUEST(-1),
    USER_REQUEST_SET_OFF_TRINITY(-1),
    MESO_RANGER_REQUEST(-1),
    USER_REQUEST_SET_SMASH_COUNT(-1),
    USER_HYPER_SKILL_UP_REQUEST(529),// v214
    USER_HYPER_SKILL_RESET_REQUEST(530),// v214
    USER_HYPER_STAT_SKILL_UP_REQUEST(531), // v214
    USER_HYPER_STAT_SKILL_RESET_REQUEST(532), // v214
    USER_SET_DRESS_CHANGED_REQUEST(533), // v214
    ENTRY_RECORD_REQUEST(-1), // v214
    SET_MAX_GAUGE(-1),
    USER_RETURN_EFFECT_RESPONSE(-1),
    GET_SERVER_TIME(-1),
    GET_CHARACTER_POSITION(-1), // v210
    USER_REQUEST_CHANGE_MOB_ZONE_STATE(539), // v210
    EVOLVING_REQUEST(540), // v210
    USER_MIXER_REQUEST(-1), // v210
    SUMMON_EVENT_REWARD(-1), // v210
    MYSTIC_FIELD_MOVE(-1), // v210
    USER_JEWEL_CRAFT_REQUEST(-1), // v210
    VALUE_PACK_REQUEST(-1),
    WAIT_QUEUE_REQUEST(-1), // v210
    CHECK_TRICK_OR_TREAT_REQUEST(542), // v210
    //543
    MONSTER_FARM_MIGRATE_OUT_REQUEST(544), // v210?
    HALLOWEEN_CANDY_RANKING_REQUEST(545), // v210
    GET_REWARD_REQUEST(546),
    MAPLE_STYLE_BONUS_REQUEST(547),
    MAPLE_STYLE_ADVICE_REQUEST(548),
    MAPLE_STYLE_SET_SCORE_REQUEST(549),
    MENTORING(550),
    GET_LOTTERY_RESULT(551),
    ROOT_ABYSS_ENTER_REQUEST(552),
    USER_SET_ITEM_ACTION(553),
    USER_SET_BITS_CASE(554),
    USER_SET_BITS_SLOT(555),
    USER_ANTI_MACRO_QUESTION_RESULT(556),
    USER_PINKBEAN_ROLLING(557),
    USER_PINKBEAN_YO_YO_STACK(558),
    USER_QUICK_MOVE_SCRIPT(559),
    TIME_GATE_REQUEST(560),
    USER_SELECT_ANDROID(561),
    USER_COMPLETE_NPC_SPEECH(562),
    USER_COMPLETE_ANOTHER_USER_CHECK(563),
    USER_COMPLETE_COMBO_KILL_COUNT_CHECK(564),
    USER_COMPLETE_MULTI_KILL_COUNT_CHECK(565),
    USER_COMPLETE_MULTI_KILL_CHECK(566),
    USER_DAMAGE_FALLING_CHECK(567),
    USER_COMPLETE_PERSONAL_SHOP_BUY_CHECK(568),
    USER_DAILY_COMMITMENT_CHECK(569),
    USER_MOB_DROP_MESO_PICKUP(570),
    USER_BREAK_TIME_FIELD_ENTER(571),
    USER_RUN_ACT_QUEST(572),
    JOURNAL_AVATAR_REQUEST(573),
    REQUEST_EVENT_LIST(574), // v210
    USER_SIGN_REQUEST(575),
    ADD_ATTACK_RESET(576),
    SET_EVENT_NAME_TAG(577), // v210
    //578 Blaze Wizard? Fires of Creation
    //579 something in TryDoingForceAtomAttack_NonTarget
    SOMETHING_WITH_ABILITY_RESET(580),
    USER_AFFECTED_AREA_REMOVE_BY_TIME(581), // v210
    USER_AFFECTED_AREA_REMOVE_BY_REASON(582), // just a guess
    REQUEST_FREE_CHANGE_JOB(582), // v210
    LIBRARY_START_SCRIPT(584),
    CHANNEL_USER_COUNT_REQUEST(585), // v210
    UN_URSUS_SELECTED_SKILL_LIST(585),
    SOUL_DUNGEON_SYS(586), // v210
    USER_COORDINATION_CONTEST_REQUEST(587), // v210
    USER_SOUL_EFFECT_REQUEST(588),
    USER_SPIN_OFF_NEW_MODIFY_REQUEST(589),
    BLACK_LIST(590), // v210
    SKILL_HELPER_POPUP(591), // v210
    BLOCKBUSTER(592), // v210
    M_TALK_OFFLINE_ACCOUNT_FRIENDS_NAME_REQUEST(593), // ?
    CHARACTER_BURNING(593), // ?
    UPDATE_CHARACTER_SELECT_LIST(594), // ?
    DIRECT_GO_TO_FIELD(593),
    TRY_REGISTER_TELEPORT(594),
    USER_TOWER_CHAIR_SETTING(-1),
    BULLET_BARRAGE_DURATION_EXTENSION_REQUEST(602),
    USER_LAST_COLLECT_MONSTER_RESET(-1),
    END_OVER_HEAT(-1), // v210
    //599 summon?
    UNION_REQUEST(-1), // v210
    TRADE_KING_SHOP_REQ(-1), // v210
    TRADE_KING_SHOP_INFO_REQ(-1), // v210
    //603 3000
    //604 search?
    //605 int, int (UI 1178?)
    //606 int, int
    //607 int
    //608 int (605~608 are related)
    //609 APC?
    //610 APC?
    KEY_DOWN_SKILL_COST(617),
    //612
    //613
    //614 recv from FireAura, OverloadMode,...
    MATRIX_UPDATE_REQUEST(622), // v214
    //616
    //617
    //618 star event?
    MOD_SPECTRA_ENERGY(625),
    USER_REVIVE_REQUEST(627),
    GREATER_DARK_SERVANT_SWAP_REQUEST(628),
    //622
    INHUMAN_SPEED_FORCE_ATOM_REQUEST(630),
    //624
    CRYSTAL_SKILL_REQUEST(633), // v210
    //626~630
    //627 learned skill list?
    //631
    //632
    //633 related to 840~843?
    //634
    //635 int, int, short, short
    //636 Train? short, int
    //637 long

    B_E_G_I_N__P_E_T(646), // v214
    PET_MOVE(647),// v214
    PET_ACTION(648),// v214
    PET_INTERACTION_REQUEST(649),// v214
    PET_DROP_PICK_UP_REQUEST(650), // v214
    PET_STAT_CHANGE_ITEM_USE_REQUEST(651),// v214
    PET_UPDATE_EXCEPTION_LIST_REQUEST(652),// v214
    PET_FOOD_ITEM_USE_REQUEST(653),// v214
    PET_OPEN_SHOP(654),// v214
    E_N_D__P_E_T(655),// v214

    B_E_G_I_N__S_K_I_L_L_P_E_T(656),
    SKILL_PET_MOVE(657),
    SKILL_PET_ACTION(658),
    SKILL_PET_STATE(659),
    SKILL_PET_DROP_PICK_UP_REQUEST(660),
    SKILL_PET_UPDATE_EXCEPTION_LIST_REQUEST(661),
    E_N_D__S_K_I_L_L_P_E_T(662),

    B_E_G_I_N__S_U_M_M_O_N_E_D(663),
    SUMMONED_MOVE(664), // v214
    SUMMONED_ATTACK(665),// v214
    SUMMONED_HIT(666), // v214
    SUMMONED_SKILL(667), // v214
    SUMMONED_REMOVE(668),
    SUMMONED_ATTACK_PV_P(669),
    //662 int
    //663 Mighty Mascot(400051046)?
    //664
    SUMMONED_ACTION(673), // v214
    SUMMONED_ASSIST_ATTACK_DONE(674), // v214
    SUMMONED_SKILL_ATTACK(675),
    SUMMONED_SEQUENCE_ATTACK(676),
    //669 Mighty Mascot(400051046) or Elemental Fury(400021066) or Elemental Radiance (400021073)?
    //670 Mighty Mascot(400051046) or Elemental Fury(400021066)?
    E_N_D__S_U_M_M_O_N_E_D(-1),

    B_E_G_I_N__D_R_A_G_O_N(680),
    DRAGON_MOVE(681),
    DRAGON_GLIDE(682),
    E_N_D__D_R_A_G_O_N(683),

    B_E_G_I_N__A_N_D_R_O_I_D(684),
    ANDROID_MOVE(685),
    ANDROID_ACTISET(686),
    E_N_D__A_N_D_R_O_I_D(687),

    B_E_G_I_N__F_O_X_M_A_N(688),
    FOX_MAN_MOVE(689),
    FOX_MAN_ACTION_SET_USE_REQUEST(690),
    E_N_D__F_O_X_M_A_N(691),

    QUICKSLOT_KEY_MAPPED_MODIFIED(692),
    PASSIVE_SKILL_INFO_UPDATE(693),
    UPDATE_CLIENT_ENVIRONMENT(694),
    // 2 unk ops here?
    DIRECTION_NODE_COLLISION(697),
    USER_LASER_INFO_FOR_REMOTE(698),
    RETURN_TELEPORT_DEBUFF(-1),
    CHECK_PROCESS(-1),
    MEMO_IN_GAME_REQUEST(-1), // removed?
    EGO_EQUIP_GAUGE_COMPLETE_RETURN(-1), // v214
    EGO_EQUIP_CREATE_UPGRADE_ITEM(702), // v214
    EGO_EQUIP_CREATE_UPGRADE_ITEM_COST_REQUEST(703),// v214
    EGO_EQUIP_TALK_REQUEST(704),// v214
    EGO_EQUIP_CHECK_UPDATE_ITEM_REQUEST(705), // v214
    INHERITANCE_INFO_REQUEST(706),// v214
    INHERITANCE_UPGRADE_REQUEST(707), // v214
    MIRROR_READING_SELECT_BOOK_REQUEST(-1), // v214
    LIKE_POINT(-1), // v214
    USER10TH_STREAMING_URL_REQUEST(-1), // v214
    //
    USER_UPDATE_MAPLE_TV_SHOW_TIME(-1), // v214
    REDUCE_DOT_DAMAGE_BASE_BUFF_REQUEST(-1),
    MIRROR_STUDY_COMPLETE(-1),
    REQUEST_ARROW_PLATTER_OBJ(715),
    USER_TIME_EVENT_UI_OPEN_REQUEST(-1),
    USER_TIME_EVENT_RESULT_REQUEST(-1),
    USER_TIME_EVENT_COMPLETE_REQUEST(-1),
    USER_TIME_EVENT_PASSED_TIME_SET(-1),
    INVASION_SETTING_REQUEST(-1), // v210
    USER_FIELD_ATTACK_OBJ_REQUEST_BOARDING(-1), // v210
    USER_FIELD_ATTACK_OBJ_REQUEST_GET_OFF(-1), // v210
    //MONSTER_BATTLE(714),
    UI_SCRIPT_REQUEST(722), // could be removed?
    BOSS_ARENA_MATCH_REQUEST(-1),
    BOSS_ARENA_MIGRATE_REQUEST(-1),
    MOB_USER_CONTROL_SKILL_Q_PUSH(-1),
    MOB_USER_CONTROL_SKILL_Q_POP(-1),
    MOB_USER_CONTROL_SKILL_FORCED_Q_POP(-1),
    PARTY_QUEST_RANKING_REQUEST(-1),
    ATTENDANCE_EVENT(-1), // v210
    ATTENDANCE_EVENT_REWARD_REQ(-1), // v210
    //723
    //724
    UI_ATTENDANCE_GHOST_CHANGE_REQ(-1), // could be wrong
    EVENT_UI_REQ(-1), // v210
    //727
    ATTENDANCE_EVENT_SELECT_REWARD(-1),
    USER_SET_CUSTOMIZE_EFFECT(-1),
    USER_CUSTOMIZE_EFFECT_ITEM_MODIFY(-1),
    USER_GROWTH_HELPER_REQUEST(739),// v214
    USER_CONTENTS_MAP_REQUEST(740), // v214
    USER_TIMER_REQ(-1), // v210
    //734
    USER_MANNEQUIN(-1), // ?
    //736
    USER_BUFFER_FLY_REQ(-1),
    USER_NON_TARGET_FORCE_ATOM_ATTACK(746), // v214
    USER_RUN_SCRIPT(-1), // v210
    CHECK_BOSS_PARTY_BY_SCRIPT(-1), // v210
    //741
    SET_GO_TO_SHINE_CITY_WAIT_FIELD(-1),
    SET_STAR_PLANET_MINI_GAME_CUSTOMIZING_OPTION(-1),
    STAR_PLANET_TREND_SHOP_SET_AVATAR(-1),
    STAR_PLANET_TREND_SHOP_RESTORE_AVATAR(-1),
    STAR_PLANET_REQUEST(-1),
    STAR_PLANET_MATCHING_REENTRANCE(-1),
    STAR_PLANET_RESULT_UI_EXIT_SCRIPT(-1), // v210
    MOVE_TO_BOSS_MATCHING_FIELD(-1),
    //749 Close UI 1230
    //750 Close UI 1233
    //751 Close UI 1246
    MOVE_TO_URSUS_WAITING_FIELD(-1), // v210?
    MONSTER_COLLECTION_COMPLETE_REWARD_REQ(-1), // v210
    MONSTER_COLLECTION_EXPLORE_REQ(-1), // v210
    PLAT_FORMAR_ENTER_REQUEST(-1),
    STIGMA_DELIVERY_REQUEST(-1), // v210
    UNION_RAID_RETREAT(-1), // TODO this might be one from 749~751
    //757 slot / maxCorruption / slotHeight / slotWidth / alarmTime
    //758
    //759 Dream Breaker Update Request?
    //760 used by some extended fields?

    B_E_G_I_N__E_V_E_N_T__G_R_O_U_P(-1),
    INVITATION_ACCEPT_USER(-1),
    INVITATION_CANCEL_USER(-1),
    EVENT_GROUP_LEAVE(-1),
    B_E_G_I_N__E_V_E_N_T__G_R_O_U_P__P_A_C_K_E_T(-1),
    E_N_D__E_V_E_N_T__G_R_O_U_P__P_A_C_K_E_T(-1),
    E_N_D__E_V_E_N_T__G_R_O_U_P(-1),

    B_E_G_I_N__E_V_E_N_T__R_A_N_K_I_N_G(-1),
    EVENT_RANKING_OPEN(-1),
    EVENT_RANKING_HELP(-1),
    E_N_D__E_V_E_N_T__R_A_N_K_I_N_G(-1),

    B_E_G_I_N__S_T_A_R_P_L_A_N_E_T__M_A_T_C_H_I_N_G(-1),
    STAR_PLANET_MATCHING__REGISTER_REQ(-1),
    STAR_PLANET_MATCHING__UN_REGISTER_REQ(-1),
    STAR_PLANET_MATCHING__REGISTER_PARTY_REQ(-1),
    STAR_PLANET_MATCHING__JOIN_PARTY_PLAY_REQ(-1),
    STAR_PLANET_MATCHING__TRANSFER_ASSENT(-1),
    STAR_PLANET_MATCHING__HELP_SCRIPT(-1),
    E_N_D__S_T_A_R_P_L_A_N_E_T__M_A_T_C_H_I_N_G(-1),

    B_E_G_I_N__S_T_A_R_P_L_A_N_E_T__Q_U_E_U_E(-1),
    STAR_PLANET_QUEUE__REGISTER_REQ(-1),
    STAR_PLANET_QUEUE__UN_REGISTER_REQ(-1),
    E_N_D__S_T_A_R_P_L_A_N_E_T__Q_U_E_U_E(-1),

    B_E_G_I_N__S_T_A_R_P_L_A_N_E_T__I_N_V_I_T_A_T_I_O_N(-1),
    STAR_PLANET_INVITATION_ACCEPT(-1),
    STAR_PLANET_INVITATION_CANCEL(-1),
    E_N_D__S_T_A_R_P_L_A_N_E_T__I_N_V_I_T_A_T_I_O_N(-1),

    USER_SURVEY_REQUEST(-1),
    NPS_INFO(-1), // v210
    USER_FLAME_ORB_REQUEST(798), // v214
    USER__SAD_RESULT_UI__CLOSE(-1),
    FREE_LOOK_CHANGE_REQUEST(-1),
    FREE_LOOK_CHANGE_UI_OPEN_FAILED(-1),
    USER_SMART_PHONE_CALL_REQUEST(-1),
    USER_JAGUAR_CHANGE_REQUEST(804), // v214
    FPS_LOG(-1),
    PACKET_MODIFY_LOG(-1),
    //798 Skeleton?
    BATTLE_USER_AVATAR_SELECT(-1),
    BATTLE_USER_ATTACK(-1),
    BATTLE_USER_ATTACK_EXPIRE(-1),
    BATTLE_USER_ATTACK_POSITION(-1),
    BATTLE_USER_HIT(-1),
    BATTLE_USER_HIT_BY_MOB(-1),
    BATTLE_STAT_CORE_REQUEST(-1),
    BATTLE_USER_ALIVE(-1),
    USER_CONTENTS_BOOK_REQUEST(-1),
    //808 Reading?
    //809 UI 1175?
    //810
    PERFORMANCE_CLIENT_LOGIN(-1),
    PERFORMANCE_CLIENT_IN_FIELD(-1),
    PING_CHECK_REQUEST__CLIENT_TO_GAME(-1),
    PING__CLIENT_TO_GAME(-1),
    //815
    PLANT_POT_CLICK(-1),
    //817
    RANDOM_MISSION_REQUEST(-1),
    ITEM_COLLECTION_SET_FLAG(-1),
    ITEM_COLLECTION_CHECK_COMPLETE(-1),
    SELF_STAT_CHANGE_REQUEST(-1),
    CASH_BUFF_EVENT_CANCEL(-1),
    CREATE_PSYCHIC_LOCK(832),
    RESET_PATH_PSYCHIC_LOCK(833),
    RELEASE_PSYCHIC_LOCK(834),
    RESERVE_DAMAGE_PSYCHIC_LOCK(-1),
    CREATE_KINESIS_PSYCHIC_AREA(836),
    DO_ACTIVE_PSYCHIC_AREA(837),
    DEBUFF_PSYCHIC_AREA(838),
    RELEASE_PSYCHIC_AREA(839),
    // 400021008?
    PSYCHIC_OVER_REQUEST(-1),
    DEC_PSYCHIC_POINT_REQUEST(-1),
    TOUCH_ME_END_REQUEST(-1),
    BITE_ATTACK_RESPONSE(-1),
    URSUS_SHOP_REQUEST(-1),
    URSUS_PARTY_MEMBER_LIST(-1),
    USER_KEY_DOWN_STEP_REQUEST(847),
    DAILY_GIFT_REQUEST(848),
    SKILL_COMMAND_LOCK_ARAN(849), // v210 not only Aran but also HoYoung or...
    SKILL_COMMAND_LOCK_ARK(850),
    BEAST_FORM_WING_OFF(851),
    SKILL_COMMAND_LOCK_EVENT(-1), // like determination skill
    RESET_AIR_HIT_COUNT_REQUEST(-1),
    RW_ACTION_CANCEL(-1),
    RELEASE_RW_GRAB(-1),
    RW_CLEAR_CURRENT_ATTACK_REQUEST(-1),
    RW_MULTI_CHARGE_CANCEL_REQUEST(857),
    FUNCTION_FOOTHOLD_MAN(-1),
    DIMENSIONAL_MIRROR_WARP_REQUEST(859), // v214
    //851
    //852
    //853
    //854
    SHOOT_OBJECT_CREATE_REQUEST(864), // v214
    //856
    SHOOT_OBJECT_EXPLODE_REQUEST(866), // 214
    //858
    //859
    //860
    //861 ZodiacEvent?
    LOADED_DICE_SELECTION_RESULT(871),
    SERPENT_VORTEX_INCREMENT_REQUEST(872),
    //864~865
    //
    SPOTLIGHT_STACK_REQUEST(875),
    UNION_ASSIGN_REQUEST(876), // v210
    //868
    //869 CustomVehicle?
    //870 Android error?
    UNION_PRESET_CHANGE(880), // v210
    UNION_PRESET_INFO_REQUEST(881), // v210
    EXTRACT_SOUL(-1),
    STEP_UP_UI_REWARD_REQUEST(-1), // ? (UI 1160)
    STEP_UP_UI_REQUEST(-1),
    //876 TODO (UI 1156)
    //877
    USER_TELEPORT_ROCK_ALLOWED_SETTING_REQUEST(-1), // ? TODO
    //879
    ACHIEVEMENT_REQUEST(889), // ?
    //881
    //882
    //883
    //884
    //885
    //886
    //887 Attendance check?
    //888
    //889 2nd pwd check?
    INCREASE_SKILL_STACK_REQUEST(890), // by Solus (CTS555 v210)
    //891
    DIVINE_ECHO_EXPIRE_REQUEST(892),
    //893
    //894
    DIMENSIONAL_SWORD_CHANGE(894), // v210?
    //895
    //896
    //897
    INFERNO_SPHERE_FEATHER_COUNT(888), // v210?
    //900 Tactical Relay? (UI 1209)
    //901
    //902
    //903 WildHunter's Primal Grenade (400031032)
    //904 Blaster's Bullet Blast (400011091)
    //905
    //906 could be Alliance Skill? (UI 1200)
    //907 TODO (UI 1206)
    //908
    //909
    MAPLE_SQUAD_SWITCH_CHARACTER(-1),
    MAPLE_SQUAD_UNK1(-1),
    MAPLE_SQUAD_UNK2(-1),
    MAPLE_SQUAD_UNK3(-1), // from UI 1224?
    MAPLE_SQUAD_REQUEST(-1),
    MAPLE_SQUAD_UNK4(-1),
    MAPLE_SQUAD_SELECT_CHARACTER(-1),
    //917 DemonAvenger's Demonic Blast (400011038)
    //918
    //919 LP 2007, UI 1220?
    //920 LP 2007, UI 1220?
    //921
    //922 questEx 100179, "eTime"? (UI 1214)
    //923 BattleUserRespawn? (LP 1723)
    TRANSFER_HAMMER_REQUEST(-1), // v210
    //925
    //926 Sealed Rune Power
    //927
    //928 "can't complete anymore" "Not enough Maple Points"
    //929 "Pirate Blessing has been applied"
    //930
    //931
    //932 Monster Book?
    //933 Monster Book?
    //934 Monster Book?
    //935 Monster Book? (LP 491?)
    MONSTER_BOOK_MOB_INFO(935), // ?
    //936 LegendAward?
    GACHAPON_REQUEST(937), // v210

    NEBULITE_INSERT_REQUEST(917),
    SOCKET_CREATE_REQUEST(918),

    FAMILIAR_ADD_REQUEST(954), // v210 (+10?)
    FAMILIAR_SPAWN_REQUEST(-1),
    FAMILIAR_RENAME_REQUEST(-1),


    // Beast Tamer
    BEAST_TAMER_REGROUP_REQUEST(898),


    GUILD_BBS(951), // v208

    SURPRISE_BOX(977), // v214

    VIOLET_CUBE_REQUEST(982), // v210 (+9)

    SALON_QUERY(998), // v210 (+9)

    FAMILIAR_MOVE(-1),
    FAMILIAR_ACTION(-1),
    FAMILIAR_ATTACK(-1),
    FAMILIAR_SKILL(-1),

    SLASH_COMMAND(-1),

    E_N_D__U_S_E_R(1017),

    B_E_G_I_N__F_I_E_L_D(1017),
    B_E_G_I_N__L_I_F_E_P_O_O_L(-1),


    B_E_G_I_N__M_O_B(1049),// v214
    MOB_MOVE(1050), // v214
    MOB_APPLY_CTRL(1051),// v214
    MOB_DROP_PICK_UP_REQUEST(1052),// v214
    MOB_HIT_BY_OBSTACLE(1053),// v214
    MOB_HIT_BY_OBSTACLE_ATOM(1054),// v214
    MOB_HIT_BY_MOB(1055),// v214

    MOB_SELF_DESTRUCT(1056), // v214
    MOB_SELF_DESTRUCT_COLLISION_GROUP(1057), // v214
    MOB_ATTACK_MOB(1058),// v214
    MOB_SKILL_DELAY_END(1059),// v214
    MOB_TIME_BOMB_END(1060),// v214
    MOB_ESCORT_COLLISION(1061),// v214
    MOB_REQUEST_ESCORT_INFO(1062),// v214
    MOB_ESCORT_STOP_END_REQUEST(1063),// v214
    MOB_AREA_ATTACK_DISEASE(1064),// v214
    MOB_EXPLOSION_START(1065),// v214
    MOB_LIFTING_END(1066),// v214
    MOB_UPDATE_FIXED_MOVE_DIR(1067),// v214
    MOB_CREATE_FIRE_WALK(1068),// v214
    MOB_AFTER_DEAD_REQUEST(1069),// v214

    MOB_DAMAGE_SHARE_INFO(1071),// v214
    MOB_CREATE_AFFECTED_AREA(1072),// v214
    MOB_DOWN_RESPONSE(1073),// v214
    E_N_D__M_O_B(1074),// v214

    B_E_G_I_N__N_P_C(1086),// v214
    NPC_MOVE(1087),// v214
    NPC_SPECIAL_ACTION(1088),// v214
    E_N_D__N_P_C(1089),// v214
    E_N_D__L_I_F_E_P_O_O_L(1090),// v214

    B_E_G_I_N__D_R_O_P_P_O_O_L(1091),// v214
    DROP_PICK_UP_REQUEST(1092), // v214
    E_N_D__D_R_O_P_P_O_O_L(1093),// v214

    B_E_G_I_N__R_E_A_C_T_O_R_P_O_O_L(-1),// v214
    REACTOR_HIT(1095),// v214
    REACTOR_CLICK(1096),// v214
    REACTOR_RECT_IN_MOB(1097),// v214
    REACTOR_UNK203_1047(1098),// v214
    REACTOR_KEY(1099),// v214
    E_N_D__R_E_A_C_T_O_R_P_O_O_L(-1),// v214

    B_E_G_I_N__F_I_S_H_I_N_G_Z_O_N_E_P_O_O_L(-1),
    FISHING_INFO(-1),
    FISHING_END(-1),
    E_N_D__F_I_S_H_I_N_G_Z_O_N_E_P_O_O_L(-1),

    B_E_G_I_N__P_E_R_S_O_N_A_L__O_B_J_E_C_T(-1),
    DECOMPOSER_REQUEST(-1),
    E_N_D__P_E_R_S_O_N_A_L__O_B_J_E_C_T(-1),

    B_E_G_I_N__E_V_E_N_T__F_I_E_L_D(-1),
    EVENT_START(-1),
    SNOW_BALL_HIT(-1),
    SNOW_BALL_TOUCH(-1),
    COCONUT_HIT(-1),
    TOURNAMENT_MATCH_TABLE(-1),
    PULLEY_HIT(-1),
    E_N_D__E_V_E_N_T__F_I_E_L_D(-1),

    B_E_G_I_N__M_O_N_S_T_E_R__C_A_R_N_I_V_A_L__F_I_E_L_D(-1),
    M_CARNIVAL_REQUEST(-1),
    E_N_D__M_O_N_S_T_E_R__C_A_R_N_I_V_A_L__F_I_E_L_D(-1),

    B_E_G_I_N__D_E_F_E_N_S_E__F_I_E_L_D(-1),
    DEFENSE_GAME_REQUEST(-1),
    E_N_D__D_E_F_E_N_S_E__F_I_E_L_D(-1),

    C_O_N_T_I_S_T_A_T_E(1136),// v214
    B_E_G_I_N__P_A_R_T_Y__M_A_T_C_H(1137),// v214
    INVITE_PARTY_MATCH(1138),// v214
    CANCEL_INVITE_PARTY_MATCH(1139),// v214
    PARTY_MEMBER_CANDIDATE_REQUEST(1140),// v214
    URSUS_PARTY_MEMBER_CANDIDATE_REQUEST(1141),// v214
    PARTY_CANDIDATE_REQUEST(1142),// v214
    INTRUSION_FRIEND_CANDIDATE_REQUEST(-1),// v214
    INTRUSION_LOBBY_CANDIDATE_REQUEST(-1),// v214
    END_PARTY_MATCH(-1),// v214
    REQUEST_FOOT_HOLD_MOVE(-1), // v214
    GATHER_REQUEST(1036),
    RUNE_STONE_SKILL_REQ(1148),
    GATHER_END_NOTICE(1149),
    ACT_CHANGE_REACTOR_USE_REQUST(1150),
    USER_ANTI_MACRO_BOMB_REQUEST(1151),
    MAKE_ENTER_FIELD_PACKET_FOR_QUICK_MOVE(1152),
    RUNE_STONE_USE_REQ(1153),
    RUNE_STONE_USE_RES(1154),
    RUNE_STONE_USE_CHK(1155),
    OBSTACLE_ATOM_COLLISION(-1),
    TIMER_GAUGE_TIMEOUT(-1),
    FALLING_CATCHER_HACK_CHECK(-1),
    COOK_GAME_REQUEST(-1),
    FPS_MODE_EXIT_REQUEST(-1),
    MAKE_ENTER_FIELD_PACKET_FOR_MIRROR_DUNGEON(-1),
    LEAVE_MIRROR_DUNGEON(-1),
    PEACEMAKER_TRAVEL_CONTACT_COUNT(1163),
    PEACEMAKER_EXPLOSION_CONTACT_COUNT(-1),
    ILLIUM_RESONANCE_LINK(-1),

    // TODO
    B_E_G_I_N__R_H_Y_T_H_M_G_A_M_E(-1),
    RHYTHM_GAME_HIT_NOTE(-1),
    RHYTHM_GAME_START_REGION(-1),
    RHYTHM_GAME_END_REGION(-1),
    RHYTHM_GAME_END_SPECIAL_ATTACK(-1),

    RHYTHM_GAME_SELECT_MODE(-1),
    RHYTHM_GAME_ATTACK_REQUEST(-1),
    RHYTHM_GAME_NPC_ACTION_REQUEST(-1),
    RHYTHM_GAME_EXIT_GAME(-1),
    E_N_D__R_H_Y_T_H_M_G_A_M_E(-1),

    B_E_G_I_N__M_O_U_N_T_A_I_N_R_I_D_I_N_G(-1),
    MOUNTAIN_RIDING_HP_INFO(-1),
    MOUNTAIN_RIDING_MOB_INFO(-1),
    E_N_D__M_O_U_N_T_A_I_N_R_I_D_I_N_G(-1),

    B_E_G_I_N__P_I_R_A_N_H_A(-1),
    PIRANHA_INFO(-1),
    PIRANHA_DIE(-1),
    PIRANHA_DAMAGE(-1),
    PIRANHA_PREPARE(-1),
    E_N_D__P_I_R_A_N_H_A(-1),

    B_E_G_I_N__R_O_B_B_I_N_S(-1),
    ROBBINS__INC_BOMB(-1),
    ROBBINS__DEC_BOMB(-1),
    ROBBINS__TOSS_BOMB(-1),
    E_N_D__R_O_B_B_I_N_S(-1),

    B_E_G_I_N__F_A_L_L_I_N_G_S_T_O_N_E(-1),
    FALLING_STONE_INFO(-1),
    FALLING_STONE_HP_INFO(-1),
    FALLING_STONE_PREPARE(-1),
    E_N_D__F_A_L_L_I_N_G_S_T_O_N_E(-1),

    B_E_G_I_N__B_A_T_T_L_E_F_I_E_L_D(-1),
    BATTLE_FIELD_DAMAGE(-1),
    BATTLE_FIELD_SHEEP_REVIVAL_REQ(-1),
    BATTLE_FIELD_SHEEP_REVIVE(-1),
    E_N_D__B_A_T_T_L_E_F_I_E_L_D(-1),

    B_E_G_I_N__B_O_S_S_A_R_E_N_A(-1),
    BOSS_ARENA_SELECT_BOSS(-1),
    BOSS_ARENA_SELECT_SKILL(-1),
    BOSS_ARENA_SELECT_DIFFICULTY(-1),
    BOSS_ARENA_SELECT_CONFIRM(-1),
    E_N_D__B_O_S_S_A_R_E_N_A(-1),

    B_E_G_I_N__C_A_T_A_P_U_L_T(-1),
    CATAPULT__UPGRADE_SKILL(-1),
    E_N_D__C_A_T_A_P_U_L_T(-1),

    FIELD_ATTACK_OBJ_PUSH_ACT(-1),
    FIELD_RESPAWN(-1),
    B_E_G_I_N__S_O_U_L__D_U_N_G_E_O_N(-1),
    SOUL_ITEM_USE(-1),
    SOUL_ITEM_USE_VOTE(-1),
    SOUL_DUNGEON_SUMM_SOUL_BOSS(-1),
    E_N_D__S_O_U_L__D_U_N_G_E_O_N(-1),

    B_E_G_I_N__S_P_A_C_E_M_O_O_N_R_A_B_B_I_T(-1),
    SPACE_MOON_RABBIT_HIT_EFF(-1),
    SPACE_MOON_RABBIT_DAMAGE(-1),
    E_N_D__S_P_A_C_E_M_O_O_N_R_A_B_B_I_T(-1),

    B_E_G_I_N__H_U_N_D_R_E_D_B_I_N_G_O(-1),
    H_BINGO_CHECK_NUMBER(-1),
    H_BINGO_CHECK_BINGO(-1),
    E_N_D__H_U_N_D_R_E_D_B_I_N_G_O(-1),

    B_E_G_I_N__T_Y_P_I_N_G_G_A_M_E(-1),
    TYPING_GAME_CHECK_MSG(-1),
    TYPING_GAME_WORD_MOB_ATTACK(-1),
    TYPING_GAME_LEVEL_SELECT(-1),
    TYPING_GAME_SKILL_ATTACK(-1),
    TYPING_GAME_FIELD_OUT(-1),
    E_N_D__T_Y_P_I_N_G_G_A_M_E(-1),

    B_E_G_I_N__H_U_N_D_R_E_D_O_X_Q_UI_Z(-1),
    H_OX_QUIZ_SELECTED(-1),
    E_N_D__H_U_N_D_R_E_D_O_X_Q_UI_Z(-1),

    B_E_G_I_N__S_T_A_R_P_L_A_N_E_T_R_P_S(-1),
    S_P_RPS_GAME_USER_SELECT(-1),
    S_P_RPS_GAME_ANSWER(-1),
    S_P_RPS_GAME_LEAVE(-1),
    E_N_D__S_T_A_R_P_L_A_N_E_T_R_P_S(-1),

    B_E_G_I_N__S_I_D_E_S_C_R_O_L_L_F_L_Y_S_H_O_O_T_I_N_G(-1),
    SSFS_HIT_USER(-1),
    SSFS_LETHAL_ATTACK(-1),
    SSFS_EXIT(-1),
    E_N_D__S_I_D_E_S_C_R_O_L_L_F_L_Y_S_H_O_O_T_I_N_G(-1),

    B_E_G_I_N__F_I_E_L_D_S_T_A_T_E(-1),
    STAR_PLANET__H_BINGO_CHECK_NUMBER(-1),
    STAR_PLANET__H_BINGO_CHECK_BINGO(-1),
    STAR_PLANET__H_BINGO_SEND_NUMBER(-1),
    STAR_PLANET__H_RPS_SELECTED(-1),
    STAR_PLANET__GROUP_DANCE_SELECTED(-1), // v208
    STAR_PLANET__GROUP_DANCE_CANCEL(-1),
    E_N_D__F_I_E_L_D_S_T_A_T_E(-1),

    //B_E_G_I_N__M_O_M_E_N_T_S_W_I_M_A_R_E_A(1251),
    MOMENT_SWIM_AREA__WATER_LEVEL(-1), //?
    MOB_CONVEX_SKILL_AREA_REQUEST(-1), //v208
    //E_N_D__M_O_M_E_N_T_S_W_I_M_A_R_E_A(1253),

    B_E_G_I_N__G_H_O_S_T_P_A_R_K(-1),
    GHOST_PARK_USE_RUNE_REQ(-1), //v208
    GHOST_PARK_RUNE_HEAL_REQ(-1), //v208
    GHOST_PARK_HIT_BULLET(-1), //v208
    E_N_D__G_H_O_S_T_P_A_R_K(-1),

    B_E_G_I_N__F_I_E_L_D__U_R_U_S(-1),
    URSUS_SAVE_DEADLY_USER(-1),
    E_N_D__F_I_E_L_D__U_R_U_S(-1),

    FIELD_SKILL_USE_REQUEST(-1),
    FIELD_WEATHER__MSG(-1),
    FIELD_STAT_Q_R_EX_DAY(-1),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_B_O_U_N_T_Y_H_U_N_T_I_N_G(-1),
    POLO_FRITO_BOUNTY_HUNTING_REQUEST(-1),
    E_N_D__P_O_L_O_F_R_I_T_O_B_O_U_N_T_Y_H_U_N_T_I_N_G(-1),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_T_O_W_N_D_E_F_E_N_S_E(-1),
    POLO_FRITO_TOWN_DEFENSE_REQUEST(-1),
    E_N_D__P_O_L_O_F_R_I_T_O_T_O_W_N_D_E_F_E_N_S_E(-1),

    B_E_G_I_N__P_O_L_O_F_R_I_T_O_C_O_U_R_T_S_H_I_P_D_A_N_C_E(-1),
    POLO_FRITO_COURTSHIP_DANCE_RESULT(-1),
    E_N_D__P_O_L_O_F_R_I_T_O_C_O_U_R_T_S_H_I_P_D_A_N_C_E(-1),

    B_E_G_I_N__B_O_S_S__D_E_M_I_A_N__F_L_Y_I_N_G_S_W_O_R_D(-1),
    DEMIAN_OBJECT_MAKE_ENTER_ACK(-1),
    DEMIAN_OBJECT_NODE_END(-1),
    DEMIAN_OBJECT_ERR__RECREATE(-1),
    E_N_D__B_O_S_S__D_E_M_I_A_N__F_L_Y_I_N_G_S_W_O_R_D(-1),
    B_E_G_I_N__B_O_S_S__L_U_C_I_D(-1),
    LUCID_FAIRY_DUST_CHECK(-1), // v210
    LUCID_ACTIVATE_STATUE_REQUEST(-1), // v210
    LUCID_WELCOME_BARRAGE_END(-1), // v210
    E_N_D__B_O_S_S__L_U_C_I_D(-1),
    E_N_D__F_I_E_L_D(-1),

    CHECK_S_P_W_CREATE_NEW_CHARACTER(-1),
    SET_S_P_W(-1),

    B_E_G_I_N__B_L_A_C_K__M_A_G_E(-1),
    BLACK_MAGE_ORB_HIT(-1),
    E_N_D__B_L_A_C_K__M_A_G_E(-1),

    GOLLUX_MINI_MAP_LEAVE_REQUEST(-1), //v208.3

    SECOND_ATOM_REMOVE_REQUEST(1416),

    B_E_G_I_N__C_A_S_H_S_H_O_P(-1),
    CASH_SHOP_CHARGE_PARAM_REQUEST(-1),
    CASH_SHOP_QUERY_CASH_REQUEST(-1),
    CASH_SHOP_CASH_ITEM_REQUEST(-1),
    CASH_SHOP_CHECK_COUPON_REQUEST(-1),
    CASH_SHOP_MEMBER_SHOP_REQUEST(-1),
    CASH_SHOP_GIFT_MATE_INFO_REQUEST(-1),
    CASH_SHOP_SEARCH_LOG(-1),
    CASH_SHOP_COODINATION_REQUEST(-1), // v210
    CASH_SHOP_CHECK_MILEAGE_REQUEST(-1),
    //1450?
    CASH_SHOP_NAVER_USAGE_INFO_REQUEST(-1), // ?
    M_V_P__DAILY_PACK__REQUEST(-1), // v210
    M_V_P__SPECIAL_PACK__REQUEST(-1), // v210
    CASH_SHOP_ACTION(-1),
    CASH_SHOP_BUTTON_PRESS(-1),
    //1456?
    E_N_D__C_A_S_H_S_H_O_P(-1),

    B_E_G_I_N__R_A_I_S_E(-1),
    RAISE_REFRESH(-1),
    RAISE_UI_STATE(-1),
    RAISE_INC_EXP(-1),
    RAISE_ADD_PIECE(-1), // v210
    E_N_D__R_A_I_S_E(-1),

    SEND_MATE_MAIL(-1),
    REQUEST_GUILD_BOARD_AUTH_KEY(-1),
    REQUEST_CONSULT_AUTH_KEY(-1),
    REQUEST_CLASS_COMPETITION_AUTH_KEY(-1),
    REQUEST_WEB_BOARD_AUTH_KEY(-1),
    IRBOX_EVENT(-1),
    //1470

    B_E_G_I_N__I_T_E_M_U_P_G_R_A_D_E(1488),
    GOLD_HAMMER_REQUEST(1489), // v210
    GOLD_HAMMER_COMPLETE(1490), // v210
    //1474 something with Enchant UI
    //1475 Vicious Hammer?
    E_N_D__I_T_E_M_U_P_G_R_A_D_E(1476),

    B_E_G_I_N__B_A_T_T_L_E_R_E_C_O_R_D(-1),
    BATTLE_RECORD_ON_OFF_REQUEST(-1), // v210
    BATTLE_RECORD_SKILL_DAMAGE_LOG(-1),
    E_N_D__B_A_T_T_L_E_R_E_C_O_R_D(-1),

    // TODO
    B_E_G_I_N__F_A_R_M(-1),
    INSERT_FARM_OBJECT(-1),
    DELETE_FARM_OBJECT(-1),
    INSERT_FARM_TILE(-1),
    DELETE_FARM_TILE(-1),
    TRANSFER_FARM_FIELD(-1),
    BUY_FARM_OBJECT(-1),
    SEL_FARM_OBJECT(-1),
    MY_HOUSE_UPGRADE(-1),
    FARM_ADMIN_COMMAND(-1),
    REQUEST_QUEST_COMPLETE(-1),
    CHECK_FARM_NAME(-1),
    REQUEST_INTERACT_OBJECT(-1),
    REQUEST_CONSUME_OBJECT(-1),
    REQUEST_CLICK_NPC(-1),
    REQUEST_RANDOM_FARM(-1),
    REQUEST_FARM_VISIT(-1),
    REQUEST_ADD_FARM_FRIEND(-1),
    FARM_IN_GAME_FRIEND_REQUEST(-1),
    REQUEST_DELETE_FARM_FRIEND(-1),
    REQUEST_ADD_BLACK_LIST(-1),
    REQUEST_DELETE_BLACK_LIST(-1),
    REQUEST_FARM_INFO_UI(-1),
    CHECK_FARM_NAME_BY_CONSUME(-1),
    REQUEST_AUTO_HARVEST(-1),
    REQUEST_SOUL_RECHARGE(-1),
    REQUEST_TRANSFER_FARM_BY_NAME(-1),
    MY_FARM_MONSTER_REQUEST(-1),
    FARM_MONSTER_COMBINE(-1),
    FARM_MONSTER_SET_NAME_REQUEST(-1),
    FARM_MONSTER_CARE(-1),
    FARM_MONSTER_PLAY(-1),
    FARM_MONSTER_RELEASE(-1),
    FARM_MONSTER_SEARCH_REQUEST(-1),
    FARM_MONSTER_POS_RECODE(-1),
    FARM_MONSTER_LOCKER_REQUEST(-1),
    FARM_MONSTER_LIFE_EXTEND(-1),
    PHOTO_UPDATE(-1),
    PHOTO_GET_REQUEST(-1),
    MY_HOME_SEND_NOTICE_REQUEST(-1),
    MY_HOME_LOAD_MAIN_LOG_REQUEST(-1),
    MY_HOME_DELETE_LOG_REQUEST(-1),
    FARM_WHISPER(-1),
    FARM_GROUP_MESSAGE(-1),
    REQUEST_FARM_FRIEND_RECOMMEND(-1),
    FARM_REQUEST_IN_GAME_INFO_SET(-1),
    FARM_REQUEST_IN_GAME_INFO_MOD(-1),
    REQUEST_FARM_FRIEND_INFO(-1),
    REQUEST_FARM_TODAY(-1),
    REQUEST_FIRST_ENTER_REWARD(-1),
    CHECK_ADMIN_ACCOUNT_LOG(-1),
    E_N_D__F_A_R_M(-1),

    CHARACTER_LIST_REQUEST(-1),
    COPY_CHARACTER_TO_TEST_REQUEST(-1),
    //End v208


    REWARD_REQUEST(1565), // v214

    VORAGE_REQUEST(-1),

    //1535 AdminAccount (ManagerAccount or GradeCode=1)



    SPAM_60_SEC(-1),

    RETRO_LEAVE(-1),

    NO(1889), // v210 (?)
    ;

    /**
     * Created on 2/18/2017.
     */
    private short value;
    private final static Map<Short, InHeader> opToHeaderMap = new HashMap<>();

    static {
        for (InHeader ih : values()) {
            opToHeaderMap.put(ih.getValue(), ih);
        }
    }

    InHeader(int op) {
        this.value = (short) op;
    }

    public short getValue() {
        return value;
    }

    public static InHeader getInHeaderByOp(int op) {
        return opToHeaderMap.getOrDefault((short) op, null);
    }

    public static boolean isSpamHeader(InHeader inHeaderByOp) {
        List<InHeader> spam = Arrays.asList(
                //  UPDATE_CLIENT_ENVIRONMENT,
                PONG,
                WVS_SET_UP_STEP,
                SECURITY_PACKET,
                PRIVATE_SERVER_PACKET,
                MOB_MOVE,
                USER_MOVE,
                //  USER_HIT,
                //  USER_EMOTION,
                 PASSIVE_SKILL_INFO_UPDATE,
                //  USER_CHANGE_STAT_REQUEST,
                //  SUMMONED_MOVE,
                SPAM_60_SEC,
                 USER_TEMPORARY_STAT_UPDATE_REQUEST,
                // USER_CALC_DAMAGE_STAT_SET_REQUEST,
                // MOB_APPLY_CTRL,
                //  USER_REQUEST_INSTANCE_TABLE,
                  USER_QUEST_REQUEST,
                //  CHECK_LOGIN_AUTH_INFO,
                NPC_MOVE,
                  SKILL_PET_MOVE,
                //   FAMILIAR_MOVE,
                   PET_MOVE,
                  ALIVE_ACK,
                //  OBSTACLE_ATOM_COLLISION,
                // USER_COMPLETE_COMBO_KILL_COUNT_CHECK,
                // USER_COMPLETE_MULTI_KILL_COUNT_CHECK,
                // USER_COMPLETE_MULTI_KILL_CHECK,
                USER_CHAT,
                // XENON_CORE_OVERLOAD,
                // MOB_SKILL_DELAY_END,
                // ANDROID_MOVE,
                // DRAGON_MOVE,
                 SERPENT_VORTEX_INCREMENT_REQUEST
                // MOD_SPECTRA_ENERGY
        );
        return spam.contains(inHeaderByOp);
    }

    public static void main(String[] args) {
//        int change = 39;
//        for (OutHeader header : values()) {
//            int val = header.getValue();
//            if (val >= SET_FIELD.getValue()) {
//                val += change;
//            }
//            System.out.printf("%s(%d),%n", header, val);
//        }
        File file = new File(ServerConstants.DIR + "\\src\\main\\java\\net\\swordie\\ms\\handlers\\header\\InHeader.java");
        int change = 1;
        InHeader checkOp = null;
        try (Scanner s = new Scanner(file)) {
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (line.contains(",") && line.contains("(")) {
                    String[] split = line.split("[()]");
                    String name = split[0];
                    if (!Util.isNumber(split[1])) {
                        System.out.println(line);
                        continue;
                    }
                    int val = Integer.parseInt(split[1]);
                    InHeader ih = Arrays.stream(InHeader.values()).filter(o -> o.toString().equals(name.trim())).findFirst().orElse(null);
                    if (ih != null) {
                        InHeader start = B_E_G_I_N__C_A_S_H_S_H_O_P;
                        if (ih.ordinal() >= start.ordinal() && ih.ordinal() < B_E_G_I_N__I_T_E_M_U_P_G_R_A_D_E.ordinal()) {
                            if (line.contains("*")) {
                                checkOp = ih;
                            }
                            val += change;
                            System.out.println(String.format("%s(%d), %s", name, val, start == ih ? "// *" : ""));
                        } else {
                            System.out.println(line);
                        }
                    } else {
                        System.out.println(line);
                    }
                } else {
                    System.out.println(line);
                }
            }
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        if (checkOp != null) {
            System.err.println(String.format("Current op (%s) contains a * (= updated). Be sure to check for overlap.", checkOp));
        }
    }
}