# id 811000020 (East Tower Central Shrine : Inside East Tower Central Shrine), field 811000020
sm.lockInGameUI(True, True)
sm.spawnNpc(9130118, 139, 88)
sm.showNpcSpecialActionByTemplateId(9130118, "summon", 0)
sm.setSpeakerType(3)
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9130118) # Miroku
sm.sendNext("What, who are you?")
sm.setParam(17)
sm.sendSay("...What are you doing here?")
sm.setParam(5)
sm.sendSay("Me? You're obviously not worthy enough to know who I am. As for what I'm doing, I'm brainwashing these little soldiers! Don't you have eyes?")
sm.sendSay("Those lowly beings are better off being brainwashed. You know, I think you will be, too.")
sm.sendSay("So hold still! I'LL MAKE THIS QUICK!")
sm.setParam(17)
sm.sendSay("No more jokes. You can't just do as you please! ")
sm.lockInGameUI(False, True)
sm.closeUI(1128)
sm.startQuest(58936)
sm.createQuestWithQRValue(58973, "m035=clear")
