# id 811000021 (Hieizan : Path to West Tower), field 811000021
sm.lockInGameUI(True, True)
sm.spawnNpc(9131000, 0, 0)
sm.showNpcSpecialActionByTemplateId(9131000, "summon", 0)
sm.setSpeakerType(3)
sm.setParam(5)
sm.setParam(17)
sm.sendSay(" I didn't follow you. I didn't even expect to see you.  ")
sm.sendSay("But today, I will finally defeat you!")
sm.setParam(5)
sm.setParam(17)
sm.sendSay("Enough! Taste my blade!")
sm.setParam(5)
sm.completeQuestNoCheck(58937)
sm.setParam(17)
sm.sendSay("No! You are my worst enemy, and I will be sure to rid the world of you!")
sm.createQuestWithQRValue(18418, "B=35628")
sm.sendSay(" Where did you go?! ")
sm.createQuestWithQRValue(58973, "m035=clear;dr1=clear")
sm.lockInGameUI(False, True)
