# id 867201601 (Abrup Basin : Grim Vale Cave), field 867201601
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.spawnNpc(9400680, 901, 401)
sm.showNpcSpecialActionByTemplateId(9400680, "summon", 0)
sm.forcedFlip(True)
sm.forcedAction(29, 100000000)
sm.sendDelay(1000)
sm.playSound("Sound/PL_MONAD.img/EP1/ACT1/wind", 128)
sm.sendDelay(3000)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face3#... ")
sm.setParam(57)
sm.sendSay("#b... ")
sm.setParam(37)
sm.sendSay("#face3#Hmm... do you hear something? ")
sm.setParam(57)
sm.sendSay("#bWhat? ")
sm.setParam(37)
sm.sendSay("#face3#Here, listen... That. Someone crying, perhaps. Is it just me? ")
sm.playSound("Sound/PL_MONAD.img/EP1/ACT1/wind", 128)
sm.sendDelay(3000)
sm.setParam(57)
sm.sendNext("#bIt's just the wind. Don't worry. ")
sm.setParam(37)
sm.sendSay("#face3#... ")
sm.setParam(57)
sm.sendSay("#b... ")
sm.sendDelay(7000)
sm.setParam(37)
sm.sendNext("#face1#It's finally dawning on me just how long a day this has been. ")
sm.setParam(57)
sm.sendSay("#bI know... we've been going non-stop since we left Kaptafel. ")
sm.setParam(37)
sm.sendSay("#face1#I don't mean to complain, mind you. After all, I want to set a good example for the others... who aren't here right now. Ha... ")
sm.sendSay("#face0#I do wonder, though... am I doing enough for those who rely on me? Or am I really a burden on those I mean to help? ")
sm.setParam(57)
sm.sendSay("#bYou? A burden? You work way too hard for that to ever be true. ")
sm.setParam(37)
sm.sendSay("#face1#Thank you. ")
sm.sendSay("#face0#But I have been a burden to you, by following you all the way out here. And for that, I am sorry. ")
sm.setParam(57)
sm.sendSay("#bDon't be ridiculous. If not for you, I'd be an ice cube under that lake right now. ")
sm.sendSay("#bHonestly, I'm glad you came along. I've really enjoyed your company. ")
sm.setParam(37)
sm.sendSay("#face1#I'm happy to hear that. ")
sm.sendSay("#face1#This reminds me of the night we spent at that lost village. ")
sm.sendSay("#face1#When it's so dark and quiet, you can really appreciate the night sky. ")
sm.setParam(57)
sm.sendSay("#bYeah, Abrup is probably the only place you can see the aurora like this. ")
sm.setParam(37)
sm.sendSay("#face0#Back then... you asked about my dreams, didn't you? ")
sm.sendSay("#face0#Well, I've never told anyone of them. I have this fear... that if I tell someone about my dreams, they will come true. ")
sm.sendSay("#face0#But today, just today, I believe I can tell you. ")
sm.sendSay("#face0#That is, if you're willing to listen? ")
sm.setParam(57)
sm.sendSay("#bOf course.")
sm.setParam(37)
sm.sendSay("#face0#In my dreams, it's always dark and cold. ")
sm.sendSay("#face0#And I always see the same girl. ")
sm.sendSay("#face4#She's running through a black forest, chased by someone or something I never see. She falls, her skin bruised and battered, but she keeps going. ")
sm.sendSay("#face4#The dream skips ahead to her lying still on the barren snowfield. I don't know if she's exhausted or unconscious, but I know she's still alive. I can feel it. ")
sm.sendSay("#face5#When I awaken, I still feel as though I am that poor girl. So cold, and so frightened... ")
sm.sendSay("#face5#This dream, this exact same dream... I've had it every night for months. ")
sm.setParam(57)
sm.sendSay("#bThat sounds terrible. ")
sm.setParam(37)
sm.sendSay("#face5#But what does it mean? Is that girl waiting for me somewhere? Does she need my help? ")
sm.sendSay("#face4#Having the exact same dream every night must mean something. Especially since... my father is there, too. ")
sm.setParam(57)
sm.sendSay("#bYour father? ")
sm.setParam(37)
sm.sendSay("#face5#Yes... without a doubt. ")
sm.sendSay("#face5#He's wearing his Afinas scholar robes, as he always did... ")
sm.sendSay("#face4#But I don't know why he's there. Is he saving that girl? Or is it... something sinister... ")
sm.sendSay("#face4#To be honest, that's the real reason I wanted to be here. ")
sm.sendSay("#face3#There's something waiting for me out here. I know now that dark forest from my dream is Abrup's Windsleep Forest. ")
sm.setParam(57)
sm.sendSay("#bThis is the same forest you saw the girl fleeing in? ")
sm.setParam(37)
sm.sendSay("#face3#I know it sounds positively mad, but I'm sure of it. And that means there's something here for me to find. ")
sm.sendSay("#face5#So I followed you, #h0#, even knowing the dangers and burdening you further. I'm so sorry. ")
sm.setParam(57)
sm.sendSay("#bWell... have you found anything yet? ")
sm.setParam(37)
sm.sendSay("#face3#...No. Nothing at all. ")
sm.sendSay("#face3#I don't even know what I expected to find. Did I think I'd meet that girl? Or my father? I don't know... ")
sm.setParam(57)
sm.sendSay("#bBut you've taken an important step, Alika. That's always hard. ")
sm.sendSay("#bYou've taken the first step towards resolution. ")
sm.setParam(37)
res = sm.sendNext("#face1#Hah, thanks #h0#. You're starting to remind me of my friend. #b\r\n#L0# Are you talking about Cayne?#l\r\n#L1# Your friend must be quite thoughtful, just like me...#l")
res = sm.sendNext("#face1#Cayne is a good friend of mine, of course. But I'm talking about another friend. A very important one. #b\r\n#L0# Tell me more.#l\r\n#L1# I'd like to meet that friend sometime.#l")
sm.sendNext("#face2#Her name is Vivere, and she's my best friend. She's practically family, we're so close. ")
sm.sendSay("#face2#We've been together nearly our whole lives. That's something that's bothered me here... we've never been apart this long. ")
res = sm.sendNext("#face3#I should have brought her with me...#b\r\n#L0# Is your friend a scholar, too?#l\r\n#L1# Let's go back to your father... #l")
sm.sendNext("#face1#No, not a scholar. But she's at least as smart as I am. ")
sm.setParam(57)
sm.sendSay("#bSmarter than you, the youngest scholar in Afinas? ")
sm.setParam(37)
sm.sendSay("#face1#Yes, much smarter! For me, doing well academically is expected, because all I did was study ever since I was young. ")
sm.sendSay("#face1#But my friend... it all just comes so naturally to her. ")
sm.setParam(57)
sm.sendSay("#bAre you ever jealous of her? ")
sm.setParam(37)
res = sm.sendNext("#face1#Jealous? No, not at all! I'm happy to have someone like her in my life. #b\r\n#L0# Studying since you were young... isn't that hard?#l\r\n#L1# Tell me more about your friend. #l")
sm.sendNext("#face0#It was hard... because it was hard to earn praise even if I did well. ")
sm.sendSay("#face0#No matter how high my scores were, it was never enough for my father. And others would give him credit for my success. ")
sm.sendSay("#face0#I hated hearing that, so I tried harder than anyone. I wanted to be perfect, so no one could find any fault with me. ")
sm.sendSay("#face1#Because of my drive, I was able to make Apprentice Scholar faster than anyone in the history of Afinas. So in that sense, it was worth it. ")
sm.setParam(57)
sm.sendSay("#bThat's amazing, Alika. You never gave up, even when times got tough. So admirable. ")
sm.setParam(37)
res = sm.sendNext("#face1#'If you can dream it, you can do it.' That's my favorite quote. It's the one that's kept me going this whole time. #b\r\n#L0# So, what do you hope to do in the future?#l\r\n#L1# I see.#l")
sm.sendNext("#face1#Hmm... well... it's a little embarrassing... ")
sm.setParam(57)
sm.sendSay("#bThere's no reason to be embarrassed of your dreams. You've accomplished so much, so why should you care if someone doesn't like your dream? ")
sm.setParam(37)
sm.sendSay("#face2#True, very true. And it's not like you'd be mean about it anyway, right? Ha ha... Okay, I'll tell you, but you CANNOT tell Cayne, okay? ")
sm.setParam(57)
sm.sendSay("#bWhatever it is, he'll never hear it from me. ")
sm.setParam(37)
sm.sendSay("#face1#I've only left Afinas headquarters a few times in my whole life. ")
sm.sendSay("#face1#This right now is the biggest adventure I've ever had. To be fair, it's a pretty big one. ")
sm.sendSay("#face1#My dream, then, is to travel to a brand new world! ")
sm.sendSay("#face2#I want to find a place far from the world we know, a land that knows nothing of us, and live amongst its people. I want to share my knowledge for the good of all. What do you think of that? ")
sm.setParam(57)
sm.sendSay("#bI think that's a great idea! But... why is it a secret from Cayne? ")
sm.setParam(37)
sm.sendSay("#face1#Because if things are perfect, both Cayne and Vivere are there with me. I want to share my dream with them, those that I hold dear... ")
sm.setParam(57)
sm.sendSay("#bWouldn't Cayne be happy to hear that? ")
sm.setParam(37)
sm.sendSay("#face1#Hmm... that could reach my father... so this needs to be a secret even to you,  #h0#.")
res = sm.sendNext("#face1##h0#, do you perhaps... want to join us in Afinas? #b\r\n#L0# Do you think I should become an Afinas knight?#l\r\n#L1# Why?#l")
sm.sendNext("#face1#I admit, I expected that. Someone like you is certain to be in great demand, right #h0#? ")
res = sm.sendNext("#face1#I want to show you how much I appreciate what you've done. Think of it as a vacation! You can relax, rest up... Oh! And I can introduce you to Vivere, too. #b\r\n#L0# Thank you for the offer, but I have other commitments.#l\r\n#L1# Anytime, if you need me.#l")
sm.sendNext("#face2#Good! It's a promise, then. Once we get out of this mess, we're going back to Afinas together.")
sm.setParam(57)
sm.sendSay("#bOkay. It's getting late. You should get some sleep. ")
sm.setParam(37)
sm.sendSay("#face1#You're right, of course. But I fear... if we sleep here, will we still be alive in the morning? ")
sm.setParam(57)
sm.sendSay("#bOf course. Don't worry, just rest. ")
sm.setParam(37)
sm.sendSay("#face1#What about you, #h0#? ")
sm.setParam(57)
sm.sendSay("#bI'll be sleeping soon as well. We have a lot to do tomorrow. ")
sm.setParam(37)
sm.sendSay("#face1#Okay. ")
sm.setParam(57)
sm.sendSay("#b... ")
sm.setParam(37)
sm.sendSay("#face1#Don't worry, #h0#! We'll find that dear old lady. ")
sm.sendSay("#face1#The breath of Windsleep Forest is with her. ")
sm.sendSay("#face1#I had always wondered what that greeting meant, and now I finally know. ")
sm.sendSay("#face1#I must say, it feels as though the breath of Windsleep Forest is what led us here. ")
sm.setParam(57)
sm.sendSay("#bYou might be right. ")
sm.setParam(37)
sm.sendSay("#face1#So don't you worry. ")
sm.setParam(57)
sm.sendSay("#b... ")
sm.setParam(37)
sm.sendSay("#face1#All right then, off to sleep! ")
sm.sendSay("#face2#Good night, #h0#! ")
sm.setParam(57)
sm.sendSay("#bGood night, Alika. ")
sm.spawnNpc(9400580, 901, 401)
sm.showNpcSpecialActionByTemplateId(9400580, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400580, "sleep", -1)
sm.sendDelay(2000)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(3000)
sm.setParam(37)
sm.sendNext("#face5#Hmm... umm... ")
sm.sendSay("#face5#Where are you... going...? ")
sm.sendSay("#face5#Ugh.... agh... ")
sm.setParam(57)
sm.sendSay("#bShe must be having that same nightmare...")
sm.sendDelay(3000)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64081, "dir=1")
sm.warp(867201603)
