# id 867202652 (Abrup Basin : Sunglow Forest), field 867202652
sm.lockInGameUI(True, False)
sm.spawnNpc(9400592, -550, 130)
sm.showNpcSpecialActionByTemplateId(9400592, "summon", 0)
sm.spawnNpc(9400589, -460, 130)
sm.showNpcSpecialActionByTemplateId(9400589, "summon", 0)
sm.spawnNpc(9400611, -300, 130)
sm.showNpcSpecialActionByTemplateId(9400611, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400611, "attack1", -1)
sm.showNpcSpecialActionByTemplateId(9400589, "attack1", -1)
sm.moveNpcByTemplateId(9400592, True, 100, 70)
sm.sendDelay(1000)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendNext("#face0#Ah... Umm... ")
sm.sendSay("#face0#D-do you finally believe I'm clean? ")
sm.resetNpcSpecialActionByTemplateId(9400611)
sm.resetNpcSpecialActionByTemplateId(9400589)
sm.showNpcSpecialActionByTemplateId(9400611, "die1", 0)
sm.sendDelay(1200)
sm.flipNpcByTemplateId(9400589, True)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#We do. This is the most level-headed you've been since this whole mess started. ")
sm.setParam(57)
sm.sendSay("#bAnd this is the most level-headed I've EVER seen you! ")
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendNext("#face1#That day... when I returned home from the the Skuas market... ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Aruhi... ")
sm.moveNpcByTemplateId(9400589, True, 100, 70)
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendSay("#face1#Please, just hear me out, just this once... Please, Peytour. ")
sm.setParam(57)
sm.sendSay("#bGo on. ")
sm.setParam(37)
sm.sendSay("#face1#When I returned, the town felt wrong. There were footprints everywhere... And at the end of those footprints... friends and loved ones being carried away screaming... ")
sm.sendSay("#face1#I saw it with my own two eyes. They were demons covered head to toe in steel armor, white as snow! ")
sm.sendSay("#face1#I'm a coward... I did nothing. I just hid and waited for it all to end. ")
sm.sendSay("#face1#But I'm no liar... I've been telling the truth every day since it happened. Do you believe me now? ")
sm.setParam(57)
sm.sendSay("#b...Alright. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face1#There are no other witnesses, and the kidnappers left no traces, so... ")
sm.setParam(57)
sm.sendSay("#bLet's ask around, then. Perhaps someone from another village saw them. ")
sm.createQuestWithQRValue(64039, "chk1=1")
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendNext("#face0#T-thank you! Oh, thank you! All I've wanted was to be trusted again! ")
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#Almost done... Just a little bit more...")
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(64108)
sm.warp(-1)
