# id 867201012 (Abrup Basin : Svarti Village Empty Paddock), field 867201012
sm.lockInGameUI(True, False)
sm.spawnNpc(9400598, 1790, 60)
sm.showNpcSpecialActionByTemplateId(9400598, "summon", 0)
sm.spawnNpc(9400587, 1140, 60)
sm.showNpcSpecialActionByTemplateId(9400587, "summon", 0)
sm.spawnNpc(9400596, 1070, 60)
sm.showNpcSpecialActionByTemplateId(9400596, "summon", 0)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.forcedMove(False, 250)
sm.sendDelay(1000)
sm.startQuest(64061)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bWhat brings you here? ")
sm.sendDelay(250)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 33371939, 0, 0)
sm.moveNpcByTemplateId(9400598, True, 120, 80)
sm.sendDelay(2000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendNext("N-n-nothing! I mean, hi! I'm Thorson, and I'm from Svarti! I'm related to Chief Gurnardson! Well, distant relative.")
sm.flipNpcByTemplateId(9400587, False)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400587, False, 320, 150)
sm.sendDelay(2000)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#Are you... watching us? ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("No! No. N-n-no. ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#Planning to steal something, then? We have nothing, you know. ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("No, no-o-o! It's just... ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#Just? ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("W-well, I... wanted to meet people from outside... ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#Do you think we're here for your amusement? ")
sm.sendDelay(500)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.setParam(57)
sm.sendNext("#bChief Kan, please. I can tell he means well. ")
sm.setParam(37)
sm.sendSay("#face0#...Considering everything we've been through here, I remain skeptical. ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("It's really not like that! I've never seen this many people in my entire life... ")
sm.sendSay("Really. The chief probably doesn't even know that I'm here! ")
sm.sendDelay(500)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.setParam(57)
sm.sendNext("#bWell, you need to understand... Your chief was not very kind to us when we were trying to rest for the evening. ")
sm.setParam(37)
sm.sendSay("Sigh... ")
sm.sendSay("That's because... oh... ")
sm.sendSay("Things have been really bad for us here, too. ")
sm.sendSay("Did you see how empty the village is? We're starving, even the few of us that are left... ")
sm.sendSay("We lost all of our livestock to the monsters. And then the river froze in a flash, so we can't even fish. ")
sm.sendSay("Some of us went out to break through the ice, but there were no fish underneath! It's like they all disappeared. ")
sm.setParam(57)
sm.sendSay("#bI see. I expected Svarti to have it tough, too, but not that much. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#If that's the case, surely you would have welcomed us with open arms instead of as a burden! ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("Well... since Kaptafel always steals our livestock... ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#How many times do I have to tell you that we've never TOUCHED your livestock?! ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("W-whoa! Sorry, sorry! Geez... You don't have to shout... ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#Why must we depend on those who mistrust and mistreat us for survival? What did we ever do to deserve this... ")
sm.completeQuestNoCheck(64061)
sm.createQuestWithQRValue(64061, "dirchk=1")
sm.flipNpcByTemplateId(9400587, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400587, True, 300, 150)
sm.sendDelay(1000)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.warp(867201100)
