# id 867201550 (null), field 867201550
sm.lockInGameUI(True, False)
sm.hideUser(True)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face1#Wow... ")
sm.setParam(57)
sm.sendSay("#bBeautiful. ")
sm.setParam(37)
sm.sendSay("#face0#Do you see that town over there? ")
sm.setParam(57)
sm.sendSay("#bWhere? ")
sm.setParam(37)
sm.sendSay("#face0#There! Between the cliffs! ")
sm.setParam(57)
sm.sendSay("#bOh! Wow, how did people manage to cram a town in there? ")
sm.setParam(37)
sm.sendSay("#face3#It looks solid, too. That place could keep everyone safe. ")
sm.setParam(57)
sm.sendSay("#bYeah, and there's enough space for everyone to have a roof over their head again. ")
sm.setParam(37)
sm.sendSay("#face0#You're right. Goodness, should we hurry down? ")
sm.setParam(57)
sm.sendSay("#bOkay, hold on! ")
sm.lockInGameUI(False, True)
sm.startQuest(64059)
sm.warp(867201560)
