# id 867201102 (Abrup Basin : Svarti Camp), field 867201102
sm.lockInGameUI(True, False)
sm.spawnNpc(9400598, 1720, 30)
sm.showNpcSpecialActionByTemplateId(9400598, "summon", 0)
sm.spawnNpc(9400580, 770, 30)
sm.showNpcSpecialActionByTemplateId(9400580, "summon", 0)
sm.spawnNpc(9400589, 1130, 30)
sm.showNpcSpecialActionByTemplateId(9400589, "summon", 0)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(1000)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bThorson! ")
sm.forcedMove(False, 60)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 33450786, 0, 0)
sm.sendDelay(1000)
sm.moveNpcByTemplateId(9400598, True, 100, 70)
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendNext("Yes, hero? You called? What can I do for you? ")
sm.setParam(57)
sm.sendSay("#bI have something to ask you. ")
sm.setParam(37)
sm.sendSay("Anything! Go right ahead. ")
sm.setParam(57)
sm.sendSay("#bDo you happen to know the old lady living in the cabin in the forest with her granddaughter? ")
sm.sendDelay(1500)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 33450786, 0, 0)
sm.setParam(37)
sm.sendNext("Hmm... Oh! That witch granddaughter and the old lady! ")
sm.setParam(57)
sm.sendSay("#bWitch? ")
sm.setParam(37)
sm.sendSay("Yep! But hey, what about the old lady? ")
sm.setParam(57)
sm.sendSay("#bDid she visit this town a few months ago? ")
sm.setParam(37)
sm.sendSay("Uh... hmm... the old lady... ")
sm.sendSay("Uh... to be honest, I'm not sure. The chief usually deals with visitors. ")
sm.sendDelay(1500)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 33450786, 0, 0)
sm.sendNext("Oh, hey! I'll go ask the chief for you! ")
sm.flipNpcByTemplateId(9400598, False)
sm.moveNpcByTemplateId(9400598, False, 200, 90)
sm.sendDelay(3000)
sm.forcedFlip(True)
sm.sendDelay(500)
sm.forcedMove(True, 220)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400589, False, 70, 60)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#From what I could hear, you were talking about Sanaan. Did you learn anything about her whereabouts? ")
sm.setParam(57)
sm.sendSay("#bThorson didn't seem to know. He went to ask Chief Gurnardson. ")
sm.setParam(37)
sm.sendSay("#face0#I see. He's quite the friendly lad. ")
sm.setParam(57)
sm.sendSay("#bOh, right... Thorson said something about a witch granddaughter. ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400589, True)
sm.sendDelay(500)
sm.setParam(37)
sm.sendNext("#face0#Hah... ")
sm.moveNpcByTemplateId(9400589, True, 200, 70)
sm.sendDelay(500)
sm.forcedMove(True, 100)
sm.sendNext("#face0#She's a little different from us, and some people concern themselves too much with such differences. Nothing more. ")
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400580, True)
sm.setParam(57)
sm.sendNext("#bDifferent? How so?")
sm.setParam(37)
sm.sendSay("#face0#Hmm... it may be more appropriate to say she is special. Both her natural abilities and her skin color.")
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400580, False, 280, 70)
sm.sendDelay(3500)
sm.flipNpcByTemplateId(9400589, False)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face0##h0#, I forgot to give this to you earlier.")
sm.sendDelay(900)
sm.sendDelay(2000)
sm.avatarOriented("Effect/OnUserEff.img/questEffect/PL_MONAD1/1")
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(500)
sm.sendNext("#face0#Peytour, what exactly do you mean?")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Sanaan and her granddaughter... let's see, her name was... Blanche. Right, Blanche.")
sm.sendSay("#face0#They were once villagers of Kaptafel, though it was before I settled in the town proper.")
sm.setParam(57)
sm.sendSay("#bI did not know that.")
sm.setParam(37)
sm.sendSay("#face0#They said that Sanaan raised Blanche since she was a baby. As she grew, her differences became more and more obvious.")
sm.sendSay("#face0#That itself was not a problem. The problem was when the villagers began to notice how Blanche was different from them.")
sm.sendSay("#face0#Blue-gray skin, swift running, incredible archery...")
sm.sendSay("#face0#I never met the girl, but from the stories it's not hard to imagine people fearing or even hating her, out of ignorance.")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face4#Blue-gray skin...")
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 0, 0, 0)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 33450787, 0, 0)
sm.sendSay("#face4#You mean...")
sm.setParam(57)
sm.sendSay("#bWas she a demon?")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Half-demon, as I hear it. Regardless, Sanaan took her granddaughter into the forest to keep her safe.")
sm.sendSay("#face0#This is as much I know. I've always pitied them, struggling on their own because of the ill treatment of others...")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Hmmm...")
sm.spawnNpc(9400598, 1500, 30)
sm.showNpcSpecialActionByTemplateId(9400598, "summon", 0)
sm.spawnNpc(9400597, 1550, 30)
sm.showNpcSpecialActionByTemplateId(9400597, "summon", 0)
sm.moveNpcByTemplateId(9400598, True, 170, 100)
sm.moveNpcByTemplateId(9400597, True, 270, 60)
sm.sendDelay(3000)
sm.sendDelay(1000)
sm.speechBalloon(False, 0, 0, "Hero! Hero! ", 3000, 1, 0, 0, 0, 4, 9400598, 4878499)
sm.forcedFlip(True)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(2000)
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendNext("#face0#Hmm! What is it? You have questions for me?")
sm.setParam(57)
sm.sendSay("#bYes, do you...")
sm.setParam(37)
sm.sendSay("#face0#Hold a moment! Information is not free here, friend. Your questions come with a price.")
sm.setParam(57)
sm.sendSay("#bExcuse me?")
sm.setParam(37)
sm.sendSay("#face0#Now, then... I heard from Thorson earlier that you brought back some Leatty Crystals for your people, right? I would appreciate you sharing your spoils, to support those who are supporting you.")
sm.setParam(57)
sm.sendSay("#b...How many do you need?")
sm.flipNpcByTemplateId(9400597, False)
sm.sendDelay(250)
sm.setParam(37)
sm.sendNext("#face0#Thorson, how many did they bring back? ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("Uh, I don't know... maybe 100? ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#What? 100? What a bounty! Surely you can spare half. ")
sm.flipNpcByTemplateId(9400597, True)
sm.sendDelay(250)
sm.setParam(57)
sm.sendNext("#bI'll need some time to round them up. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face4#No, please... stay here. ")
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, True, 300, 200)
sm.sendDelay(2400)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, False, 290, 200)
sm.sendDelay(3000)
sm.setParam(57)
sm.sendNext("#bThat's... ")
sm.setParam(37)
sm.sendSay("#face4#We should hear the story first. The knights can handle a simple task like gathering Leatty Crystals. ")
sm.sendDelay(2000)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(3500)
sm.speechBalloon(False, 0, 0, "Let's see... ", 3000, 1, 0, 0, 0, 4, 9400597, 4878499)
sm.sendDelay(3500)
sm.speechBalloon(False, 0, 0, "Seems about right.", 3000, 1, 0, 0, 0, 4, 9400597, 4878499)
sm.setParam(57)
sm.sendNext("#bNow, continue with your story. It had better be worth 50 Leatty Crystals. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#Goodness, you needn't be so skeptical! ")
sm.sendSay("#face0#Hmm, hmm... Ahh yes, the old lady. I remember her visits to Svarti well. She came twice, actually! ")
sm.setParam(57)
sm.sendSay("#bTwice? ")
sm.setParam(37)
sm.sendSay("#face0#The first time was about 4 or 5 months ago... she was looking for her granddaughter, so I sent her away. We had no outsiders here at the time, you see. ")
sm.setInnerOverrideSpeakerTemplateID(9400598) # Thorson
sm.sendSay("That's right. The chief usually turns people away at the gate. ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#Ahem! Then again about two months ago... probably a little before the monsters turned on us, she came back. ")
sm.sendSay("#face0#Of course, I told her that her granddaughter was not here. Because she isn't. Of course. ")
sm.sendSay("#face0#I recall she mumbled something about returning home. Perhaps this was the last place she looked? ")
sm.setParam(57)
sm.sendSay("#bSo... she went back to that cabin after all. ")
sm.setParam(37)
sm.sendSay("#face0#There you go! Surely that was some valuable information, eh? Well-worth your efforts, hmm? ")
sm.setParam(57)
sm.sendSay("#bIf she's still at the cabin... ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face5#...then she must be in danger. ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#Why ARE you looking for that old lady, anyway? Do you know her? ")
sm.setParam(57)
sm.sendSay("#bIn a way... She is the one who sent me the letter that brought me to Abrup. ")
sm.sendSay("#bDespite that, I still haven't met her in person. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#In a way, we have Sanaan to thank for our survival. ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#I-is that so? That old lady saved all of us? Hmm! ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Well, it was her letter that brought #h0# here from the outside world. ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#Ah, is that so? Perhaps... ")
sm.sendSay("#face0#S-so then, you're going to that cabin? Are you planning to bring her here? ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Are you really planning to go there? ")
sm.showEffect("Effect/OnUserEff.img/emotionBalloon/noSpeak", 2000, 0, 0, 0, 0, 0, 0)
sm.setParam(57)
sm.sendSay("#b... ")
sm.setParam(37)
sm.sendSay("#face0#The forest is far too dangerous right now, even for you. And there's no guarantee she's still there. ")
sm.forcedFlip(True)
sm.sendDelay(250)
sm.setParam(57)
sm.sendNext("#bHm. If she is in the dangerous forest...")
sm.sendDelay(1000)
sm.speechBalloon(False, 0, 0, "Wait! Why are you ignoring me?", 3000, 1, 0, 0, 0, 4, 9400597, 4878499)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face5#Are you really going? Into the deep forest? ")
sm.sendDelay(1000)
sm.speechBalloon(False, 0, 0, "This is why you never deal with mystery outsiders.", 3000, 1, 0, 0, 0, 4, 9400597, 4878499)
sm.setParam(57)
sm.sendNext("#bYes. I have to do this. ")
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face5#... ")
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400597, False)
sm.sendDelay(300)
sm.speechBalloon(False, 0, 0, "And Thorson! Stop being a blabbermouth already!", 3000, 1, 0, 0, 0, 4, 9400597, 4878499)
sm.moveNpcByTemplateId(9400597, False, 300, 100)
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400598, False)
sm.sendDelay(300)
sm.moveNpcByTemplateId(9400598, False, 300, 100)
sm.sendDelay(1000)
sm.setParam(57)
sm.sendNext("#bEvery moment counts. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#You really are stubborn sometimes. Do you even know where the cabin is? Ah, give me a moment. ")
sm.flipNpcByTemplateId(9400589, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400589, True, 650, 200)
sm.sendDelay(2000)
sm.setParam(57)
sm.sendNext("#b... ")
sm.sendDelay(250)
sm.sendDelay(2000)
sm.speechBalloon(True, 0, 0, "...", 3000, 1, 0, 0, 0, 4, 9400580, 4878499)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face4#... ")
sm.sendDelay(2000)
sm.setParam(57)
sm.sendNext("#bAlika, what's on your mind? ")
sm.speechBalloon(True, 0, 0, "...", 3000, 1, 0, 0, 0, 4, 9400580, 4878499)
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face5#Huh? Ah, n-nothing. ")
sm.sendSay("#face5#Just... be careful, and come back safe. Please, #h0#. ")
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, True, 1500, 200)
sm.sendDelay(2000)
sm.sendDelay(250)
sm.forcedMove(True, 650)
sm.sendDelay(3000)
sm.flipNpcByTemplateId(9400589, False)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400589, False, 100, 200)
sm.sendDelay(3000)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#Here, take this. ")
sm.setParam(57)
sm.sendSay("#bThis is... ")
sm.setParam(37)
sm.sendSay("#face0#Sanaan's cabin is beyond the Grim Vale in Windsleep Forest. ")
sm.sendSay("#face0#I would not suggest entering the Grim Vale under the circumstances, so please take the path around it. ")
sm.sendSay("#face0#However, if you have to spend the night in the forest, make camp in the canyon there. You'll be more secluded while you rest. ")
sm.sendSay("#face0#...I feel responsible for you taking on this burden. Perhaps I said something I shouldn't have. ")
sm.setParam(57)
sm.sendSay("#bDon't worry, Peytour. I'll be back in no time. ")
sm.setParam(37)
sm.sendSay("#face0#Of course, of course. Take care out there, and may the breath of Windsleep Forest be with you. ")
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(64070)
sm.warp(867201100)
