# id 867201510 (Abrup Basin : Spring Wind Hollow), field 867201510
sm.showFieldEffect("defense/count", 0)
sm.showNpcSpecialActionByTemplateId(9400595, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400689, "summon", 0)
sm.showFieldEffect("killing/stage/1", 0)
sm.showFieldEffect("killing/first/start", 0)
sm.showFieldEffect("defense/count", 0)
sm.showFieldEffect("killing/stage/2", 0)
sm.showFieldEffect("killing/first/start", 0)
sm.showFieldEffect("defense/count", 0)
sm.showFieldEffect("killing/stage/3", 0)
sm.showFieldEffect("killing/first/start", 0)
sm.showFieldEffect("defense/count", 0)
sm.showFieldEffect("killing/stage/4", 0)
sm.showFieldEffect("killing/first/start", 0)
sm.completeQuestNoCheck(64076)
sm.showFieldEffect("killing/clear", 0)
sm.warp(867201500)
