#Communing with Erda | used for V advancement
if sm.hasQuest(1460):
    sm.removeEscapeButton()
    sm.setSpeakerID(1540940)
    sm.sendNext("Can you hear us? Can't you hear us?")
    sm.setPlayerAsSpeaker()
    sm.sendNext("These voices...?")
    sm.setSpeakerID(1540940)
    sm.sendNext("Ah good, you can hear us.")
    sm.sendNext("We're what you call Erda. \r\n\r\n We formed this world under the protection of the World Tree. But now that the World Tree is scattered across the world and her protection has weakened, we can't help but let the Black Mage take us wherever he wants.")
    sm.sendNext("We're scared. Darkness lurks on the #rother side of that door#k. pulling us in. Only you can save us.")
    sm.sendNext("We can't help but scatter and flow to somewhere we don't know. That's our destiny.")
    sm.sendNext("Remember: the future of this world rests on your shoulders.")
    sm.setPlayerAsSpeaker()
    sm.sendNext("What did I just see? I'd better talk to the #bHistory Observer#k again.")
    sm.setQRValue(1460, "2")
    sm.lockInGameUI(False)
    sm.warpInstanceOut(270010111)
    sm.dispose()