# id 867200419 (Abrup Basin : Eyeful Territory), field 867200419
sm.lockInGameUI(True, False)
sm.spawnNpc(9400589, -720, 280)
sm.showNpcSpecialActionByTemplateId(9400589, "summon", 0)
sm.spawnNpc(9400582, -850, 280)
sm.showNpcSpecialActionByTemplateId(9400582, "summon", 0)
sm.spawnNpc(9400611, -970, 280)
sm.showNpcSpecialActionByTemplateId(9400611, "summon", 0)
sm.spawnNpc(9400611, -1090, 280)
sm.showNpcSpecialActionByTemplateId(9400611, "summon", 0)
sm.spawnNpc(9400611, -1300, 280)
sm.showNpcSpecialActionByTemplateId(9400611, "summon", 0)
sm.sendDelay(500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#Ugh, my aching back. Perhaps a snowstorm is coming. Let's take a break. ")
sm.showNpcSpecialActionByTemplateId(9400582, "movingattack", -1)
sm.showNpcSpecialActionByTemplateId(9400611, "attack1", -1)
sm.moveNpcByTemplateId(9400589, False, 280, 80)
sm.sendDelay(1000)
sm.forcedFlip(True)
sm.forcedMove(False, 316)
sm.sendDelay(501)
sm.sendDelay(2000)
sm.flipNpcByTemplateId(9400589, True)
sm.sendNext("#face0#Please, rest. You must be exhausted from all the fighting earlier. ")
sm.setInnerOverrideSpeakerTemplateID(9400582) # Cayne
sm.sendSay("#face0#I would prefer to finish up and return to the village. ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Don't want to keep Alika waiting, do you? ")
sm.sendSay("#face0#Well, I wouldn't want to slow you down, then. ")
sm.setInnerOverrideSpeakerTemplateID(9400582) # Cayne
sm.sendSay("#face0#A-ah, think nothing of it, Peytour. You rest while we finish up. ")
sm.sendSay("#face0#Right, #h0#? ")
sm.forcedFlip(True)
sm.setParam(57)
sm.sendSay("#b... ")
sm.sendDelay(500)
sm.forcedMove(True, 200)
sm.setParam(37)
sm.sendNext("#face1#That's the spirit! ")
sm.setParam(57)
sm.sendSay("#bYou really care about Alika. ")
sm.sendDelay(1000)
sm.forcedAction(5, 50000)
sm.setParam(37)
sm.sendNext("#face0#I-I... I am Alika's bodyguard. I'm... like her Prince Charming, I suppose... ")
sm.setParam(57)
sm.sendSay("#bRight, right... So, how big a deal is apprentice scholar? ")
sm.setParam(37)
sm.sendSay("#face0#Ha ha, Alika is no ordinary apprentice scholar. ")
sm.sendSay("#face0#She is the youngest of the Afinas scholars! A genius! Not to mention clever, charming, driven, gorgeous... ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#I heard she is the daughter of a high-ranking scholar. ")
sm.setParam(57)
sm.sendSay("#bOh! ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400582) # Cayne
sm.sendSay("#face0#Hey, hey, hey. Let's not read anything more into this, all right? That's not relevant... ")
sm.setParam(57)
sm.sendSay("#bThen why is your voice trailing off? ")
sm.setParam(37)
sm.sendSay("#face0#... ")
sm.sendSay("#face0#...Of course, I owe a great debt to her father Rookhowell. But right now, it is solely for Alika's sake. ")
sm.sendSay("#face1#There, 50! That's all of it. Now, let's head back!")
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64021, "dir1=1")
sm.warp(867200404)
