# id 450003760 (Lachelein Alley : Lachelein Alley), field 450003760
sm.lockInGameUI(True, False)
sm.blind(True, 255, 0, 0, 0, 0)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003251) # Protective Mask
sm.sendNext("#face0##h0#! #h0#! I'm coming to save you!")
sm.sendSay("#face0#Argh! My head... So many memories, flowing in... \r\nAhh... This is... A nightmare... #eThe#n nightmare...")
sm.sendSay("#face0#(Then... The one she's been looking for...?)")
sm.forcedFlip(True)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.setParam(57)
sm.sendNext("Protective Mask? You saved me!")
sm.setParam(37)
sm.sendSay("#face0#...")
sm.setParam(57)
sm.sendSay("But... I thought those that fell into the Arcane River... dissolve into Erdas?")
sm.changeBGM("Bgm46.img/ClockTowerofNightmare", 0, 0)
sm.bgmVolume(100, 1000)
sm.setParam(37)
sm.sendSay("#face0#A being that is neither human nor Erdas would not be destroyed.")
sm.sendSay("#face0#I am what Lucid seeks. \r\nThe nightmare that Lucid fears, #bis me.#k")
sm.setParam(57)
sm.sendSay("What?!")
sm.setParam(37)
sm.sendSay("#face0#I was the only one who could peer into Lucid's memories. \r\nI was the only one who grew weak when the dream weakened. ")
sm.sendDelay(1500)
sm.sendNext("#face0#Back then, when I was agonizing over whether I had a 'soul'... \r\nIt looks like I finally have my answer. ")
sm.setParam(57)
sm.sendSay("Protective Mask...")
sm.setParam(37)
sm.sendSay("#face0#Leave, #h0#. Just leave me alone. ")
sm.sendSay("#face0#I'm just another #billusion#k conjured up by Lucid's subconscious.")
sm.setParam(57)
sm.sendSay("...")
sm.sendDelay(1500)
sm.sendNext("Look. I don't know much about souls, but I do know one thing. ")
sm.sendSay("The way you struggled to survive, just to save others... It's proof you were never an illusion.")
sm.sendSay("The way you care, and your drive to keep on living are proof that you're alive. ")
sm.setParam(37)
sm.sendSay("#face0#...")
sm.sendDelay(1000)
sm.sendNext("#face0#The final music box is at the clocktower. You know what must be done.")
sm.sendDelay(1000)
sm.forcedMove(True, 500)
sm.sendDelay(2000)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.warp(450003000)
