# id 867202316 (Abrup Basin : Skuas), field 867202316
sm.showNpcSpecialActionByTemplateId(9400603, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400603, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400601, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400600, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400586, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400580, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400589, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400587, "summon", 0)
sm.showNpcSpecialActionByTemplateId(9400597, "summon", 0)
sm.lockInGameUI(True, False)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.moveNpcByTemplateId(9400580, False, 70, 50)
sm.sendDelay(250)
sm.forcedMove(False, 100)
sm.moveNpcByTemplateId(9400586, True, 40, 30)
sm.sendDelay(1000)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendNext("I never thought it would... ")
sm.moveNpcByTemplateId(9400589, False, 300, 120)
sm.sendDelay(3000)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#Sanaan! You made it! Oh, I'm so relieved... ")
sm.sendDelay(3000)
sm.flipNpcByTemplateId(9400589, True)
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400589, False)
sm.sendNext("#face0#Oh, I was so glad that I got carried away... ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("Hah, it's okay. Nice to know someone was worried. ")
sm.moveNpcByTemplateId(9400587, False, 130, 50)
sm.sendDelay(1000)
sm.moveNpcByTemplateId(9400597, False, 90, 50)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#It's... been a while, Sanaan. ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#Hmm, hmm! Yes, quite a while! Why didn't you tell me? ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("Tell you what, you old windbag? ")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face1#Well... Ah, hmm! ")
sm.sendSay("#face1#...About your situation, though... I suppose you did. Ah, well, I hope you understand that I was just following town policy! Hmm! ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("There's no point in dwelling on the past.")
sm.moveNpcByTemplateId(9400600, True, 30, 50)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400600) # Birna
sm.sendNext("Have I not taught you the importance of cooperation and compassion? We only have each other here in this valley, so selfishness is entirely self-defeating. ")
sm.sendSay("Had you considered the needs of your kin for even a moment, this wouldn't have happened. ")
sm.sendSay("How can you call yourself a leader if you act with such cruelty? ")
sm.showEffect("Effect/OnUserEff.img/emotionBalloon/noSpeak", 2000, 0, 0, 0, 34292437, 0, 0)
sm.showEffect("Effect/OnUserEff.img/emotionBalloon/noSpeak", 2000, 0, 0, 0, 34292438, 0, 0)
sm.sendDelay(3000)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#Chief Birna... We aren't children listening to your history lessons anymore. ")
sm.sendSay("#face0#We must make tough decisions for the good of our people. Don't treat us like children.")
sm.setInnerOverrideSpeakerTemplateID(9400597) # Gurnardson
sm.sendSay("#face0#That's... That's what I'm saying! ")
sm.setInnerOverrideSpeakerTemplateID(9400600) # Birna
sm.sendSay("I'm treating you as a chief, Kan. That means holding you to a higher standard.")
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400597, True)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400597, True, 100, 80)
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400586, False)
sm.sendDelay(500)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendNext("Don't trouble yourself with lectures, Birna. What matters is that I'm here now. ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400586, True)
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400589, False)
sm.moveNpcByTemplateId(9400586, True, 40, 50)
sm.sendDelay(1000)
sm.moveNpcByTemplateId(9400589, False, 190, 80)
sm.sendDelay(2500)
sm.sendNext("I didn't want to assume... but the letter that brought you here was mine, yes? ")
sm.sendSay("Well then. Welcome to Abrup, such as it is. ")
sm.forcedMove(False, 80)
sm.setParam(57)
sm.sendSay("#bI'm so glad you're okay... Sorry to keep you waiting. ")
sm.setParam(37)
sm.sendSay("Nonsense, friend. You've clearly had your hands full.")
sm.setInnerOverrideSpeakerTemplateID(9400600) # Birna
sm.sendSay("You are every bit the hero our people say you are. You've accomplished so much, even bringing these two hard-headed chiefs together somehow. ")
sm.setParam(57)
sm.sendSay("#bOh, that wasn't me. She gets the credit for uniting the towns. ")
sm.flipNpcByTemplateId(9400589, True)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Hello. I'm Alika, a scholar with the Afinas Dispatch. ")
sm.setInnerOverrideSpeakerTemplateID(9400600) # Birna
sm.sendSay("A pleasure to meet you, Alkia. I'm Birna, chief of Skuas. ")
sm.sendSay("I owe you both my most heartfelt thanks. ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("How difficult this must have all been for you, coming all this way. ")
sm.setParam(57)
sm.sendSay("#bWe've had plenty of help though, from both the Afinas Dispatch and the locals.")
sm.spawnNpc(9400588, -275, -185)
sm.showNpcSpecialActionByTemplateId(9400588, "summon", 0)
sm.moveNpcByTemplateId(9400588, False, 80, 50)
sm.sendDelay(1200)
sm.setParam(37)
sm.sendNext("Ah... Thank you, thank you... You have no idea how much this means to me. ")
sm.sendSay("After my granddaughter disappeared, I searched every corner of Abrup looking for her, for any sign of her. ")
sm.sendSay("A day came soon after when the forest wind stopped and everything froze. After that, the monsters began changing. ")
sm.sendSay("I had no idea how dire the situation was. Fortunately Elva here came to rescue me from the mounting danger. ")
sm.sendSay("Here in Skuas I was safe, but I couldn't search for my granddaughter, or even wait for her at our cabin. All I could do was write letters begging for help. ")
sm.sendSay("I've written hundreds of letters, and you are the only person who came. ")
sm.setParam(57)
sm.sendSay("#bBut I couldn't find any trace of her, either...")
sm.setParam(37)
sm.sendSay("Please, don't be sorry. What you've done here is a far greater thing than helping one old woman. ")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Umm... I brought the picture from the cabin. ")
sm.moveNpcByTemplateId(9400580, False, 50, 50)
sm.sendDelay(1000)
sm.showEffect("Effect/OnUserEff.img/questEffect/PL_MONAD1/6", 0, 0, 0, 0, 34292435, 0, 0)
sm.sendDelay(2000)
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400580, True, 50, 50)
sm.sendDelay(2000)
sm.flipNpcByTemplateId(9400580, False)
sm.showEffect("Effect/OnUserEff.img/questEffect/PL_MONAD1/6", 0, 0, 0, 0, 34292434, 0, 0)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendNext("Oh, goodness... Thank you so much, dear. My one regret when I left my cabin was leaving this precious picture behind. ")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#I'm sorry about what happened to your granddaughter. ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("She's strong. I have a feeling we'll be reunited soon. ")
sm.setParam(57)
sm.sendSay("#bShe's... very special, isn't she? ")
sm.setParam(37)
sm.sendSay("Yes. No one is as special as my Blanche... ")
sm.sendDelay(250)
sm.showEffect("Effect/OnUserEff.img/emotionBalloon/exclamation", 1000, 0, 0, 0, 34304857, 0, 0)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendNext("Blanche...? Blanche was taken too? ")
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400587, True)
sm.sendDelay(250)
sm.forcedFlip(True)
sm.sendDelay(250)
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(1000)
sm.setParam(57)
sm.sendNext("#bYes, the letter that brought me here was about a missing granddaughter. And that letter was from Sanaan. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Sanaan saved us all. ")
sm.sendDelay(1000)
sm.showEffect("Effect/OnUserEff.img/emotion/shade", 0, 0, 0, 0, 34304857, 0, 0)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendNext("B-but Blanche... Did Blanche... We...? ")
sm.sendDelay(1000)
sm.showEffect("Effect/OnUserEff.img/emotion/shade", 0, 0, 0, 0, 34304857, 0, 0)
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400588, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400588, True, 100, 140)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face1#... ")
sm.moveNpcByTemplateId(9400587, True, 150, 140)
sm.sendDelay(1000)
sm.forcedFlip(True)
sm.sendDelay(250)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(1000)
sm.setParam(57)
sm.sendNext("#bWhat's Ullan trying to say? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("It's nothing, just something from the past. ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#... ")
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendSay("She still remembers what happened back then... ")
sm.sendSay("But if you're stuck in the past for too long, you can never change the future. ")
sm.sendSay("Ignoring our problems accomplishes nothing...")
sm.sendSay("It's a shame that some people seem to forget that. ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face1#Very true...")
sm.setInnerOverrideSpeakerTemplateID(9400600) # Birna
sm.sendSay("Only when we acknowledge our past mistakes can we improve. Don't you agree? ")
sm.sendSay("It may have taken longer than it should, but these people need to experience every step. ")
sm.spawnNpc(9400581, -400, -85)
sm.showNpcSpecialActionByTemplateId(9400581, "summon", 0)
sm.spawnNpc(9400582, -480, -85)
sm.showNpcSpecialActionByTemplateId(9400582, "summon", 0)
sm.spawnNpc(9400583, -540, -85)
sm.showNpcSpecialActionByTemplateId(9400583, "summon", 0)
sm.moveNpcByTemplateId(9400581, False, 250, 80)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400582, False, 250, 80)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400583, False, 250, 80)
sm.sendDelay(4000)
sm.sendDelay(3000)
sm.setInnerOverrideSpeakerTemplateID(9400586) # Sanaan
sm.sendNext("There are many things I want to tell to you, #h0#. But I am not the only one who needs you now. ")
sm.sendSay("Once you have attended to your duties, come and sit with me for a chat.")
sm.sendDelay(1000)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.sendNext("#h0#, I know it's not much, but please accept this. \r\nI'm truly grateful to you for coming here and uniting the people of Abrup.")
sm.playExclSoundWithDownBGM("Field.img/masteryBook/EnchantSuccess", 100)
sm.completeQuestNoCheck(64103)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/06/23/13/36")
sm.createQuestWithQRValue(25980, "normal=#164#119#88#87#;hard=#")
sm.warp(867202303)
