# id 910090304 (Partem : Base Camp), field 910090304
sm.changeBGM("Bgm51.img/ThePartemRuins", 0, 0)
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.hideUser(True)
sm.setSpeakerType(3)
sm.setParam(549)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face4#Argh... Ugh...")
sm.sendDelay(1000)
sm.sendNext("#face4#Almost...there...")
sm.sendDelay(500)
sm.sendDelay(4500)
sm.createFieldTextEffect("#fnArial##fs18#Later, at the Base Camp", 100, 1000, 6, -50, -50, 1, 4, 0, 0, 0)
sm.playSound("Sound/SoundEff.img/pathfinder/down", 100)
sm.sendDelay(1000)
sm.onLayer(500, "00", 0, -80, 1, "Effect/Direction22.img/effect/PF_baseC/0", 4, False, -1, False)
sm.sendNext("#face4#Nnnngh... uggh...")
sm.sendDelay(1000)
sm.sendNext("#face5#Feels like...my innards are on fire. What the heck HAPPENED back there? What was up with that super-ominous energy?")
sm.sendSay("#face5#Was it because I touched the relic? Is this one of those creepy curses you always hear stories about?")
sm.offLayer(500, "00", False)
sm.onLayer(500, "01", 0, -80, 1, "Effect/Direction22.img/effect/PF_baseC/1", 4, False, -1, False)
sm.sendSay("#face5#Guess my mentor was right. She was always saying that in this line of work, danger nips at curiosity's heels. Probably should've taken that part more seriously.")
sm.onLayer(1500, "02", 0, -80, 1, "Effect/Direction22.img/effect/PF_baseC/2", 4, False, -1, False)
sm.sendDelay(2000)
sm.offLayer(1000, "02", False)
sm.onLayer(2500, "03", 0, -80, 1, "Effect/Direction22.img/effect/PF_baseC/3", 4, False, -1, False)
sm.sendDelay(3000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(3003658) # Athena Pierce
sm.sendNext("Congratulations, #h0#. You've soaked up everything I've taught you like a sponge. But now, it's time to head out and explore the world for yourself.")
sm.sendSay("I'm certain it won't be long before you have a quiver full of tales to tell, stories from your own adventures.")
sm.sendSay("After all, having observed your growth as you've trained, I can say with confidence that your daring and curiosity exceed even that of your fellow Explorers.")
sm.sendSay("However...")
sm.sendDelay(1000)
sm.sendNext("I want you to be aware that I worry for you, for those exact same reasons.")
sm.sendSay("Curiosity can be the torchlight that illuminates heretofore-unseen paths, but it can also be the upended candle that sets the house ablaze.")
sm.sendSay("That's why, if you remember anything you've learned from me, I want you to remember that in this line of work, danger tends to follow the curious.")
sm.sendSay("And to that end, you must learn to control your curiosity. Know when to indulge it, and when to deny it.")
sm.offLayer(1000, "03", False)
sm.sendDelay(1500)
sm.onLayer(1500, "04", 0, -80, 1, "Effect/Direction22.img/effect/PF_baseC/2", 4, False, -1, False)
sm.sendDelay(2000)
sm.offLayer(300, "01", False)
sm.sendDelay(500)
sm.offLayer(3000, "04", False)
sm.sendDelay(1500)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face5#B-but I...")
sm.sendDelay(1500)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.warp(910090305)
