# id 450003430 (Lachelein Ballroom : Bright Ballroom), field 450003430
if sm.hasQuest(34319):
    sm.createQuestWithQRValue(34340, "enter=4")
    sm.lockInGameUI(True, False)
    sm.changeBGM("Bgm00.img/Silence", 0, 0)
    sm.blind(True, 255, 0, 0, 0, 0)
    sm.setSpeakerType(3)
    sm.setParam(37)
    sm.setColor(1)
    sm.setInnerOverrideSpeakerTemplateID(3003251) # Protective Mask
    sm.sendNext("#face0##h0#, who do you think the residents of Lachelein really are?")
    sm.setParam(57)
    sm.sendSay("Who they really are?")
    sm.setParam(37)
    sm.sendSay("#face0#When the music box was destroyed, knowledge of the outside world \r\nflooded in. Of course, coming from the outside world yourself, \r\nyou must know all about the Arcane River.")
    sm.setParam(57)
    sm.sendSay("Err...")
    sm.setParam(37)
    sm.sendSay("#face0#The Arcane River is a strange world, newly born. \r\nBut then #bwhere did the people of Lachelein come from?#k")
    sm.setParam(57)
    sm.sendSay("I'd wondered that myself.")
    sm.setParam(37)
    sm.sendSay("#face0#This is what I think, #h0#. \r\n#bThey are Erdas.#k Shaped into human form, and blinded by a dream of being human.")
    sm.setParam(57)
    sm.sendSay("I suppose that's possible...")
    sm.setParam(37)
    sm.sendSay("#face0#That would mean we're little more than clumps of energy. But if that's true, \r\nwhat should we do about it?")
    res = sm.sendNext("#face0##h0#... I want the truth. Do you think Erdas have '#bsouls#k'?\r\n#b#L0# Of course!#l\r\n#L1# I don't know.#l\r\n#L2# No.#l")
    sm.sendNext("#face0#Maybe you're right... Or maybe not.")
    sm.sendSay("#face0#Is struggling to live proof of a soul?")
    sm.sendSay("#face0#Perhaps all of our efforts are meaningless.")
    sm.blind(True, 255, 0, 0, 0, 0)
    sm.sendDelay(1200)
    sm.blind(False, 0, 0, 0, 0, 1000)
    sm.sendDelay(1400)
    sm.changeBGM("Bgm46.img/LachelntheIllusionCity", 0, 0)
    sm.lockInGameUI(False, True)
