# id 910090310 (Partem : Gorgonz's Place), field 910090310
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.setMapTaggedObjectVisible("1", False, 0, 0)
sm.setMapTaggedObjectVisible("2", False, 0, 0)
sm.forcedFlip(True)
sm.forcedFlip(False)
sm.zoomCamera(0, 1500, 0, 200, -200)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendNext("#face0#In a couple minutes, the sun will hit the top of the hill. Before that happens, you need to put something related to whatever it is you're looking for on the base of the compass.")
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(1000)
sm.forcedMove(False, 120)
sm.sendDelay(1000)
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendNext("#face0##b(You pull out the Relic and place it on the compass's pedestal. The sunlight grows brighter, seeming to bathe the entire hill in its warm glow.)#k")
sm.sendDelay(1000)
sm.setMapTaggedObjectVisible("1", True, 0, 0)
sm.sendDelay(500)
sm.setMapTaggedObjectVisible("2", False, 0, 0)
sm.playSound("Sound/SoundEff.img/pathfinder/compass", 100)
sm.sendDelay(1000)
sm.zoomCamera(2000, 1000, 2000, -170, -200)
sm.forcedMove(True, 120)
sm.sendDelay(2500)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face2#Wow, it actually worked!")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face3#Where the light's pointing... I feel like I've been in that area of the forest before.")
sm.sendSay("#face3##b(You vaguely remember the location the compass is pointing toward as being near the ruins, though even to your trained eyes it seemed merely a place overgrown with vegetation. Now you're curious what secrets may be hidden there.)#k")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendSay("#face0#It looks like it's leading us closer to the ruins. Maybe if we go there, we'll find something connected to those loud noises that always keep us on edge.")
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendSay("#face0#The ruins? Yikes. Well, have a nice trip. Tell me all about it when you get back. I'm curious, but not quite curious enough to overcome my crippling fear. Wait, did I say 'crippling fear'? What I meant to say is that I'm just really busy. With, uh... Research. Yeah, let's go with that.")
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendSay("#face0#Do you seriously expect me to believe you're that self-motivated when you won't even fix your magic compass without other people helping out? Well, do what you want. Me and the Explorer are gonna check it out. Byeeeeee.")
sm.sendDelay(500)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(35922)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/07/08/13/46")
sm.warp(100051030)
