# id 867200851 (Abrup Basin : Abandoned Village Camp), field 867200851
sm.lockInGameUI(True, False)
sm.spawnNpc(9400580, 390, 300)
sm.showNpcSpecialActionByTemplateId(9400580, "summon", 0)
sm.spawnNpc(9400584, 450, 300)
sm.showNpcSpecialActionByTemplateId(9400584, "summon", 0)
sm.sendDelay(300)
sm.forcedFlip(True)
sm.forcedMove(False, 50)
sm.sendDelay(600)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#bAlika, here. Firewood and meat. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Thank you, #h0#. This will make a huge difference for our people. ")
sm.setParam(57)
sm.sendSay("#bYes... I was also thinking... If you could make a soup with it, we could probably feed everyone. ")
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face1#Ah. Soup... ")
sm.sendDelay(1000)
sm.sendNext("#face3#Hmm... ")
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(1000)
sm.sendNext("#face3#Ah! Janyt, have you... made soup before? ")
sm.sendDelay(1000)
sm.sendDelay(3000)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400580, 4878499)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400584, 4878499)
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(1000)
sm.sendDelay(1000)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400580, 4878499)
sm.forcedFlip(True)
sm.forcedMove(True, 40)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400580, True, 50, 50)
sm.setParam(57)
sm.sendNext("#bUh... Look, all you do is start a fire...")
sm.sendSay("#bPut water in the pot...")
sm.sendSay("#bPut the pot over the fire... ")
sm.sendSay("#bWhen the water boils, put the meat and spices in... and done! ")
sm.playSound("Sound/PL_MONAD.img/EP1/ACT2/simmer", 128)
sm.forcedFlip(True)
sm.showEffect("Effect/OnUserEff.img/emotion/oh", 0, 0, 0, 0, 32823501, 0, 0)
sm.sendDelay(1000)
sm.setParam(37)
sm.sendNext("#face0#Oh! Ha ha, that was rather easy. My book made it sound much more complicated... ")
sm.setParam(57)
sm.sendSay("#bYour book? A cookbook? ")
sm.setParam(37)
sm.sendSay("#face4#I suppose so. It said the meat had to be prepared in half-inch cubes, and the carrots, celery, peppers, and potatoes must be sliced thin. I would have to chop onions, leeks, and mushrooms, and mince garlic. Then you blanch tomatoes by boiling, cooling in cold water, and peeling... ")
sm.setParam(57)
sm.sendSay("#bI'm gonna stop you there, because all we have is meat and salt. ")
sm.setParam(37)
sm.sendSay("#face0#I see. Well then! You must be quite talented to cook with just two ingredients. ")
sm.sendSay("#face0#So... now what do we do? ")
sm.setParam(57)
sm.sendSay("#bWe just wait! That's it! ")
sm.forcedFlip(True)
sm.sendDelay(300)
sm.forcedMove(True, 115)
sm.sendDelay(1000)
sm.forcedFlip(True)
sm.sendDelay(300)
sm.forcedAction(29, 99999999)
sm.sendDelay(300)
sm.moveNpcByTemplateId(9400580, True, 30, 50)
sm.sendDelay(2100)
sm.showNpcSpecialActionByTemplateId(9400580, "sit", -1)
sm.sendDelay(3000)
sm.spawnNpc(9400592, 700, 320)
sm.showNpcSpecialActionByTemplateId(9400592, "summon", 0)
sm.moveNpcByTemplateId(9400592, True, 390, 100)
sm.sendDelay(3000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendNext("#face1#Uh... #h0#... ")
sm.setParam(57)
sm.sendSay("#bAh, Aruhi. You're looking... better today? ")
sm.setParam(37)
sm.sendSay("#face1#Oh, you bet! I've stayed on the straight and narrow since we HIC! left Kaptafel! ")
sm.sendSay("#face1#Seriously. I'm serious. Please believe me. Oh! This is water! ")
sm.setParam(57)
sm.sendSay("#bAll right, I believe you. Good job. ")
sm.setParam(37)
sm.sendSay("#face0#Uh... So, I heard earlier... You came here because of a letter asking you to find someone's granddaughter...? ")
sm.setParam(57)
sm.sendSay("#bAh, yes. That's right. (He must have overheard the conversation with Vice Captain Butler.) ")
sm.spawnNpc(9400587, 700, 320)
sm.showNpcSpecialActionByTemplateId(9400587, "summon", 0)
sm.moveNpcByTemplateId(9400587, True, 320, 100)
sm.setParam(37)
sm.sendSay("#face0#I-I saw who did it! ")
sm.setParam(57)
sm.sendSay("#bYou did? ")
sm.setParam(37)
sm.sendSay("#face0#Yes! I swear I did! Look, I know my reputation isn't the best but you HIC! have to believe me! ")
sm.sendSay("#face1#My daughter, the townspeople, and probably the girl you're looking for, too... I saw who took them! ")
sm.setParam(57)
sm.sendSay("#bPlease, go on! ")
sm.spawnNpc(9400588, 700, 320)
sm.showNpcSpecialActionByTemplateId(9400588, "summon", 0)
sm.startQuest(64161)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#You must be tired. Please don't waste your energy on useless prattle. ")
sm.sendSay("#face0#This is the rambling of a broken man who can't cope with the hand life has dealt him... ")
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendSay("#face0#I'm telling the truth! I've cleaned up my act, Kan. You can trust me! ")
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400587, True, 210, 100)
sm.sendDelay(600)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#How can you say that when you still reek of your vices? ")
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendSay("#face0#I... I... Blast you, Kan! I've had enough of your judging! You've never had any faith in me, even before it all fell apart. ")
sm.sendSay("#face0#Blame HIC! whatever you want. I've got nothing to prove to you... ")
sm.sendDelay(900)
sm.flipNpcByTemplateId(9400587, False)
sm.sendDelay(600)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#...Get ahold of yourself, man. ")
sm.setInnerOverrideSpeakerTemplateID(9400592) # Aruhi
sm.sendSay("#face0#Ha! Why should I? You've ruined us all anyway... ")
sm.setParam(57)
sm.sendSay("#bAruhi, please. Tell me what you saw. ")
sm.setParam(37)
sm.sendSay("#face0#Forget it... HIC! Nothing I say will bring back my wife... my daughter... I've done enough...")
sm.completeQuestNoCheck(64038)
sm.startQuest(64039)
sm.moveNpcByTemplateId(9400592, True, 500, 100)
sm.sendDelay(1000)
sm.moveNpcByTemplateId(9400588, True, 410, 100)
sm.sendDelay(2000)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendNext("Dad... How could you? ")
sm.sendSay("You don't care about anyone's feelings, do you? You just kick them while they're down. ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#... ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400587, True)
sm.sendDelay(250)
sm.moveNpcByTemplateId(9400587, True, 500, 100)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendNext("Ugh! ")
sm.sendSay("Aruhi and Dad just cause problems. These grown-ups, I swear... ")
sm.setParam(57)
sm.sendSay("#bWhy shouldn't we consider Aruhi's account of the culprits? ")
sm.setParam(37)
sm.sendSay("Really? Have you seen the way he acts? There might be a little truth in there but you gotta dig it out from under a mountain of ramblings.")
sm.setParam(57)
sm.sendSay("#bSo how can I learn the truth? ")
sm.setParam(37)
sm.sendSay("Well, I've picked out the bits that are the same every time he tells his story. He says that a dozen people in white rock-hard armor took everyone to a giant dish in the forest and disappeared! ")
sm.setParam(57)
sm.sendSay("#bOkay... I mean, that could have happened. Maple World is a weird place... ")
sm.setParam(37)
sm.sendSay("Hey, I've lived in Abrup my whole life. Same goes for Dad, Aruhi, and just about all of the townspeople. ")
sm.sendSay("We've heard stories of people and contraptions like that from time to time. But why would they appear in the woods out here, of all places? ")
sm.sendSay("And then if they DID, why would walking disaster Aruhi be the ONLY one to see ANY of it?")
sm.sendSay("The grown-ups say he made the whole story up to give himself a reason for losing his family. ")
sm.sendSay("After all, if that's what happened, he would never have been able to save them. It wouldn't be his fault. ")
sm.setParam(57)
sm.sendSay("#b...I see. ")
sm.setParam(37)
sm.sendSay("He's probably gone to drown his sorrows. ")
sm.setParam(57)
sm.sendSay("#bHow do you know that? ")
sm.setParam(37)
sm.sendSay("Because it's what he always does. I don't need to see... it just always happens. ")
sm.sendSay("I wish it wasn't this way. I feel bad for him, and I want him to get better. But he never does. ")
sm.sendDelay(1000)
sm.sendNext("Both Aruhi... and Dad. ")
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face0#Ullan... ")
sm.setInnerOverrideSpeakerTemplateID(9400588) # Ullan
sm.sendSay("Sorry, it's a lot to take in. Tomorrow's going to be tough, so we should all get some sleep! ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400588, False)
sm.sendDelay(500)
sm.sendNext("Good night to you, Alika! ")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Sweet dreams, Ullan.")
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400588, False, 500, 100)
sm.sendDelay(500)
sm.sendNext("#face0#Trying to change yourself... It's hard, isn't it? Maybe the hardest task of all. ")
sm.sendSay("#face0#How hard is it for her to keep smiling like she does? I always thought her just a regular girl, but my goodness... she's more mature than some of the adults we deal with. ")
sm.setParam(57)
sm.sendSay("#bBut she is still a child. We owe it to her to spare her as much sorrow as we can. ")
sm.setParam(37)
sm.sendSay("#face0#Agreed. Let's do what we can to ease her burdens. It's a promise! ")
sm.setParam(57)
sm.sendSay("#bPromise... ")
sm.setParam(37)
sm.sendSay("#face1#And if we're going to do that, we all need rest! ")
sm.sendSay("#face1#Good night, #h0#. ")
sm.sendDelay(500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64038, "chk=1;NpcSpeech=94005831/94005912/94005803;dir01=1")
sm.warp(867200852)
