# id 867200620 (Abrup Basin : Village Exit), field 867200620
sm.lockInGameUI(True, False)
sm.spawnNpc(9400585, -725, 340)
sm.showNpcSpecialActionByTemplateId(9400585, "summon", 0)
sm.spawnNpc(9400585, -680, 340)
sm.showNpcSpecialActionByTemplateId(9400585, "summon", 0)
sm.spawnNpc(9400616, -600, 340)
sm.showNpcSpecialActionByTemplateId(9400616, "summon", 0)
sm.spawnNpc(9400592, -550, 340)
sm.showNpcSpecialActionByTemplateId(9400592, "summon", 0)
sm.spawnNpc(9400591, -490, 340)
sm.showNpcSpecialActionByTemplateId(9400591, "summon", 0)
sm.spawnNpc(9400581, -380, 340)
sm.showNpcSpecialActionByTemplateId(9400581, "summon", 0)
sm.spawnNpc(9400587, -300, 340)
sm.showNpcSpecialActionByTemplateId(9400587, "summon", 0)
sm.spawnNpc(9400580, -220, 340)
sm.showNpcSpecialActionByTemplateId(9400580, "summon", 0)
sm.spawnNpc(9400582, -164, 340)
sm.showNpcSpecialActionByTemplateId(9400582, "summon", 0)
sm.spawnNpc(9400589, -85, 340)
sm.showNpcSpecialActionByTemplateId(9400589, "summon", 0)
sm.forcedFlip(True)
sm.sendDelay(1000)
sm.forcedMove(True, 130)
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400580, False, 250, 80)
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400582, False)
sm.flipNpcByTemplateId(9400589, False)
sm.sendDelay(2000)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendNext("#face0##h0#! You made it back! ")
sm.sendDelay(2000)
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendNext("#face0#Well done, everyone. ")
sm.moveNpcByTemplateId(9400589, False, 30, 50)
sm.sendDelay(500)
sm.sendNext("#face0#Is everyone okay? ")
sm.setParam(57)
sm.sendSay("#bYes. Fortunately, there weren't that many. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#Uh... Excuse me, #h0#. I know you're very busy, but can I speak to you? ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#We talked quite a bit while you were off fighting those monsters... ")
sm.sendSay("#face0#Specifically, we discussed who should be leading this caravan. ")
sm.setInnerOverrideSpeakerTemplateID(9400580) # Alika
sm.sendSay("#face0#To cut to the chase... #h0#, can you lead the caravan? ")
sm.sendSay("#face0#Vice Captain Butler, Chief Kan, Peytour, and myself agree. ")
sm.sendSay("#face0#None of us can say that we'd have made a better decision just now. ")
sm.sendSay("#face0#Since we each have our own interests here, none of us is really qualified to make objective decisions for the group. ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(1000)
sm.sendDelay(3000)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400581, 4878499)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400587, 4878499)
sm.sendNext("#face0##h0#, will you help us? ")
sm.flipNpcByTemplateId(9400580, False)
sm.sendDelay(1000)
sm.setParam(57)
sm.sendNext("#bI'm not sure I'm qualified for this either, though. I hardly know anything about Abrup or the knights... ")
sm.setParam(37)
sm.sendSay("#face0#Chief Kan will help you manage our people, and Vice Captain Butler will help you manage our foes. ")
sm.sendSay("#face0#You're the right person for the job BECAUSE you're an outsider. You don't have the strong ties that we do to each other. Please... we need you.")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400580, True)
sm.sendDelay(1000)
sm.sendDelay(500)
sm.sendDelay(2000)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400587, 4878499)
sm.sendDelay(3000)
sm.speechBalloon(True, 0, 0, "...", 2000, 1, 0, 0, 0, 4, 9400581, 4878499)
sm.setParam(57)
sm.sendNext("#bDid everyone agree to this? ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400581) # Butler
sm.sendSay("#face1#...It's only until we reach the next village. ")
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#Yes. It's unanimous. ")
sm.setParam(57)
sm.sendSay("#bAll right. I'll do my best to get everyone there safely. That's all. ")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(9400581) # Butler
sm.sendSay("#face1#I don't need your best. I need results. ")
sm.sendDelay(500)
sm.flipNpcByTemplateId(9400581, True)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400581, True, 500, 200)
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400587, True)
sm.sendDelay(1000)
sm.flipNpcByTemplateId(9400587, False)
sm.sendDelay(500)
sm.moveNpcByTemplateId(9400587, False, 70, 100)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendNext("#face0#Right, well... let's start with directions. ")
sm.sendDelay(1000)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTutoBack/0", True, True, 0, 0, 0)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/0", True, True, 0, 0, 0)
sm.sendNext("#face0#From Kaptafel to the next town is nearly a full day's travel. We'll need to cross the Frozen River as well.")
sm.sendDelay(1000)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/0", False, False, 0, 0, 0)
sm.sendDelay(3000)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/1", True, True, 0, 0, 0)
sm.sendDelay(500)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/1", False, False, 0, 0, 0)
sm.sendNext("#face0#As we travel, food should be your chief concern. ")
sm.sendDelay(2000)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/2", True, True, 0, 0, 0)
sm.sendNext("#face0#Without food, our weaker members will slow down and... might not make it. ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Kan... Isn't there something more important than food? ")
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/2", False, False, 0, 0, 0)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#...Yes, of course. Food is important because our people are the most important part of the caravan.. ")
sm.sendDelay(2000)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/3", True, True, 0, 0, 0)
sm.setInnerOverrideSpeakerTemplateID(9400590) # Slaka
sm.sendNext("#face0#Ha ha ha, ohhh that's a good one! Chief Kan pretending to care about his people, ha ha ha. ")
sm.setInnerOverrideSpeakerTemplateID(9400589) # Peytour
sm.sendSay("#face0#Slaka! Now is not the time! ")
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/3", False, False, 0, 0, 0)
sm.setInnerOverrideSpeakerTemplateID(9400587) # Kan
sm.sendSay("#face0#Keep in mind that every decision you make will have consequences like this. Some will be happy, some will be angry, and some will be sad. ")
sm.sendDelay(2000)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/4", True, True, 0, 0, 0)
sm.sendNext("#face0#That's the problem with leadership. It's impossible to make everyone happy, so every decision is a difficult one. ")
sm.sendDelay(500)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTutoBack/0", False, False, 0, 0, 0)
sm.reservedEffectRepeat("Effect/DirectionPL.img/effect/PL_Abrup_CaravanTuto/4", False, False, 0, 0, 0)
sm.sendDelay(2000)
sm.setParam(57)
sm.sendNext("#bSo, I've got to get everyone to the town across the river by making decisions that everyone can live with. No pressure! ")
sm.setParam(37)
sm.sendSay("#face0#Well, keep in mind that as the journey wears on, people will get tired and less patient with your decisions. ")
sm.sendSay("#face0#And if you add hunger on top of that, morale will drop in a hurry. Hence why food is so important. ")
sm.sendSay("#face0#If you ever need to go over all of your responsibilities, I'd be happy to review for you again anytime. ")
sm.sendSay("#face0#Please... do your best. We want everyone to reach the next town, and not turn on each other.")
sm.sendDelay(500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64006, "WC=0;speed=20;man=200;prog=0;Pt=CaravanP1_chk1;Ec=2;weather=0;max=16;food=450")
sm.warp(867200500)
