# id 867202800 (Abrup Basin : Crimson Snow-Covered Windsleep Forest Junction), field 867202800
sm.lockInGameUI(True, False)
sm.sendDelay(3000)
sm.setSpeakerType(3)
sm.setParam(57)
sm.setColor(1)
sm.sendNext("#b(Red snow... The attack is coming.) ")
sm.sendDelay(3000)
sm.sendNext("#b(When did the Jellyrashes show up...?) ")
sm.forcedMove(True, 600)
sm.sendDelay(3000)
sm.sendNext("#b(Hm... is there anything we could use as rope?) ")
sm.sendDelay(2000)
sm.sendNext("#b(There was that time I saved Alika with a Jellyrash...) ")
sm.sendSay("#b(Would that work?)")
sm.sendSay("#b(There's no time to waste! The town needs to know the attack's coming. Just collect ten and head back fast!)")
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(64133, "dir1=1")
sm.warp(867202810)
