# id 940200121 (Hidden Street : After the War), field 940200121
sm.lockInGameUI(True, False)
sm.hideUser(True)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.sayMonologue("And so, using her powerful ability to manipulate the minds of \r\ndreamers, Lucid hid herself away. When the Elves awoke, they would never know she existed.", 0)
sm.sayMonologue("She immersed herself in a dreamworld of her own making, \r\ncompletely isolated from the outside world.", 0)
sm.sayMonologue("In her dreamworld, Lucid was oblivious to the passage of time.", 0)
sm.sayMonologue("Finally, the terrible war came to an end when the Heroes sealed \r\nthe Black Mage away.", 1)
sm.sayMonologue("...But their victory came at a price. Each one suffered \r\nthe Black Mage's curse in a different way.", 0)
sm.sayMonologue("The Elves of Elluel, their fates being intertwined with Mercedes, \r\nalso suffered a version of the curse, as one after another each was frozen in ice.", 1)
sm.blind(True, 255, 0, 0, 0, 250)
sm.sendDelay(250)
sm.hideUser(False)
sm.lockInGameUI(False, True)
sm.warp(940200122)
