# id 910090308 (Partem : Gorgonz's Place), field 910090308
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.forcedFlip(True)
sm.zoomCamera(0, 1500, 0, 1350, -100)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(4500)
sm.createFieldTextEffect("#fnArial##fs18#Gorgonz's Place", 100, 1000, 6, -50, -50, 1, 4, 0, 0, 0)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendNext("#face0#This is Gorgonz's house. He's probably asleep right now, though, since he tends to stay up late, then naps half the day away.")
sm.sendSay("#face0#Hey Gorgonz! Wake up and roll out of bed for a minute! I need to talk to you!")
sm.sendSay("#face0#Gorgonz! Oh Gorgoooonz!")
sm.sendSay("#face0#Gooorrrrr-goooonzzzz!")
sm.sendSay("#face0#*pant* *pant* Oh wait. I just remembered, there's a surefire way to get him to show.")
sm.sendSay("#face0#Ahem. De.... De-De...")
sm.sendSay("#face0#DEMOGORGONZ!")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face3#Bwah--!")
sm.sendDelay(1000)
sm.spawnNpc(1013351, 1372, -174)
sm.showNpcSpecialActionByTemplateId(1013351, "summon", 0)
sm.moveNpcByTemplateId(1013351, True, 40, 80)
sm.sendDelay(1000)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendNext("#face0#Ahhh, that's what I like to hear. The power, the prestige, the smidge of extra credibility that comes with being addressed by your full name! Anyway, long time no see, kiddo. What's shakin'?")
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendSay("#face0#*sigh* Well, you don't seem to be doing any worse for wear. I was worried when you first said you were moving out of town.")
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendSay("#face0#Worried? For me? I roll with the punches. Whatever the trouble, I'll tough it out. But enough about me. Who's your tall, dark, and shady friend there? Wait, don't tell me you hired your very own assassin?")
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendSay("#face0#Ack! N-no! They're a hero - an Explorer who was passing through the area. We're working together now. ...Did I mention they're super strong?")
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendSay("#face1#Heh heh... At long last, a fellow connoisseur of myth, mystery, and the generally odd! Become my rival and let us scorch each other with the flames of heated scholarly competition!")
sm.setInnerOverrideSpeakerTemplateID(1013350) # Brie
sm.sendSay("#face0#Wh-what? No! This is why people don't come visit you, Gorgonz. Anyway, this Explorer are I here to see you about something important.")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face0#(She told Gorgonz we were investigating the ruins, stepping up the effort because the loud noises were getting worse. Which is...sure, let's just go with that for simplicity's sake.)")
sm.sendSay("#face0#Okay. First things first, what can you tell me about this relic?")
sm.blind(True, 200, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sendNext("#face0#(I showed the relic to Gorgonz, but when he saw it, his face grew pale, just like with Mascarpo and the chief.)")
sm.blind(False, 0, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendNext("#face0#Eeeep! S-sorry, but can you please put that away?")
sm.sendSay("#face0#Yeowza. I don't know where you picked that thing up, but it's got some seriously bad mojo floatin' around it, just like the ruins. Is it connected to the ruins? ...Did you GET it from the ruins?")
sm.setParam(549)
sm.setInnerOverrideSpeakerTemplateID(1013358) # Pathfinder
sm.sendSay("#face0#I'm the one asking the questions here. I heard you observe the ruins. How much do you know about them?")
sm.setParam(37)
sm.setInnerOverrideSpeakerTemplateID(1013351) # Gorgonz
sm.sendSay("#face0#So...here's the thing. I'm no archaeologist. I just like creepy, scary stuff. That's why I hang out near the ruins. I don't really know all that much about them, scientifically speaking.")
sm.sendDelay(1000)
sm.sendNext("#face0#Sorry to be a disappointment. But if there's something in the ruins you're looking for, there IS something I've got that I think can help.")
sm.sendDelay(1000)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.completeQuestNoCheck(35913)
sm.startQuest(11620)
sm.createQuestWithQRValue(15710, "lasttime=19/07/08/13/38")
sm.createQuestWithQRValue(35947, "12=1;2=1;6=1")
sm.createQuestWithQRValue(35948, "00=h0;10=h1;11=h0;02=h1;12=h0;22=h1;13=h0;23=h1;14=h0;15=h0;06=h0;07=h0;16=h0;26=h1;08=h1;17=h0;09=h0;19=h0")
sm.warp(100051030)
