# id 940200130 (Hidden Street : Drifting Thoughts), field 940200130
sm.lockInGameUI(True, False)
sm.hideUser(True)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.zoomCamera(0, 1000, 0, -200, -200)
sm.sendDelay(1000)
sm.blind(False, 0, 0, 0, 0, 1500)
sm.zoomCamera(500, 1000, 500, 50, 0)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot0", 200)
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot1", 200)
sm.sendDelay(300)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot2", 200)
sm.sendDelay(300)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot1", 200)
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot0", 200)
sm.sendDelay(300)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot2", 200)
sm.sendDelay(500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003270) # Lucid
sm.sendNext("#face4#...How long have I been here? How long do I have to stay trapped in here?")
sm.sendSay("#face4#I can't take it anymore... I just want it to stop! Waah...")
sm.sendSay("#face4#Save me, anyone! Please wake me from this terrible nightmare!")
sm.sendSay("#face4#Waaah...")
sm.sendSay("#face4#(Sniffs) Waah...")
sm.sendSay("#face3#...")
sm.sendSay("#face2#...")
sm.sendSay("#face2#...Huh? What is that powerful force... drawing me in? Where am I going?")
sm.sendSay("#face2#Someone's there... Closer now...")
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot0", 200)
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot2", 200)
sm.sendDelay(300)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot1", 200)
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot2", 200)
sm.sendDelay(500)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/foot0", 200)
sm.sendDelay(300)
sm.blind(True, 255, 0, 0, 0, 250)
sm.sendDelay(250)
sm.hideUser(False)
sm.lockInGameUI(False, True)
sm.warp(940200131)
