# id 940200133 (Hidden Street : Commander Lucid), field 940200133
sm.lockInGameUI(True, False)
sm.hideUser(True)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.spineScreen(True, True, False, 0, "Map/Effect3.img/Lacheln/Sense/002","animation","lucid")
sm.bgmVolumeOnly(True)
sm.bgmVolume(40, 2000)
sm.sendDelay(2000)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003272) # Lucid
sm.sendNext("#face6#Ha... Haha... HAHAHA.")
sm.playExclSoundWithDownBGM("Voice3.img/Lucid/E2/0", 128)
sm.sendSay("#face6#It feels like whatever weight's been holding me down has finally lifted...")
sm.playExclSoundWithDownBGM("Voice3.img/Lucid/E2/1", 128)
sm.sendSay("#face6#So... is this his gift? I have never felt such power... It's overwhelming!")
sm.playExclSoundWithDownBGM("Voice3.img/Lucid/E2/2", 128)
sm.sendSay("#face2#Ha... Haha. AHAHAHA!")
sm.playExclSoundWithDownBGM("Voice3.img/Lucid/E2/3", 128)
sm.sendNext("#face2#I have been waiting for this moment, to finally be reborn.")
sm.playExclSoundWithDownBGM("Voice3.img/Lucid/E2/4", 128)
sm.sendSay("#face3#...Now the dream I weave will become reality!")
sm.playExclSoundWithDownBGM("Voice3.img/Lucid/E2/5", 128)
sm.offSpineScreen("lucid", 0, "", 0)
sm.spineScreen(True, False, True, 0, "Map/Effect3.img/BossLucid/Lucid/lusi","animation","")
sm.playSound("Sound/SoundEff.img/ArcaneRiver/lucid_spine", 200)
sm.sendDelay(8500)
sm.bgmVolume(100, 3000)
sm.bgmVolumeOnly(False)
sm.playSound("Sound/SoundEff.img/ArcaneRiver/butterfly1", 200)
sm.spineScreen(True, False, False, 0, "Map/Effect3.img/BossLucid/butterfly2/buterfly","animation","")
sm.sendDelay(2500)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.hideUser(False)
sm.lockInGameUI(False, True)
sm.warp(450003000)
