# id 450003100 (Lachelein : Hideout), field 450003100
if not sm.hasQuest(34326) and sm.hasQuestCompleted(34325):
    sm.createQuestWithQRValue(34340, "enter=7")
    sm.lockInGameUI(True, False)
    sm.removeAdditionalEffect()
    sm.blind(True, 255, 0, 0, 0, 0)
    sm.changeBGM("Bgm00.img/Silence", 0, 0)
    sm.sendDelay(1500)
    sm.setSpeakerType(3)
    sm.setParam(37)
    sm.setColor(1)
    sm.setInnerOverrideSpeakerTemplateID(3003250) # Lucid
    sm.sendNext("#face1#Have you ever struggled to awaken from a dream?")
    sm.playExclSoundWithDownBGM("Voice3.img/Lucid/Q3/0", 128)
    sm.sendSay("#face1#Even though you know you are dreaming, the darkness won't \r\nrelease its hold on you... You are paralyzed, and a feeling of helplessness \r\nwashes over you.")
    sm.playExclSoundWithDownBGM("Voice3.img/Lucid/Q3/1", 128)
    sm.sendSay("#face5#Have you ever felt so bereft of hope? Well, you will soon. \r\nWelcome to your nightmare.")
    sm.playExclSoundWithDownBGM("Voice3.img/Lucid/Q3/2", 128)
    sm.sendDelay(500)
    sm.onLayer(2000, "0", 0, -80, 1, "Map/Effect3.img/Lacheln/0", 4, True, -1, False)
    sm.sendDelay(1500)
    sm.offLayer(1500, "0", False)
    sm.sendDelay(1500)
    sm.playSound("Sound/SoundEff.img/ArcaneRiver/butterfly1", 200)
    sm.spineScreen(True, False, False, 0, "Map/Effect3.img/BossLucid/butterfly2/buterfly","animation","")
    sm.sendDelay(2500)
    sm.blind(True, 255, 0, 0, 0, 0)
    sm.sendDelay(1200)
    sm.blind(False, 0, 0, 0, 0, 1000)
    sm.sendDelay(1400)
    sm.changeBGM("Bgm46.img/LachelntheIllusionCity", 0, 0)
    sm.lockInGameUI(False, True)
