# id 940200131 (Hidden Street : Black Mage Encounter), field 940200131
sm.lockInGameUI(True, False)
sm.hideUser(True)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1000)
sm.blind(False, 0, 0, 0, 0, 1500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003270) # Lucid
sm.sendNext("#face2#...Who are you?")
sm.sendSay("#face2#...You have an ominous aura.")
sm.sendSay("#face1#But maybe you're the one I've been waiting for all this time...")
sm.sendSay("#face1#Can I go to where you are?")
sm.blind(True, 200, 0, 0, 0, 1300)
sm.sendDelay(1600)
sm.sayMonologue("Eternal life, and knowledge beyond bounds.", 0)
sm.sayMonologue("...A new world.", 0)
sm.sayMonologue("It was an enticing offer for Lucid, a simple Elf-child of Elluel who had never been beyond her kingdom's borders.", 0)
sm.sayMonologue("A plan beyond fathoming, and the raw, absolute power to bring it to fruition...", 0)
sm.sayMonologue("To hear that such a powerful being needed her...", 0)
sm.sayMonologue("She took hold of the Black Mage's hand without a moment's hesitation.", 1)
sm.blind(True, 255, 0, 0, 0, 250)
sm.sendDelay(250)
sm.hideUser(False)
sm.lockInGameUI(False, True)
sm.warp(940200132)
