# id 402090009 (null), field 402090009
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.onLayer(500, "d0", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/11/0", 4, True, -1, False)
sm.sendDelay(1500)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3001504) # Albaire
sm.sendNext("#face0#You are weak.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/C/1", 100)
sm.sendSay("#face0#Accept it.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/C/2", 100)
sm.sendSay("#face0#Your grand ideals aren't going to save anyone.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/C/3", 100)
sm.sendSay("#face1#Don't get in the High Flora's way any more.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/C/4", 100)
sm.sendSay("#face0#This time, I'll make sure you don't survive.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/C/5", 100)
sm.sendDelay(1000)
sm.offLayer(300, "d0", False)
sm.spineScreen(False, False, True, 0, "Effect/Direction17.img/effect/ark/medal/0/ark_medal","animation","01")
sm.playSound("Sound/SoundEff.img/cadena/pendant", 100)
sm.sendDelay(6000)
sm.onLayer(500, "0", 0, -10, 0, "Effect/Direction17.img/effect/ark/noise/1366/0", 4, True, -1, True)
sm.playSound("Sound/SoundEff.img/radionoise", 100)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(300)
sm.onLayer(500, "2", 0, -10, 0, "Effect/Direction17.img/effect/ark/noise/1366/2", 4, True, -1, True)
sm.onLayer(500, "3", 0, -10, 0, "Effect/Direction17.img/effect/ark/noise/1366/3", 4, True, -1, True)
sm.offLayer(300, "0", False)
sm.sendDelay(2000)
sm.changeBGM("Bgm48.img/Memory", 0, 0)
sm.sendDelay(1000)
sm.onLayer(500, "d3", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/5/0", 4, True, -1, False)
sm.sendDelay(1500)
sm.onLayer(100, "d4", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/5/1", 4, True, -1, False)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendNext("#face0#We did it, Albaire!")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/1", 100)
sm.setInnerOverrideSpeakerTemplateID(3001505) # Albaire
sm.sendSay("#face0#Yeah, I wasn't sure you'd actually make it!")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/E/2", 100)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendSay("#face1#I proved you wrong, didn't I? Now we're headed into real battle instead of drills.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/3", 100)
sm.sendSay("#face1#We're finally going to make a difference in Grandis!")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/4", 100)
sm.sendSay("#face1#But I'm also a little scared.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/5", 100)
sm.sendSay("#face2#Sometimes I even have nightmares about it. I'm sure we'll be fine though.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/6", 100)
sm.setInnerOverrideSpeakerTemplateID(3001505) # Albaire
sm.sendSay("#face3#Ark, I swore to protect the people who matter to me, and that includes you.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/E/7", 100)
sm.sendSay("#face3#I'll always be there to protect you.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/E/8", 100)
sm.sendSay("#face3#Even if you are the worst soldier on the battlefield!")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/E/9", 100)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendSay("#face3#Ha! You think you could survive without me?!")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/10", 100)
sm.sendSay("#face3#You won't even make it to Colonel without my help.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/11", 100)
sm.setInnerOverrideSpeakerTemplateID(3001505) # Albaire
sm.sendSay("#face0#Then it's a good thing you aren't going to abandon me out there.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/E/12", 100)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendSay("#face3#Yeah. I'll protect you too. Just don't mess up too bad.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/13", 100)
sm.setInnerOverrideSpeakerTemplateID(3001505) # Albaire
sm.sendSay("#face1#All right, I promise.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/E/14", 100)
sm.offLayer(300, "d3", False)
sm.offLayer(300, "d4", False)
sm.sendDelay(1500)
sm.setInnerOverrideSpeakerTemplateID(3001500) # Ark
sm.sendNext("#face5#I thought we were just joking around that day.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/16", 100)
sm.sendSay("#face5#But he really was always there for me.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/E/Male/17", 100)
sm.sendDelay(1000)
sm.onLayer(500, "0", 0, -10, 0, "Effect/Direction17.img/effect/ark/noise/1366/0", 4, True, -1, True)
sm.playSound("Sound/SoundEff.img/radionoise", 100)
sm.sendDelay(300)
sm.offLayer(300, "0", False)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendNext("#face4#I have to warn them.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/F/Male/1", 100)
sm.onLayer(500, "d9", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/3/0", 4, True, -1, False)
sm.setInnerOverrideSpeakerTemplateID(3001506) # Limbo
sm.sendSay("#face1#You are not to leave the base without approval, Second Lieutenant Ark.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/3", 100)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendSay("#face4#...")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/F/Male/4", 100)
sm.setInnerOverrideSpeakerTemplateID(3001506) # Limbo
sm.sendSay("#face1#I also heard you hesitated in the last battle. It nearly cost us our victory.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/5", 100)
sm.offLayer(300, "d9", False)
sm.onLayer(500, "d10", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/3/1", 4, True, -1, False)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendSay("#face4#Victory? More like massacre. How can you say you fight for peace?")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/F/Male/6", 100)
sm.setInnerOverrideSpeakerTemplateID(3001506) # Limbo
sm.sendSay("#face1#Do you really think I care about peace?")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/7", 100)
sm.sendSay("#face1#From the moment you joined, I could see your doubt.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/8", 100)
sm.sendSay("#face1#The unrest in your heart shows in your eyes.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/9", 100)
sm.sendSay("#face1#I just needed you to prove you were a traitor.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/10", 100)
sm.sendSay("#face0#And now you'll pay for it.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/11", 100)
sm.sendDelay(300)
sm.offLayer(300, "d10", False)
sm.blind(True, 255, 240, 240, 240, 1300)
sm.sendDelay(1600)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendNext("#face5#Aaaaaaagh!!")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/F/Male/12", 100)
sm.setInnerOverrideSpeakerTemplateID(3001506) # Limbo
sm.sendSay("#face0#Your soul is mine!")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/F/13", 100)
sm.sendDelay(2000)
sm.onLayer(500, "0", 0, -10, 0, "Effect/Direction17.img/effect/ark/noise/1366/0", 4, True, -1, True)
sm.playSound("Sound/SoundEff.img/radionoise", 100)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.sendDelay(300)
sm.offLayer(300, "0", False)
sm.sendDelay(1000)
sm.sayMonologue("#fs22##fnArial#\r\n\r\nI did all I could, but it wasn't enough.", 0)
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/A/Male/1", 100)
sm.sayMonologue("#fs22##fnArial#Maybe it was always meant to end this way.", 0)
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/A/Male/2", 100)
sm.sayMonologue("#fs22##fnArial#\r\nOr maybe it was just me...", 0)
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/A/Male/3", 100)
sm.sayMonologue("#fs22##fnArial#\r\n\r\n\r\nIs this how it ends?", 1)
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/A/Male/4", 100)
sm.sendDelay(7100)
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/A/Male/5", 100)
sm.createFieldTextEffect("#fnﾳﾪﾴﾮﾰ￭ﾵ￱ ExtraBold##fs35#I'm sorry I won't be there for you, Albaire.", 50, 6600, 4, 0, 0, 0, 4, 3, 300, 300)
sm.sendDelay(3200)
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/A/Male/6", 100)
sm.createFieldTextEffect("#fnﾳﾪﾴﾮﾰ￭ﾵ￱ ExtraBold##fs35#Please forgive me.", 50, 2700, 4, 0, 0, 0, 4, 3, 300, 300)
sm.sendDelay(1000)
sm.onLayer(500, "d11", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/4/0", 4, True, -1, False)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(3001502) # Ark
sm.sendNext("#face5#Albaire? What is he doing here?")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Back/G/Male/1", 100)
sm.setInnerOverrideSpeakerTemplateID(3001504) # Albaire
sm.sendSay("#face2#Ark, I don't understand.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/2", 100)
sm.setInnerOverrideSpeakerTemplateID(3001505) # Albaire
sm.sendSay("#face2#How could you turn on us like this?")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/3", 100)
sm.sendSay("#face2#I thought we wanted the same things.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/4", 100)
sm.offLayer(300, "d11", False)
sm.onLayer(500, "d12", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/4/1", 4, True, -1, False)
sm.sendDelay(1000)
sm.sendNext("#face3#Still... I promised to protect you no matter what.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/5", 100)
sm.sendSay("#face3#Even if I have to sacrifice everything to do it.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/6", 100)
sm.setInnerOverrideSpeakerTemplateID(3001504) # Albaire
sm.sendSay("#face3#I can't let you die. I'll stop the specter ritual.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/7", 100)
sm.spineScreen(True, False, True, 0, "Map/Effect2.img/HofM/ACT1_bye/whiteback2/skeleton","animation","")
sm.sendDelay(5000)
sm.setInnerOverrideSpeakerTemplateID(3001505) # Albaire
sm.sendNext("#face3#Haaah!!")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Back/G/8", 100)
sm.sendDelay(2000)
sm.offLayer(500, "d12", False)
sm.onLayer(500, "0", 0, -10, 0, "Effect/Direction17.img/effect/ark/noise/1366/0", 4, True, -1, True)
sm.playSound("Sound/SoundEff.img/radionoise", 100)
sm.sendDelay(500)
sm.offLayer(300, "0", False)
sm.offLayer(300, "2", False)
sm.offLayer(300, "3", False)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.onLayer(500, "d13", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/11/1", 4, True, -1, False)
sm.onLayer(500, "d14", 0, -50, -1, "Effect/Direction17.img/effect/ark/illust/11/2", 4, True, -1, False)
sm.sendDelay(1000)
sm.setInnerOverrideSpeakerTemplateID(3001500) # Ark
sm.sendNext("#face6#What's happened to you?")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Now/D/Male/1", 100)
sm.setInnerOverrideSpeakerTemplateID(3001504) # Albaire
sm.sendSay("#face1#Me? I'm not the one who's changed.")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/D/2", 100)
sm.setInnerOverrideSpeakerTemplateID(3001500) # Ark
sm.sendSay("#face6#But... you wanted to protect people.")
sm.playExclSoundWithDownBGM("Voice4.img/Ark/Now/D/Male/3", 100)
sm.setInnerOverrideSpeakerTemplateID(3001504) # Albaire
sm.sendSay("#face0#Like you said, war for peace was all a lie, right?")
sm.playExclSoundWithDownBGM("Voice4.img/ArkNpc/Now/D/4", 100)
sm.offLayer(300, "d14", False)
sm.sendDelay(1000)
sm.offLayer(300, "d13", False)
sm.onLayer(500, "d15", 0, -80, -1, "Effect/Direction17.img/effect/ark/illust/11/3", 4, True, -1, False)
sm.sendDelay(1000)
sm.offLayer(3000, "d15", False)
sm.sendDelay(3000)
sm.bgmVolume(0, 2000)
sm.sendDelay(2300)
sm.showFadeTransition(0, 1000, 3000)
sm.zoomCamera(0, 1000, 2147483647, 2147483647, 2147483647)
sm.moveCamera(True, 0, 0, 0)
sm.sendDelay(300)
sm.removeOverlapScreen(1000)
sm.moveCamera(True, 0, 0, 0)
sm.lockInGameUI(False, True)
sm.warp(402090013)
