# id 450002204 (Chu Chu Island : Chu Chu Island), field 450002204
sm.startQuest(34200)
sm.completeQuestNoCheck(34200)
sm.lockInGameUI(True, False)
sm.removeAdditionalEffect()
sm.blind(True, 255, 0, 0, 0, 0)
sm.forcedMove(False, 2)
sm.zoomCamera(0, 1000, 0, 570, 70)
sm.createQuestWithQRValue(18418, "B=34840")
sm.spawnNpc(3003167, 796, -64)
sm.showNpcSpecialActionByTemplateId(3003167, "summon", 0)
sm.forcedInput(4)
sm.blind(True, 255, 0, 0, 0, 0)
sm.sendDelay(1200)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendDelay(1400)
sm.sendDelay(3000)
sm.zoomCamera(3000, 1000, 5000, 610, 20)
sm.sendDelay(3000)
sm.setSpeakerType(3)
sm.setParam(37)
sm.setColor(1)
sm.setInnerOverrideSpeakerTemplateID(3003150) # Lyon
sm.sendNext("Hey!")
sm.setParam(57)
sm.sendSay("...")
sm.setParam(37)
sm.sendSay("Wake up, meow!")
sm.sendSay("Err... Roar. I meant roar.")
sm.sendSay("Anyway... Since #ba bop on the head#k knocked them out, maybe another good bop will wake them up? Makes sense to me.")
sm.sendSay("#face1##fs50#Hyaa!")
sm.blind(True, 300, 255, 255, 255, 0)
sm.forcedInput(0)
sm.sendDelay(2000)
sm.blind(False, 0, 0, 0, 0, 1000)
sm.sendNext("#face0#Hey look, you're awake! How are you feeling buddy? Heh!")
sm.setParam(57)
sm.sendSay("Oww... My head. Huh? I was just on the #briver#k and...")
sm.setParam(37)
sm.sendSay("#face1#Hm?! Yes, the #briver#k! This river goes all over! Heh!")
sm.setParam(57)
sm.sendSay("I... don't think this is the same river...")
sm.sendSay("By the way, who are you?")
sm.setParam(37)
sm.sendSay("Oh! Me? I'm the #bgreatest hero#k and #bchief#k that Chu Chu Island has ever seen! I am as #bwise as I am strong#k, and no one is more #brespected#k by the villagers...")
sm.sendSay("#face0#I'm #bLyon#k, Meow!")
sm.setParam(57)
sm.sendSay("Meow?")
sm.setParam(37)
sm.sendSay("H-huh? You're hearing things. I clearly just roared.")
sm.setParam(57)
sm.sendSay("I distinctly heard a meow. Aren't you a #blion#k?")
sm.sendSay("Wait... Ahh! It's a #blion#k! Or at least some kind of man-lion-thing...")
sm.forcedMove(True, 50)
sm.sendDelay(1000)
sm.forcedMove(False, 1)
sm.setParam(37)
sm.sendNext("#face0##bLion#k? What's that? Sounds like food!")
sm.sendSay("Hey, hey, don't wander off. Come over here, let me look at you. Those #bwounds#k you got from Muto definitely need some attention#k.")
sm.setParam(57)
sm.sendSay("Ahh! Stay back!")
sm.forcedMove(True, 50)
sm.sendDelay(1000)
sm.forcedMove(False, 1)
sm.setParam(37)
sm.sendNext("#face0#Heh. Looks like #bMuto#k gave you a pretty good knock here! How about we head down to the village for now? After a little grub and a nap, you should be right as rain!")
sm.setParam(57)
sm.sendSay("Village? There's a village here?")
sm.setParam(37)
sm.sendSay("Of course! It's the beauteous #bChu Chu Village#k! Now follow me!")
sm.moveNpcByTemplateId(3003167, False, 320, 250)
sm.sendDelay(2000)
sm.setParam(57)
sm.sendNext("W-what was that?")
sm.sendSay("You know what...? #bA walking, talking lion#k isn't the weirdest thing I've seen in Maple World...")
sm.sendSay("I guess I'll follow him for now!")
sm.forcedMove(False, 800)
sm.sendDelay(3000)
sm.blind(True, 255, 0, 0, 0, 500)
sm.sendDelay(500)
sm.lockInGameUI(False, True)
sm.warp(450002000)
