#Resistance Headquarters :Hospital Room
if sm.hasQuest(1846):
    sm.lockInGameUI(True)
    sm.spawnNpc(1540471, 475, 56)
    sm.spawnNpc(9075304, 200, 56, True)
    sm.removeEscapeButton()
    sm.setSpeakerID(9075304)
    sm.sendNext("We've done what we can medically, but her terrible wounds have left her in a coma. We don't know how long she can go on since she was so weak to begin with.")
    sm.sendNext("There's not much else we can do. Death, or life... It's all up to Orchid. All we can do is wait and watch... I also asked Belle to investigate the Evolution system that attacked her.")
    sm.spawnNpc(2450037, 100, 56, True)
    sm.setSpeakerID(9075305)
    sm.sendNext("I'm back. Ugh, I never want to go back there. Gives me the creeps.")
    sm.setSpeakerID(9075304)
    sm.sendNext("Sorry you had to deal with that. How did the investigations go?")
    sm.setSpeakerID(9075305)
    sm.sendNext("Well, to cut to the chase, the Evolution System has #r#e evolved#k#n by itself. Without any changes to its internal system. I don't want to admit it but, Gelimer was a genius.")
    sm.setSpeakerID(9075304)
    sm.sendNext("Belle, hold your horses and tell us the details. A self-evolving machine... What are you talking about?")
    sm.setSpeakerID(9075305)
    sm.sendNext("That is just what it is. The Evolution System has evolved itself completely anew. It doesn't just defend itself. It's #renhanced itself to a stronger system#k. It's making its own judgements.")
    sm.setSpeakerID(9075305)
    sm.sendNext("It recognized Orchid as a strong enemy and enhanced its own system to accommodate. Gelimer, that madman... he created something big.")
    sm.setSpeakerID(9075304)
    sm.sendNext("Then what happens to the Evolution System now?")
    sm.setSpeakerID(9075305)
    sm.sendNext("Who knows? Whether it will keep itself as-is or chose to make changes... It's all up to the AI.")
    sm.sendNext("You should go check it out for yourself. My words are worth almost nothing, unless you go see it.")
    sm.setSpeakerID(9075304)
    sm.sendNext("Okay, #h #. Go see how the Evolution System has changed itself. Contact me as soon as you see anything out of the ordinary.")
    sm.setSpeakerID(1540471)
    sm.sendNext("Lotus...Lotus...")
    sm.setSpeakerID(9075304)
    sm.sendNext("She will call out Lotus's name even in her times of life-and-death struggles. Do you think he will hear her?")
    sm.lockInGameUI(False)
    sm.warp(957020003, 0)