sm.lockInGameUI(True)
sm.removeEscapeButton()
sm.showFieldEffect("evolving/mapname", 0)
sm.sendDelay(3000)
sm.setSpeakerID(1033230)
sm.sendNext("Gelimer! Why did you move Lotus here without my authorization?!")
sm.setSpeakerID(9075303)
sm.sendNext("M-madame Orchid. You are... early...")
sm.setSpeakerID(1033230)
sm.sendNext("Shut your trap, you greasy old nerd! You don't move my brother unless I tell you to move my brother! My little Lotus needs to be near me or he'll get scared!")
sm.setSpeakerID(9075303)
sm.sendNext("Please lower your voice, dear. There have been some developments...")
sm.setSpeakerID(1033230)
sm.sendNext("I'm developing a need to set your mustache on fire, Gelimer. How long do you think you can keep delaying these experiments? Lotus should have been awake months ago. You know what I'm going to do to you if you don't succeed, don't you?")
sm.setSpeakerID(9075303)
sm.sendNext("Lotus will awaken soon, I assure you. He will wake up, very soon...")
sm.setSpeakerID(1033230)
sm.sendNext("You want more time? Then buy a new watch! I want my brother awake now!")
sm.setSpeakerID(9075303)
sm.sendNext("Perhaps he only needs to hear your voice... Come, take a look.")
sm.showFieldEffect("evolving/swoo1", 0)
sm.sendDelay(4000)
sm.lockInGameUI(False)
sm.warp(957020002, 0)