#Gelimer Research Lab : Second Square
sm.lockInGameUI(True)
sm.hideUser(True)
sm.removeEscapeButton()
sm.spawnNpc(9075303, 750, -104)
sm.setSpeakerID(9075303)
sm.sendNext("W-what, Lotus has cried? How can it be?!")
sm.setSpeakerID(9075302)
sm.sendNext("")
sm.setSpeakerID(9075303)
sm.sendNext("Hm, something has gone wrong. Maybe that screw I put into his brains last night stimulated the lacrimnal galnds. Let me see, where did I put those blueprints?")
sm.setSpeakerID(9075302)
sm.sendNext("Or....chid")
sm.completeQuest(1846)
sm.lockInGameUI(False)
sm.hideUser(False)
sm.warpInstanceOut(957000000)