sm.avatarOriented("Effect/OnUserEff.img/normalEffect/demonSlayer/chatBalloon0")
sm.reservedEffect("Effect/Direction8.img/lightningTutorial2/Scene2")
sm.sendDelay(1000)
sm.removeEscapeButton()
sm.flipDialoguePlayerAsSpeaker()
sm.sendNext("The air feels like black sludge in my lungs. The Black Mage is close...")
sm.sendDelay(1000)

sm.curNodeEventEnd(True)
sm.warp(927020090, 0)