# id 865020061 (Commerci Republic : Canal Battleground 5), field 865020061
sm.createQuestWithQRValue(18418, "B=33252")
sm.lockInGameUI(True, True)
sm.setSpeakerType(3)
sm.setParam(17)
sm.sendNext("There are just too many of them.")
sm.createQuestWithQRValue(18418, "B=33253")
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390234) # Leon Daniella
sm.sendSay("I'm too pretty to die!!")
sm.setParam(17)
sm.sendSay("Leon, don't give up!")
sm.setParam(5)
sm.sendSay("(The situation looks pretty hopeless, though... What can we do?)")
sm.sendDelay(1700)
sm.setInnerOverrideSpeakerTemplateID(9390208) # Riverson
sm.sendNext("Make choice! Surrender... or die!")
sm.setParam(17)
sm.sendSay("Ugh... This doesn't look good.")
sm.sendDelay(1700)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 240, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 140, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 40, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -40, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -140, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -240, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.sendNext("What's going on?!")
sm.sendDelay(2000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 240, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -140, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(800)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 40, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -40, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(800)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 140, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -240, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(800)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 40, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -40, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(800)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 340, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -240, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.sendDelay(1000)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 340, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 240, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 140, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, 40, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -40, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -140, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -240, 0, 0, 0, 0, 0)
sm.showEffect("Effect/DirectionBT.img/effect/Comerz/Boom1", 0, -340, 0, 0, 0, 0, 0)
sm.playSound("cannonshooter/Attack3", 100)
sm.setParam(5)
sm.sendNext("Support troops? Losing battle. Retreat!")
sm.setParam(17)
sm.sendSay("Did the prime minister send them?")
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("I thought daddy was all out of troops.")
sm.startQuest(17631)
sm.spawnNpc(9390247, 985, 348)
sm.showNpcSpecialActionByTemplateId(9390247, "summon", 0)
sm.setParam(17)
sm.sendSay("Hey! I know you!")
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390247) # Robed Lady
sm.sendSay("Oh. It's you.")
sm.setParam(17)
sm.sendSay("Why did you help us?")
sm.setParam(5)
sm.sendSay("Why do you think?")
sm.setParam(17)
sm.sendSay("Er, I don't know...")
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("#h0#! Introduce me!")
sm.setParam(17)
sm.sendSay("Um, this is...")
sm.setParam(5)
sm.sendSay("This is the dashing Leon Daniella of the Daniella Merchant Union, at your service, my lady.")
sm.setInnerOverrideSpeakerTemplateID(9390247) # Robed Lady
sm.sendSay("You're from the Daniella Merchant Union?")
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("I am if you want me to be. You saved my life. You have my eternal devotion.")
sm.setInnerOverrideSpeakerTemplateID(9390247) # Robed Lady
sm.sendSay("I don't want your eternal devotion! I want to be paid for saving your butt!")
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("You really want my butt?")
sm.setInnerOverrideSpeakerTemplateID(9390247) # Robed Lady
sm.sendSay("No, I want your MONEY.")
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("Then you shall have my butt and my money! Do you also want to touch my hair? It's really soft.")
sm.setInnerOverrideSpeakerTemplateID(9390247) # Robed Lady
sm.sendSay("Maybe later. Thanks for the dough. Gotta jet.")
sm.setParam(17)
sm.sendSay("What a character...")
sm.setParam(5)
sm.setInnerOverrideSpeakerTemplateID(9390202) # Leon Daniella
sm.sendSay("So this is what it's like to be in love...")
sm.setParam(17)
sm.sendSay("(Oh, Leon... You have such terrible taste.)")
sm.completeQuestNoCheck(17631)
sm.lockInGameUI(False, True)
sm.createQuestWithQRValue(18418, "B=33254")
